// hu lang variables

tinyMCE.addI18n('hu.ibrowser',{
	title : 'Képkezelő',
	desc : 'Képkezelő',
	library : 'Könyvtár',
	preview : 'Előnézet',
	img_sel : 'Image selection',
	img_info : 'Image information',
	img_upload : 'Kép feltöltése',
	images : 'Kép',
	src : 'Forrás',
	alt : 'Description',
	size : 'Méret',
	align : 'Text flow',
	height : 'Magasság',
	width : 'Szélesség',
	reset : 'Reset Dimensions',
	border : 'Keret',
	hspace : 'Vízszintes távolság',
	vspace : 'Függőleges távolság',
	select : 'Mentés',
	cancel : 'Mégsem',
	uploadtxt : 'Fájl',
	uploadbt : 'Feltöltés',
	align_default : 'Alapértelmezett',
	align_baseline : 'Alapvonalhoz',
	align_top : 'Felülre',
	align_middle : 'Középre',
	align_bottom : 'Alulra',
	align_texttop : 'Szöveg tetejéhez',
	align_absmiddle : 'Szöveg közepéhez',
	align_absbottom : 'Szöveg aljához',
	align_left : 'Balra',
	align_right : 'Jobbra',
	error : 'Hiba',
	errornoimg : 'Válasszon egy képet',
	errornodir : 'Könyvtár nem létezik',
	errorupload : 'Hiba a fájl feltöltésekor.\nPróbálja később',
	errortype : 'Hibás fájltípus',
	errordelete : 'Törlése sikertelen',
	confirmdelete : 'Kép törléséhez kattintson az OK gombra!',
	error_width_nan : 'A szélesség nem szám!',
	error_height_nan : 'A magasság nem szám!',
	error_border_nan : 'A keret nem szám!',
	error_hspace_nan : 'A vízszintes távolság nem szám!',
	error_vspace_nan : 'A függőleges távolság nem szám!',
	error_no_obj_id : 'Mentse az ILIAS objektumot, hogy érvényes azonosítót kaphasson. Anélkül a képkezelő nem tud elindulni!'
});