#!/bin/bash

# This file is part of ILIAS, a powerful learning management system
# published by ILIAS open source e-Learning e.V.
#
# ILIAS is licensed with the GPL-3.0,
# see https://www.gnu.org/licenses/gpl-3.0.en.html
# You should have received a copy of said license along with the
# source code, too.
#
# If this is not the case or you just want to try ILIAS, you'll find
# us at:
# https://www.ilias.de
# https://github.com/ILIAS-eLearning
#
# This script delete all artifacts that are generated by build and deploy scripts.

BASE_PATH="./CI/Style-To-Repo"

function removeBuildArtifacts() {
  if [ -d "${BASE_PATH}/style" ]
  then
    rm -rf ${BASE_PATH}/style
  fi
}

function removeDeployArtifacts() {
  if [ -d "${BASE_PATH}/repo" ]
  then
    rm -rf ${BASE_PATH}/repo
  fi
}