// UK lang variables

tinyMCELang['lang_ibrowser_title'] = 'Image manager';
tinyMCELang['lang_ibrowser_desc'] = 'Image manager';
tinyMCELang['lang_ibrowser_library'] = 'Library';
tinyMCELang['lang_ibrowser_preview'] = 'Preview';
tinyMCELang['lang_ibrowser_img_sel'] = 'Image selection';
tinyMCELang['lang_ibrowser_img_info'] = 'Image information';
tinyMCELang['lang_ibrowser_img_upload'] = 'Image upload';
tinyMCELang['lang_ibrowser_images'] = 'Images';
tinyMCELang['lang_ibrowser_src'] = 'Source';
tinyMCELang['lang_ibrowser_alt'] = 'Description';
tinyMCELang['lang_ibrowser_size'] = 'Size';
tinyMCELang['lang_ibrowser_align'] = 'Text flow';
tinyMCELang['lang_ibrowser_height'] = 'Height';
tinyMCELang['lang_ibrowser_width'] = 'Width';
tinyMCELang['lang_ibrowser_reset'] = 'Reset Dimensions';
tinyMCELang['lang_ibrowser_border'] = 'Border';
tinyMCELang['lang_ibrowser_hspace'] = 'HSpace';
tinyMCELang['lang_ibrowser_vspace'] = 'VSpace';
tinyMCELang['lang_ibrowser_select'] = 'Save';
tinyMCELang['lang_ibrowser_delete'] = 'Delete';
tinyMCELang['lang_ibrowser_cancel'] = 'Cancel';
tinyMCELang['lang_ibrowser_uploadtxt'] = 'File';
tinyMCELang['lang_ibrowser_uploadbt'] = 'Upload';
// error messages
tinyMCELang['lang_ibrowser_error'] = 'Error';
tinyMCELang['lang_ibrowser_errornoimg'] = 'Please select an image';
tinyMCELang['lang_ibrowser_errornodir'] = 'Library doesn\'t physically exist';
tinyMCELang['lang_ibrowser_errorupload'] = 'An error occured while handling the file upload.\nPlease try again later';
tinyMCELang['lang_ibrowser_errortype'] = 'Wrong image file type';
tinyMCELang['lang_ibrowser_errordelete'] = 'Delete failed';
tinyMCELang['lang_ibrowser_confirmdelete'] = 'Click OK to delete image!';
tinyMCELang['lang_ibrowser_error_width_nan'] = 'Width is not a number!';
tinyMCELang['lang_ibrowser_error_height_nan'] = 'Height is not a number!';
tinyMCELang['lang_ibrowser_error_border_nan'] = 'Border is not a number!';
tinyMCELang['lang_ibrowser_error_hspace_nan'] = 'Horizontal space is not a number!';
tinyMCELang['lang_ibrowser_error_vspace_nan'] = 'Vertical space is not a number!';
tinyMCELang['lang_ibrowser_error_no_obj_id'] = 'Please save your ILIAS object to get a valid object id. Without an object id the image manager could not be started!';