checks:
    php: true
filter:
    excluded_paths:
        - 'tests/*'
build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage-file tests'
                coverage:
                    file: 'coverage-file'
                    format: 'php-clover'
