#!/bin/bash

count=0
for file in $(git diff --cached --name-only --diff-filter=ACM | grep -e '\.php$')
do
  	if 	check_for_parse_errors
   	then
	    echo "$file ok"
	else
		echo "$file not ok"
		count+=1
	fi
done
if [[ $count -gt 0 ]]
then 
	exit 1
else
	exit 0
fi