<?php

declare(strict_types=1);

/**
 * This file is part of ILIAS, a powerful learning management system
 * published by ILIAS open source e-Learning e.V.
 *
 * ILIAS is licensed with the GPL-3.0,
 * see https://www.gnu.org/licenses/gpl-3.0.en.html
 * You should have received a copy of said license along with the
 * source code, too.
 *
 * If this is not the case or you just want to try ILIAS, you'll find
 * us at:
 * https://www.ilias.de
 * https://github.com/ILIAS-eLearning
 *
 *********************************************************************/

interface ilPDFRenderer
{
    /**
     * @param string $service
     * @param string $purpose
     * @param array<string, mixed> $config
     * @param ilPDFGenerationJob $job
     * @return void
     */
    public function generatePDF(string $service, string $purpose, array $config, ilPDFGenerationJob $job): void;


    /**
     * Prepare the content processing at the beginning of a PDF generation request
     * Should be used to initialize the processing of latex code
     * The PDF renderers require different image formats generated by the MathJax service
     *
     * @param string $service
     * @param string $purpose
     * @return void
     */
    public function prepareGenerationRequest(string $service, string $purpose): void;
}
