<?php

// often used content types taken from "apache/conf/mime.types"

$mimetypes = array(
    'avi' => 'video/x-msvideo',
    'bmp' => 'image/bmp',
    'class' => 'application/octet-stream',
    'css' => 'text/css',
    'dcr' => 'application/x-director',
    'doc' => 'application/msword',
    'dtd' => 'application/xml-dtd',
    'gif' => 'image/gif',
    'htm' => 'text/html',
    'html' => 'text/html',
    'ico' => 'image/x-icon',
    'jpeg' => 'image/jpeg',
    'jpg' => 'image/jpeg',
    'js' => 'application/x-javascript',
    'mov' => 'video/quicktime',
    'mp3' => 'audio/mpeg',
    'mpeg' => 'video/mpeg',
    'mpg' => 'video/mpeg',
    'ogg' => 'application/ogg',
    'pdb' => 'chemical/x-pdb',
    'pdf' => 'application/pdf',
    'png' => 'image/png',
    'ppt' => 'application/vnd.ms-powerpoint',
    'ps' => 'application/postscript',
    'qt' => 'video/quicktime',
    'ra' => 'audio/x-pn-realaudio',
    'ram' => 'audio/x-pn-realaudio',
    'rdf' => 'application/rdf+xml',
    'rm' => 'application/vnd.rn-realmedia',
    'rtf' => 'text/rtf',
    'smi' => 'application/smil',
    'smil' => 'application/smil',
    'svg' => 'image/svg+xml',
    'swf' => 'application/x-shockwave-flash',
    'txt' => 'text/plain',
    'vrml' => 'model/vrml',
    'wav' => 'audio/x-wav',
    'wrl' => 'model/vrml',
    'xhtml' => 'application/xhtml+xml',
    'xls' => 'application/vnd.ms-excel',
    'xml' => 'application/xml',
    'xsl' => 'application/xml',
    'xslt' => 'application/xslt+xml',
    'xul' => 'application/vnd.mozilla.xul+xml',
    'zip' => 'application/zip'
);
