<?php

/**
 * This file is part of ILIAS, a powerful learning management system
 * published by ILIAS open source e-Learning e.V.
 *
 * ILIAS is licensed with the GPL-3.0,
 * see https://www.gnu.org/licenses/gpl-3.0.en.html
 * You should have received a copy of said license along with the
 * source code, too.
 *
 * If this is not the case or you just want to try ILIAS, you'll find
 * us at:
 * https://www.ilias.de
 * https://github.com/ILIAS-eLearning
 *
 *********************************************************************/

declare(strict_types=1);

namespace ILIAS\TestQuestionPool\ExportImport\Foundation\Normalizing\Attributes;

use Attribute;

/**
 * Declares that a normalizer class supports the input generated by a specific version of ILIAS. Legacy normalizers
 * are used to denormalize data from older versions of ILIAS into the current data model.
 */
#[Attribute(Attribute::TARGET_CLASS)]
final readonly class NormalizesLegacy
{
    /**
     * @param class-string ...$types
     */
    public function __construct(
        public string $version,
        string ...$types
    ) {
        $this->types = $types;
    }

    /** @var list<class-string> */
    public array $types;
}
