<?php

namespace ILIAS\BackgroundTasks\Implementation\Values\ScalarValues;

class FloatValue extends ScalarValue
{
    public function setValue($float)
    {
        if (!is_float($float)) {
            throw new InvalidArgumentException("The value given must be a float! See php-documentation is_float().");
        }

        parent::setValue($float); // TODO: Change the autogenerated stub
    }
}
