<?php
$trayiconinfo = array('broadcastmessage','Broadcast Message');
$trayicondata = 'JHRyYXlpY29uW10gPSBhcnJheSgnYnJvYWRjYXN0bWVzc2FnZScsJ0Jyb2FkY2FzdCBNZXNzYWdlJywnbW9kdWxlcy9icm9hZGNhc3RtZXNzYWdlL2luZGV4LnBocCcsJ19wb3B1cCcsJzM4NScsJzMwMCcsJycsJzEnLCcnKTs=';