#!/bin/bash
#set -x
#set -e
count=0

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`
echo "checking for variable variables"
for file in $(git diff --cached --name-only --diff-filter=ACM | grep -e '\.php$')
do
	if 	grep -E '\$\$' ${file}
	then		
		echo -e "${red}$file not ok, var-vars found, resetting it${reset}\n"
		git reset ${file}
		count+=1
	else
		echo "${green}$file ok${reset}"
	fi
done

if [[ $count -gt 0 ]]
then 
	exit 1
else
	exit 0
fi