<?php return array (
  'ILIAS\\GlobalScreen\\Scope\\MainMenu\\Provider\\StaticMainMenuProvider' => 
  array (
    0 => 'ILIAS\\Administration\\AdministrationMainBarProvider',
    1 => 'ILIAS\\Badge\\Provider\\BadgeMainBarProvider',
    2 => 'ILIAS\\Calendar\\Provider\\CalendarMainBarProvider',
    3 => 'ILIAS\\Certificate\\Provider\\CertificateMainBarProvider',
    4 => 'ILIAS\\Chatroom\\Provider\\ChatMainBarProvider',
    5 => 'ILIAS\\Contact\\Provider\\ContactMainBarProvider',
    6 => 'ILIAS\\EmployeeTalk\\Provider\\MyStaffListEntryProvider',
    7 => 'ILIAS\\LearningHistory\\LearningHistoryMainBarProvider',
    8 => 'ILIAS\\LearningProgress\\LPMainBarProvider',
    9 => 'ILIAS\\Mail\\Provider\\MailMainBarProvider',
    10 => 'ILIAS\\MainMenu\\Provider\\CustomMainBarProvider',
    11 => 'ILIAS\\MainMenu\\Provider\\StandardTopItemsProvider',
    12 => 'ILIAS\\Membership\\GlobalScreen\\MembershipMainBarProvider',
    13 => 'ILIAS\\MyStaff\\Provider\\StaffMainBarProvider',
    14 => 'ILIAS\\News\\Provider\\NewsMainBarProvider',
    15 => 'ILIAS\\Notes\\Provider\\NotesMainBarProvider',
    16 => 'ILIAS\\OnScreenChat\\Provider\\OnScreenChatProvider',
    17 => 'ILIAS\\OrgUnit\\Provider\\OrgUnitMainBarProvider',
    18 => 'ILIAS\\PersonalWorkspace\\Provider\\WorkspaceMainBarProvider',
    19 => 'ILIAS\\Portfolio\\Provider\\PortfolioMainBarProvider',
    20 => 'ILIAS\\Repository\\Provider\\RepositoryMainBarProvider',
    21 => 'ILIAS\\Skill\\Provider\\SkillMainBarProvider',
    22 => 'ILIAS\\Tagging\\Provider\\TaggingMainBarProvider',
    23 => 'ILIAS\\Tasks\\DerivedTasks\\Provider\\DerivedTaskMainBarProvider',
  ),
  'ILIAS\\GlobalScreen\\Scope\\MetaBar\\Provider\\StaticMetaBarProvider' => 
  array (
    0 => 'ILIAS\\Init\\Provider\\StartUpMetaBarProvider',
    1 => 'ILIAS\\Notifications\\Provider\\NotificationCenterProvider',
    2 => 'ILIAS\\Search\\Provider\\SearchMetaBarProvider',
    3 => 'ILIAS\\User\\Provider\\UserMetaBarProvider',
    4 => 'ilAwarenessMetaBarProvider',
    5 => 'ilHelpMetaBarProvider',
  ),
  'ILIAS\\GlobalScreen\\Scope\\Tool\\Provider\\DynamicToolProvider' => 
  array (
    0 => 'ForumGlobalScreenToolsProvider',
    1 => 'ILIAS\\Mail\\Provider\\MailGlobalScreenToolProvider',
    2 => 'ILIAS\\MetaData\\Editor\\Tree\\MDEditorToolProvider',
    3 => 'ILIAS\\OrgUnit\\Provider\\OrgUnitToolProvider',
    4 => 'SystemStylesGlobalScreenToolProvider',
    5 => 'ilAdminGSToolProvider',
    6 => 'ilCOPageEditGSToolProvider',
    7 => 'ilExerciseGSToolProvider',
    8 => 'ilHelpGSToolProvider',
    9 => 'ilLMEditGSToolProvider',
    10 => 'ilLMGSToolProvider',
    11 => 'ilMediaPoolGSToolProvider',
    12 => 'ilSkillGSToolProvider',
    13 => 'ilTaxonomyGSToolProvider',
    14 => 'ilWorkspaceGSToolProvider',
  ),
  'ILIAS\\GlobalScreen\\Scope\\Layout\\Provider\\ModificationProvider' => 
  array (
    0 => 'DashboardLayoutProvider',
    1 => 'ILIAS\\Container\\Screen\\MemberViewLayoutProvider',
    2 => 'ILIAS\\Init\\Provider\\StartUpModificationProvider',
    3 => 'ILIAS\\LTI\\Screen\\LtiViewLayoutProvider',
    4 => 'ILIAS\\Repository\\Provider\\RepositoryOpenGraphExposer',
    5 => 'ILIAS\\UICore\\PageContentProvider',
    6 => 'ILIAS\\components\\WOPI\\Embed\\EmbeddedApplicationGSProvider',
    7 => 'ilHTMLExportViewLayoutProvider',
    8 => 'ilHelpViewLayoutProvider',
    9 => 'ilLMHtmlExportViewLayoutProvider',
    10 => 'ilLSViewLayoutProvider',
    11 => 'ilMDKeywordExposer',
    12 => 'ilTestPlayerLayoutProvider',
  ),
  'ILIAS\\GlobalScreen\\Scope\\Notification\\Provider\\NotificationProvider' => 
  array (
    0 => 'ILIAS\\AdministrativeNotification\\GlobalScreen\\ADNProvider',
    1 => 'ILIAS\\BackgroundTasks\\Provider\\BTNotificationProvider',
    2 => 'ILIAS\\Badge\\GlobalScreen\\BadgeNotificationProvider',
    3 => 'ILIAS\\Chatroom\\GlobalScreen\\ChatInvitationNotificationProvider',
    4 => 'ILIAS\\Contact\\Provider\\ContactNotificationProvider',
    5 => 'ILIAS\\Mail\\Provider\\MailNotificationProvider',
    6 => 'ilLSCompletionNotificationProvider',
  ),
  'ILIAS\\GlobalScreen\\Scope\\Toast\\Provider\\ToastProvider' => 
  array (
    0 => 'ILIAS\\Notifications\\Provider\\AwarenessToastProvider',
    1 => 'ILIAS\\Notifications\\Provider\\NotificationToastProvider',
    2 => 'ilLSToastProvider',
  ),
);