<?php
$BEAUT_PATH = realpath(".")."/Services/COPage/syntax_highlight/php";
if (!isset ($BEAUT_PATH)) return;
require_once("$BEAUT_PATH/Beautifier/HFile.php");
  class HFile_asm75 extends HFile{
   function HFile_asm75(){
     $this->HFile();	
/*************************************/
// Beautifier Highlighting Configuration File 
// Asm 75x
/*************************************/
// Flags

$this->nocase            	= "0";
$this->notrim            	= "0";
$this->perl              	= "0";

// Colours

$this->colours        	= array("blue", "purple", "gray", "brown", "blue");
$this->quotecolour       	= "blue";
$this->blockcommentcolour	= "green";
$this->linecommentcolour 	= "green";

// Indent Strings

$this->indent            	= array();
$this->unindent          	= array();

// String characters and delimiters

$this->stringchars       	= array();
$this->delimiters        	= array("#", "~", "!", "%", "^", "&", "*", "(", ")", "=", "|", "\\", "/", "{", "}", "[", "]", "\"", "<", ">", " ", ",", "	", ".", "?");
$this->escchar           	= "";

// Comment settings

$this->linecommenton     	= array(";");
$this->blockcommenton    	= array("");
$this->blockcommentoff   	= array("");

// Keywords (keyword mapping to colour number)

$this->keywords          	= array(
			"ADDC" => "1", 
			"ADDS" => "1", 
			"AND" => "1", 
			"AND1" => "1", 
			"BR" => "1", 
			"BRA" => "1", 
			"BRCB" => "1", 
			"BRK" => "1", 
			"CALL" => "1", 
			"CALLA" => "1", 
			"CALLF" => "1", 
			"CLR1" => "1", 
			"DECS" => "1", 
			"DI" => "1", 
			"EI" => "1", 
			"EQ" => "1", 
			"GE" => "1", 
			"GT" => "1", 
			"GETI" => "1", 
			"HALT" => "1", 
			"HIGH" => "1", 
			"IN" => "1", 
			"INCS" => "1", 
			"LOW" => "1", 
			"LT" => "1", 
			"MOD" => "1", 
			"MOV" => "1", 
			"MOV1" => "1", 
			"MOVT" => "1", 
			"NE" => "1", 
			"NOP" => "1", 
			"NOT" => "1", 
			"OR" => "1", 
			"OR1" => "1", 
			"OUT" => "1", 
			"OUT3" => "1", 
			"POP" => "1", 
			"PUSH" => "1", 
			"RET" => "1", 
			"RETI" => "1", 
			"RETS" => "1", 
			"ROLC" => "1", 
			"RORC" => "1", 
			"SEL" => "1", 
			"SEL1" => "1", 
			"SKE" => "1", 
			"SKF" => "1", 
			"SKT" => "1", 
			"SKTCLR" => "1", 
			"STOP" => "1", 
			"SUBC" => "1", 
			"SUBS" => "1", 
			"SHL" => "1", 
			"SHR" => "1", 
			"XCH" => "1", 
			"XOR" => "1", 
			"XOR1" => "1", 
			"CSEG" => "2", 
			"DB" => "2", 
			"DBIT" => "2", 
			"DS" => "2", 
			"DSEG" => "2", 
			"DW" => "2", 
			"END" => "2", 
			"EQU" => "2", 
			"EXTRN" => "2", 
			"NAME" => "2", 
			"ORG" => "2", 
			"PUBLIC" => "2", 
			"SET" => "2", 
			"STKLN" => "2", 
			"TBR" => "2", 
			"TCALL" => "2", 
			"VENT0" => "2", 
			"VENT1" => "2", 
			"VENT2" => "2", 
			"VENT3" => "2", 
			"VENT4" => "2", 
			"VENT5" => "2", 
			"VENT6" => "2", 
			"VENT7" => "2", 
			"$" => "3", 
			"MACRO" => "3", 
			"ENDM" => "3", 
			"EXITM" => "3", 
			"GLOBAL" => "3", 
			"IRP" => "3", 
			"IRPC" => "3", 
			"REPT" => "3", 
			"STACK" => "3", 
			"@BCDE" => "4", 
			"@BCXA" => "4", 
			"@DE" => "4", 
			"@DL" => "4", 
			"@HL" => "4", 
			"@HL+" => "4", 
			"@HL-" => "4", 
			"@PCDE" => "4", 
			"@PCXA" => "4", 
			"A" => "4", 
			"B" => "4", 
			"BC" => "4", 
			"BC\'" => "4", 
			"BCDE" => "4", 
			"BCXA" => "4", 
			"C" => "4", 
			"CY" => "4", 
			"D" => "4", 
			"DE" => "4", 
			"DE\'" => "4", 
			"E" => "4", 
			"H" => "4", 
			"HL" => "4", 
			"HL\'" => "4", 
			"HL+" => "4", 
			"HL-" => "4", 
			"L" => "4", 
			"MB0" => "4", 
			"MB1" => "4", 
			"MB2" => "4", 
			"MB3" => "4", 
			"MB4" => "4", 
			"MB5" => "4", 
			"MB6" => "4", 
			"MB7" => "4", 
			"MB8" => "4", 
			"MB9" => "4", 
			"MB10" => "4", 
			"MB11" => "4", 
			"MB12" => "4", 
			"MB13" => "4", 
			"MB14" => "4", 
			"MB15" => "4", 
			"PCDE" => "4", 
			"PCXA" => "4", 
			"RB0" => "4", 
			"RB1" => "4", 
			"RB2" => "4", 
			"RB3" => "4", 
			"RB4" => "4", 
			"RB5" => "4", 
			"RB6" => "4", 
			"RB7" => "4", 
			"RB8" => "4", 
			"RB9" => "4", 
			"RB10" => "4", 
			"RB11" => "4", 
			"RB12" => "4", 
			"RB13" => "4", 
			"RB14" => "4", 
			"RB15" => "4", 
			"X" => "4", 
			"XA" => "4", 
			"XA\'" => "4", 
			"ACKD" => "5", 
			"ACKE" => "5", 
			"ACKT" => "5", 
			"ADM" => "5", 
			"BP0" => "5", 
			"BP1" => "5", 
			"BP2" => "5", 
			"BP3" => "5", 
			"BP4" => "5", 
			"BP5" => "5", 
			"BP6" => "5", 
			"BP7" => "5", 
			"BS" => "5", 
			"BSB0" => "5", 
			"BSB1" => "5", 
			"BSB2" => "5", 
			"BSB3" => "5", 
			"BSYE" => "5", 
			"BT" => "5", 
			"BTM" => "5", 
			"CLOM" => "5", 
			"CMDD" => "5", 
			"CMDT" => "5", 
			"COI" => "5", 
			"CSIE" => "5", 
			"CSIE0" => "5", 
			"CSIE1" => "5", 
			"CSIM" => "5", 
			"CSIM0" => "5", 
			"CSIM1" => "5", 
			"DACE0" => "5", 
			"DACE1" => "5", 
			"DACS0" => "5", 
			"DACS1" => "5", 
			"DIGS" => "5", 
			"DIMS" => "5", 
			"DSPM" => "5", 
			"EOC" => "5", 
			"EOT" => "5", 
			"EWC" => "5", 
			"EWE" => "5", 
			"EWP" => "5", 
			"EWST" => "5", 
			"GATEC" => "5", 
			"IE" => "5", 
			"IE1" => "5", 
			"IE2" => "5", 
			"IE3" => "5", 
			"IE4" => "5", 
			"IEBT" => "5", 
			"IEBWT" => "5", 
			"IECSI" => "5", 
			"IECSIO" => "5", 
			"IEEE" => "5", 
			"IEKS" => "5", 
			"IEMFT" => "5", 
			"IEMT0" => "5", 
			"IEMT1" => "5", 
			"IEOW" => "5", 
			"IESIO" => "5", 
			"IET0" => "5", 
			"IET1" => "5", 
			"IETPG" => "5", 
			"IEW" => "5", 
			"IM0" => "5", 
			"IM1" => "5", 
			"IM2" => "5", 
			"IPS" => "5", 
			"IRQ1" => "5", 
			"IRQ2" => "5", 
			"IRQ3" => "5", 
			"IRQ4" => "5", 
			"IRQBT" => "5", 
			"IRQBWT" => "5", 
			"IRQCSI" => "5", 
			"IRQCSIO" => "5", 
			"IRQEE" => "5", 
			"IRQKS" => "5", 
			"IRQMFT" => "5", 
			"IRQMT0" => "5", 
			"IRQMT1" => "5", 
			"IRQOW" => "5", 
			"IRQSIO" => "5", 
			"IRQT0" => "5", 
			"IRQT1" => "5", 
			"IRQTPG" => "5", 
			"IRQW" => "5", 
			"IST0" => "5", 
			"IST1" => "5", 
			"KR0" => "5", 
			"KR1" => "5", 
			"KR2" => "5", 
			"KR3" => "5", 
			"KR4" => "5", 
			"KR5" => "5", 
			"KR6" => "5", 
			"KR7" => "5", 
			"KS0" => "5", 
			"KS1" => "5", 
			"KS2" => "5", 
			"KSF" => "5", 
			"LCDC" => "5", 
			"LCDM" => "5", 
			"LPS" => "5", 
			"MBE" => "5", 
			"MBS" => "5", 
			"MFTC" => "5", 
			"MFTH" => "5", 
			"MFTL" => "5", 
			"MFTM" => "5", 
			"MODH" => "5", 
			"MODL" => "5", 
			"MT0" => "5", 
			"MT1" => "5", 
			"MTM0" => "5", 
			"MTM1" => "5", 
			"MTOE0" => "5", 
			"MTOE1" => "5", 
			"MTOF0" => "5", 
			"MTOF1" => "5", 
			"PCC" => "5", 
			"PDGB" => "5", 
			"PMGA" => "5", 
			"PMGB" => "5", 
			"PMGC" => "5", 
			"PMGD" => "5", 
			"PMGE" => "5", 
			"POGA" => "5", 
			"POGB" => "5", 
			"POGC" => "5", 
			"POGD" => "5", 
			"PONF" => "5", 
			"PORT0" => "5", 
			"PORT1" => "5", 
			"PORT2" => "5", 
			"PORT3" => "5", 
			"PORT4" => "5", 
			"PORT5" => "5", 
			"PORT6" => "5", 
			"PORT7" => "5", 
			"PORT8" => "5", 
			"PORT9" => "5", 
			"PORT10" => "5", 
			"PORT11" => "5", 
			"PORT12" => "5", 
			"PORT13" => "5", 
			"PORT14" => "5", 
			"PORT15" => "5", 
			"PORT16" => "5", 
			"PORT17" => "5", 
			"PORT18" => "5", 
			"PORT19" => "5", 
			"PORT20" => "5", 
			"PORTH" => "5", 
			"PSW" => "5", 
			"PTH0" => "5", 
			"PTH1" => "5", 
			"PTHM" => "5", 
			"RBE" => "5", 
			"RBS" => "5", 
			"RELD" => "5", 
			"RELOAD" => "5", 
			"RELT" => "5", 
			"SA" => "5", 
			"SBS" => "5", 
			"SCC" => "5", 
			"SEGEX" => "5", 
			"SIO" => "5", 
			"SIO0" => "5", 
			"SIO1" => "5", 
			"SIOM" => "5", 
			"SOC" => "5", 
			"SP" => "5", 
			"STATA" => "5", 
			"STATB" => "5", 
			"SVA" => "5", 
			"T0" => "5", 
			"T1" => "5", 
			"TBC0" => "5", 
			"TBC4" => "5", 
			"TBC8" => "5", 
			"TBCM" => "5", 
			"TGC" => "5", 
			"TGM" => "5", 
			"TGS" => "5", 
			"TI0" => "5", 
			"TI1" => "5", 
			"TM0" => "5", 
			"TM1" => "5", 
			"TMOD0" => "5", 
			"TMOD1" => "5", 
			"TO0" => "5", 
			"TO1" => "5", 
			"TOE0" => "5", 
			"TOE1" => "5", 
			"TOF0" => "5", 
			"TOF1" => "5", 
			"TPGM" => "5", 
			"WDTM" => "5", 
			"WM" => "5", 
			"WUP" => "5");

// Special extensions

// Each category can specify a PHP function that returns an altered
// version of the keyword.
        
        

$this->linkscripts    	= array(
			"1" => "donothing", 
			"2" => "donothing", 
			"3" => "donothing", 
			"4" => "donothing", 
			"5" => "donothing");
}


function donothing($keywordin)
{
	return $keywordin;
}

}?>
