<?php
$BEAUT_PATH = realpath(".")."/Services/COPage/syntax_highlight/php";
if (!isset ($BEAUT_PATH)) return;
require_once("$BEAUT_PATH/Beautifier/HFile.php");

class HFile_4dos4nt extends HFile{
   function HFile_4dos4nt(){
     $this->HFile();
/*************************************/
// Beautifier Highlighting Configuration File
// 4DOS/4NT Batch
/*************************************/
// Flags

$this->nocase            	= "1";
$this->notrim            	= "0";
$this->perl              	= "0";

// Colours

$this->colours        	= array("blue", "purple", "gray", "brown", "blue", "brown", "purple", "gray");
$this->quotecolour       	= "blue";
$this->blockcommentcolour	= "green";
$this->linecommentcolour 	= "green";

// Indent Strings

$this->indent            	= array( "SWITCH", "THEN");
$this->unindent          	= array( "ENDIFF", "ENDSWITCH");

// String characters and delimiters

$this->stringchars       	= array("\"");
$this->delimiters        	= array("%", "!", "$", "^", "*", "(", ")", "+", "=", "|", "{", "}", "[", "]", "\"", "'", " ", "	", ",");
$this->escchar           	= "";

// Comment settings

$this->linecommenton     	= array("REM");
$this->blockcommenton    	= array("");
$this->blockcommentoff   	= array("");

// Keywords (keyword mapping to colour number)

$this->keywords          	= array(
			"==" => "1",
			"=" => "1",
			"|" => "1",
			"," => "1",
			"." => "1",
			">" => "1",
			">>" => "1",
			">&>" => "1",
			"<" => "1",
			"<<" => "1",
			"<&<" => "1",
			"?" => "2",
			"ACTIVATE" => "2",
			"ALIAS" => "2",
			"ASSOC" => "2",
			"AT" => "2",
			"ATTRIB" => "2",
			"BEEP" => "2",
			"BREAK" => "2",
			"CALL" => "2",
			"CANCEL" => "2",
			"CASE" => "2",
			"CD" => "2",
			"CDD" => "2",
			"CHCP" => "2",
			"CHDIR" => "2",
			"CLS" => "2",
			"COLOR" => "2",
			"COPY" => "2",
			"CTTY" => "2",
			"DATE" => "2",
			"DDEEXEC" => "2",
			"DEFAULT" => "2",
			"DEL" => "2",
			"DELAY" => "2",
			"DESCRIBE" => "2",
			"DETACH" => "2",
			"DIR" => "2",
			"DIRHISTORY" => "2",
			"DIRS" => "2",
			"DO" => "2",
			"DPATH" => "2",
			"DRAWBOX" => "2",
			"DRAWHLINE" => "2",
			"DRAWVLINE" => "2",
			"ECHO" => "2",
			"ECHO." => "2",
			"ECHOERR" => "2",
			"ECHOS" => "2",
			"ECHOSERR" => "2",
			"ENDDO" => "2",
			"ENDIFF" => "2",
			"ENDLOCAL" => "2",
			"ENDSWITCH" => "2",
			"ENDTEXT" => "2",
			"ERASE" => "2",
			"ESET" => "2",
			"EXCEPT" => "2",
			"EXIT" => "2",
			"FFIND" => "2",
			"FIND" => "2",
			"FOR" => "2",
			"FREE" => "2",
			"FTYPE" => "2",
			"GLOBAL" => "2",
			"GOSUB" => "2",
			"GREP" => "2",
			"GOTO" => "2",
			"HELP" => "2",
			"HISTORY" => "2",
			"IF" => "2",
			"IFF" => "2",
			"INKEY" => "2",
			"INPUT" => "2",
			"KEYBD" => "2",
			"KEYS" => "2",
			"KEYSTACK" => "2",
			"LH" => "2",
			"LIST" => "2",
			"LOADBTM" => "2",
			"LOADHIGH" => "2",
			"LOCK" => "2",
			"LOG" => "2",
			"MD" => "2",
			"MEMORY" => "2",
			"MKDIR" => "2",
			"MOVE" => "2",
			"MSGBOX" => "2",
			"OPTION" => "2",
			"PATH" => "2",
			"PAUSE" => "2",
			"POPD" => "2",
			"PROMPT" => "2",
			"PUSHD" => "2",
			"QUERYBOX" => "2",
			"QUIT" => "2",
			"RD" => "2",
			"REBOOT" => "2",
			"REN" => "2",
			"RENAME" => "2",
			"RETURN" => "2",
			"RMDIR" => "2",
			"SCREEN" => "2",
			"SCRPUT" => "2",
			"SELECT" => "2",
			"SET" => "2",
			"SETDOS" => "2",
			"SETLOCAL" => "2",
			"SHIFT" => "2",
			"SHRALIAS" => "2",
			"START" => "2",
			"SWAPPING" => "2",
			"SWITCH" => "2",
			"TEE" => "2",
			"TEXT" => "2",
			"TIME" => "2",
			"TIMER" => "2",
			"TITLE" => "2",
			"TOUCH" => "2",
			"TREE" => "2",
			"TRUENAME" => "2",
			"TYPE" => "2",
			"UNALIAS" => "2",
			"UNLOCK" => "2",
			"UNSET" => "2",
			"VER" => "2",
			"VERIFY" => "2",
			"VOL" => "2",
			"VSCRPUT" => "2",
			"WINDOW" => "2",
			"Y" => "2",
			".AND." => "3",
			".OR." => "3",
			".XOR." => "3",
			"BY" => "3",
			"DEFINED" => "3",
			"DIREXIST" => "3",
			"ELSE" => "3",
			"ELSEIFF" => "3",
			"EQ" => "3",
			"EQL" => "3",
			"EQU" => "3",
			"ERROR" => "3",
			"ERRORLEVEL" => "3",
			"ERRORMSG" => "3",
			"EXIST" => "3",
			"FOREVER" => "3",
			"GE" => "3",
			"GEQ" => "3",
			"GT" => "3",
			"GTR" => "3",
			"IN" => "3",
			"ISALIAS" => "3",
			"ISDIR" => "3",
			"ISINTERNAL" => "3",
			"ISLABEL" => "3",
			"ISWINDOW" => "3",
			"ITERATE" => "3",
			"LE" => "3",
			"LEAVE" => "3",
			"LEQ" => "3",
			"LSS" => "3",
			"LT" => "3",
			"NE" => "3",
			"NEQ" => "3",
			"NOT" => "3",
			"ON" => "3",
			"OFF" => "3",
			"THEN" => "3",
			"UNTIL" => "3",
			"WHILE" => "3",
			"_4VER" => "4",
			"_ALIAS" => "4",
			"_ANSI" => "4",
			"_APMAC" => "4",
			"_APMBATT" => "4",
			"_APMLIFE" => "4",
			"_BATCH" => "4",
			"_BATCHLINE" => "4",
			"_BATCHNAME" => "4",
			"_BG" => "4",
			"_BOOT" => "4",
			"_CI" => "4",
			"_CMDPROC" => "4",
			"_CO" => "4",
			"_CODEPAGE" => "4",
			"_COLUMN" => "4",
			"_COLUMNS" => "4",
			"_COUNTRY" => "4",
			"_CPU" => "4",
			"_CWD" => "4",
			"_CWDS" => "4",
			"_CWP" => "4",
			"_CWPS" => "4",
			"_DATE" => "4",
			"_DAY" => "4",
			"_DISK" => "4",
			"_DNAME" => "4",
			"_DOS" => "4",
			"_DOSVER" => "4",
			"_DOW" => "4",
			"_DOWI" => "4",
			"_DOY" => "4",
			"_DPMI" => "4",
			"_DV" => "4",
			"_ENV" => "4",
			"_FG" => "4",
			"_GDIFREE" => "4",
			"_HLOGFILE" => "4",
			"_HOUR" => "4",
			"_KBHIT" => "4",
			"_KSTACK" => "4",
			"_LASTDISK" => "4",
			"_LOGFILE" => "4",
			"_MINUTE" => "4",
			"_MONITOR" => "4",
			"_MONTH" => "4",
			"_MOUSE" => "4",
			"_NDP" => "4",
			"_PID" => "4",
			"_PIPE" => "4",
			"_PPID" => "4",
			"_PTYPE" => "4",
			"_ROW" => "4",
			"_ROWS" => "4",
			"_SECOND" => "4",
			"_SELECTED" => "4",
			"_SHELL" => "4",
			"_SID" => "4",
			"_SWAPPING" => "4",
			"_SYSERR" => "4",
			"_SYSFREE" => "4",
			"_TIME" => "4",
			"_TRANSIENT" => "4",
			"_USERFREE" => "4",
			"_VIDEO" => "4",
			"_WIN" => "4",
			"_WINDIR" => "4",
			"_WINSYSDIR" => "4",
			"_WINTITLE" => "4",
			"_WINVER" => "4",
			"_XPIXELS" => "4",
			"_YEAR" => "4",
			"_YPIXELS" => "4",
			"_?" => "4",
			"@ALIAS" => "5",
			"@ALTNAME" => "5",
			"@ASCII" => "5",
			"@ATTRIB" => "5",
			"@CDROM" => "5",
			"@CHAR" => "5",
			"@CLIP" => "5",
			"@COMMA" => "5",
			"@CONVERT" => "5",
			"@DATE" => "5",
			"@DAY" => "5",
			"@DEC" => "5",
			"@DESCRIPT" => "5",
			"@DEVICE" => "5",
			"@DISKFREE" => "5",
			"@DISKTOTAL" => "5",
			"@DISKUSED" => "5",
			"@DOSMEM" => "5",
			"@DOW" => "5",
			"@DOWI" => "5",
			"@DOY" => "5",
			"@EAREAD" => "5",
			"@EAWRITE" => "5",
			"@EMS" => "5",
			"@EVAL" => "5",
			"@EXEC" => "5",
			"@EXECSTR" => "5",
			"@EXETYPE" => "5",
			"@EXPAND" => "5",
			"@EXT" => "5",
			"@EXTENDED" => "5",
			"@FILEAGE" => "5",
			"@FILECLOSE" => "5",
			"@FILEDATE" => "5",
			"@FILENAME" => "5",
			"@FILEOPEN" => "5",
			"@FILEREAD" => "5",
			"@FILES" => "5",
			"@FILESEEK" => "5",
			"@FILESEEKL" => "5",
			"@FILESIZE" => "5",
			"@FILETIME" => "5",
			"@FILEWRITE" => "5",
			"@FILEWRITEB" => "5",
			"@FINDCLOSE" => "5",
			"@FINDFIRST" => "5",
			"@FINDNEXT" => "5",
			"@FORMAT" => "5",
			"@FSTYPE" => "5",
			"@FULL" => "5",
			"@GETDIR" => "5",
			"@GETFILE" => "5",
			"@IF" => "5",
			"@INC" => "5",
			"@INDEX" => "5",
			"@INIREAD" => "5",
			"@INIWRITE" => "5",
			"@INSERT" => "5",
			"@INSTR" => "5",
			"@INT" => "5",
			"@LABEL" => "5",
			"@LEFT" => "5",
			"@LEN" => "5",
			"@LFN" => "5",
			"@LINE" => "5",
			"@LINES" => "5",
			"@LOWER" => "5",
			"@LPT" => "5",
			"@MAKEAGE" => "5",
			"@MAKEDATE" => "5",
			"@MAKETIME" => "5",
			"@MASTER" => "5",
			"@MONTH" => "5",
			"@NAME" => "5",
			"@NUMERIC" => "5",
			"@PATH" => "5",
			"@RANDOM" => "5",
			"@READSCR" => "5",
			"@READY" => "5",
			"@REMOTE" => "5",
			"@REMOVABLE" => "5",
			"@REPEAT" => "5",
			"@REPLACE" => "5",
			"@REXX" => "5",
			"@RIGHT" => "5",
			"@SEARCH" => "5",
			"@SELECT" => "5",
			"@SFN" => "5",
			"@STRIP" => "5",
			"@SUBSTR" => "5",
			"@TIME" => "5",
			"@TIMER" => "5",
			"@TRIM" => "5",
			"@TRUENAME" => "5",
			"@UNIQUE" => "5",
			"@UPPER" => "5",
			"@WILD" => "5",
			"@WORD" => "5",
			"@WORDS" => "5",
			"@XMS" => "5",
			"@YEAR" => "5",
			"**" => "8",
			":" => "6",
			"A:" => "7",
			"B:" => "7",
			"C:" => "7",
			"D:" => "7",
			"E:" => "7",
			"F:" => "7",
			"G:" => "7",
			"H:" => "7",
			"O:" => "7",
			"-" => "8",
			"/" => "8");

// Special extensions

// Each category can specify a PHP function that returns an altered
// version of the keyword.



$this->linkscripts    	= array(
			"1" => "donothing",
			"2" => "donothing",
			"3" => "donothing",
			"4" => "donothing",
			"5" => "donothing",
			"8" => "donothing",
			"6" => "donothing",
			"7" => "donothing");
}


function donothing($keywordin)
{
	return $keywordin;
}

}?>
