<?php
$BEAUT_PATH = realpath(".")."/Services/COPage/syntax_highlight/php";
if (!isset ($BEAUT_PATH)) return;
require_once("$BEAUT_PATH/Beautifier/HFile.php");
  class HFile_c167complink extends HFile{
   function HFile_c167complink(){
     $this->HFile();	
/*************************************/
// Beautifier Highlighting Configuration File 
// 'C' for C167
/*************************************/
// Flags

$this->nocase            	= "0";
$this->notrim            	= "0";
$this->perl              	= "0";

// Colours

$this->colours        	= array("blue", "purple", "gray", "brown", "blue");
$this->quotecolour       	= "blue";
$this->blockcommentcolour	= "green";
$this->linecommentcolour 	= "green";

// Indent Strings

$this->indent            	= array("{");
$this->unindent          	= array("}");

// String characters and delimiters

$this->stringchars       	= array("\"", "'");
$this->delimiters        	= array("~", "!", "@", "%", "^", "&", "*", "(", ")", "-", "+", "=", "|", "\\", "/", "{", "}", "[", "]", ":", ";", "\"", "'", "<", ">", " ", ",", "	", "?");
$this->escchar           	= "";

// Comment settings

$this->linecommenton     	= array("//");
$this->blockcommenton    	= array("/*");
$this->blockcommentoff   	= array("*/");

// Keywords (keyword mapping to colour number)

$this->keywords          	= array(
			"#define" => "1", 
			"#else" => "1", 
			"#endif" => "1", 
			"#if" => "1", 
			"#ifdef" => "1", 
			"#ifndef" => "1", 
			"#include" => "1", 
			"#pragma" => "1", 
			"#undef" => "1", 
			"alias" => "1", 
			"align" => "1", 
			"asm" => "1", 
			"asm_noflush" => "1", 
			"automatic" => "1", 
			"class" => "1", 
			"clear" => "1", 
			"combine" => "1", 
			"cse" => "1", 
			"default_attributes" => "1", 
			"define" => "1", 
			"endasm" => "1", 
			"eramdata" => "1", 
			"fix_byte_write" => "1", 
			"global" => "1", 
			"include" => "1", 
			"iramdata" => "1", 
			"macro" => "1", 
			"noalias" => "1", 
			"noclear" => "1", 
			"nofix_byte_write" => "1", 
			"noframe" => "1", 
			"nomacro" => "1", 
			"nosource" => "1", 
			"public" => "1", 
			"regdef" => "1", 
			"restore_attributes" => "1", 
			"romdata" => "1", 
			"save_attributes" => "1", 
			"size" => "1", 
			"source" => "1", 
			"speed" => "1", 
			"static" => "1", 
			"switch_force_table" => "1", 
			"switch_smart" => "1", 
			"_at" => "2", 
			"_atbit" => "2", 
			"bit" => "2", 
			"bita" => "2", 
			"bitword" => "2", 
			"break" => "2", 
			"case" => "2", 
			"char" => "2", 
			"const" => "2", 
			"continue" => "2", 
			"default" => "2", 
			"do" => "2", 
			"double" => "2", 
			"else" => "2", 
			"esfr" => "2", 
			"esfrbit" => "2", 
			"extern" => "2", 
			"far" => "2", 
			"float" => "2", 
			"for" => "2", 
			"goto" => "2", 
			"huge" => "2", 
			"if" => "2", 
			"int" => "2", 
			"iram" => "2", 
			"long" => "2", 
			"near" => "2", 
			"register" => "2", 
			"return" => "2", 
			"sfr" => "2", 
			"sfrbit" => "2", 
			"signed" => "2", 
			"size_t" => "2", 
			"struct" => "2", 
			"switch" => "2", 
			"system" => "2", 
			"typedef" => "2", 
			"unsigned" => "2", 
			"void" => "2", 
			"volatile" => "2", 
			"while" => "2", 
			"_fstrcat" => "3", 
			"_fstrchr" => "3", 
			"_fstrcmp" => "3", 
			"_fstrcpy" => "3", 
			"_fstrcspn" => "3", 
			"_fstrlen" => "3", 
			"_fstrncat" => "3", 
			"_fstrncmp" => "3", 
			"_fstrncpy" => "3", 
			"_fstrpbrk" => "3", 
			"_fstrrchr" => "3", 
			"_fstrspn" => "3", 
			"_fstrstr" => "3", 
			"_fstrtok" => "3", 
			"_hstrcat" => "3", 
			"_hstrchr" => "3", 
			"_hstrcmp" => "3", 
			"_hstrcpy" => "3", 
			"_hstrcspn" => "3", 
			"_hstrlen" => "3", 
			"_hstrncat" => "3", 
			"_hstrncmp" => "3", 
			"_hstrncpy" => "3", 
			"_hstrpbrk" => "3", 
			"_hstrrchr" => "3", 
			"_hstrspn" => "3", 
			"_hstrstr" => "3", 
			"_hstrtok" => "3", 
			"_ioread" => "3", 
			"_iowrite" => "3", 
			"_stime" => "3", 
			"_time" => "3", 
			"_tolower" => "3", 
			"_toupper" => "3", 
			"_tzset" => "3", 
			"abort" => "3", 
			"abs" => "3", 
			"acos" => "3", 
			"asctime" => "3", 
			"asin" => "3", 
			"assert" => "3", 
			"assert.h" => "3", 
			"atan" => "3", 
			"atan2" => "3", 
			"atexit" => "3", 
			"atof" => "3", 
			"atoi" => "3", 
			"atol" => "3", 
			"bsearch" => "3", 
			"c166.h" => "3", 
			"calloc" => "3", 
			"ceil" => "3", 
			"clearerr" => "3", 
			"clock" => "3", 
			"cos" => "3", 
			"cosh" => "3", 
			"ctime" => "3", 
			"ctype.h" => "3", 
			"difftime" => "3", 
			"div" => "3", 
			"errno.h" => "3", 
			"exit" => "3", 
			"exp" => "3", 
			"fabs" => "3", 
			"fclose" => "3", 
			"feof" => "3", 
			"ferror" => "3", 
			"fflush" => "3", 
			"fgetc" => "3", 
			"fgets" => "3", 
			"float.h" => "3", 
			"floor" => "3", 
			"fmod" => "3", 
			"fopen" => "3", 
			"fprintf" => "3", 
			"fputc" => "3", 
			"fputs" => "3", 
			"fread" => "3", 
			"free" => "3", 
			"freopen" => "3", 
			"frexp" => "3", 
			"fscanf" => "3", 
			"fwrite" => "3", 
			"getc" => "3", 
			"getchar" => "3", 
			"gets" => "3", 
			"gmtime" => "3", 
			"isalnum" => "3", 
			"isalpha" => "3", 
			"isascii" => "3", 
			"iscntrl" => "3", 
			"isdigit" => "3", 
			"isgraph" => "3", 
			"islower" => "3", 
			"isprint" => "3", 
			"ispunct" => "3", 
			"isspace" => "3", 
			"isupper" => "3", 
			"isxdigit" => "3", 
			"labs" => "3", 
			"ldexp" => "3", 
			"ldiv" => "3", 
			"limits.h" => "3", 
			"locale.h" => "3", 
			"localtime" => "3", 
			"log" => "3", 
			"log10" => "3", 
			"longjmp" => "3", 
			"malloc" => "3", 
			"malloc.h" => "3", 
			"math.h" => "3", 
			"memchr" => "3", 
			"memcmp" => "3", 
			"memcpffb" => "3", 
			"memcpffw" => "3", 
			"memcpfhb" => "3", 
			"memcpfhw" => "3", 
			"memcpfnb" => "3", 
			"memcpfnw" => "3", 
			"memcphfb" => "3", 
			"memcphfw" => "3", 
			"memcphhb" => "3", 
			"memcphhw" => "3", 
			"memcphnb" => "3", 
			"memcphnw" => "3", 
			"memcpnnb" => "3", 
			"memcpnnw" => "3", 
			"memcpy" => "3", 
			"memmove" => "3", 
			"memset" => "3", 
			"mktime" => "3", 
			"modf" => "3", 
			"offsetof" => "3", 
			"pow" => "3", 
			"printf" => "3", 
			"putc" => "3", 
			"putchar" => "3", 
			"puts" => "3", 
			"qsort" => "3", 
			"rand" => "3", 
			"realloc" => "3", 
			"reg163.h" => "3", 
			"reg165.h" => "3", 
			"reg166.h" => "3", 
			"reg167.h" => "3", 
			"scanf" => "3", 
			"setbuf" => "3", 
			"setjmp" => "3", 
			"setjmp.h" => "3", 
			"setvbuf" => "3", 
			"signal.h" => "3", 
			"sin" => "3", 
			"sinh" => "3", 
			"sprintf" => "3", 
			"sqrt" => "3", 
			"srand" => "3", 
			"sscanf" => "3", 
			"stdarg.h" => "3", 
			"stddef.h" => "3", 
			"stdio.h" => "3", 
			"stdlib.h" => "3", 
			"strcat" => "3", 
			"strchr" => "3", 
			"strcmp" => "3", 
			"strcpy" => "3", 
			"strcspn" => "3", 
			"strftime" => "3", 
			"string.h" => "3", 
			"strlen" => "3", 
			"strncat" => "3", 
			"strncmp" => "3", 
			"strncpy" => "3", 
			"strpbrk" => "3", 
			"strrchr" => "3", 
			"strspn" => "3", 
			"strstr" => "3", 
			"strtod" => "3", 
			"strtok" => "3", 
			"strtol" => "3", 
			"strtoul" => "3", 
			"tan" => "3", 
			"tanh" => "3", 
			"time" => "3", 
			"time.h" => "3", 
			"toascii" => "3", 
			"tolower" => "3", 
			"toupper" => "3", 
			"ungetc" => "3", 
			"va_arg" => "3", 
			"va_end" => "3", 
			"va_start" => "3", 
			"vfprintf" => "3", 
			"vprintf" => "3", 
			"vsprintf" => "3", 
			"ASSERT_INC" => "4", 
			"C166_INC" => "4", 
			"CTYPE_INC" => "4", 
			"EOF" => "4", 
			"ERRNO_INC" => "4", 
			"FLOAT_INC" => "4", 
			"LIMITS_INC" => "4", 
			"LOCALE_INC" => "4", 
			"MATH_INC" => "4", 
			"NDEBUG" => "4", 
			"NULL" => "4", 
			"REG163_INC" => "4", 
			"REG163_NOADINT" => "4", 
			"REG163_NOCPU" => "4", 
			"REG163_NOEXTINT" => "4", 
			"REG163_NOPEC" => "4", 
			"REG163_NOPORT" => "4", 
			"REG163_NORS232" => "4", 
			"REG163_NOTIMER" => "4", 
			"REG165_INC" => "4", 
			"REG165_NOADINT" => "4", 
			"REG165_NOCPU" => "4", 
			"REG165_NOEXTINT" => "4", 
			"REG165_NOPEC" => "4", 
			"REG165_NOPORT" => "4", 
			"REG165_NORS232" => "4", 
			"REG165_NOTIMER" => "4", 
			"REG166_INC" => "4", 
			"REG166_NOADC" => "4", 
			"REG166_NOCAPCOM" => "4", 
			"REG166_NOCPU" => "4", 
			"REG166_NOPEC" => "4", 
			"REG166_NOPORT" => "4", 
			"REG166_NORS232" => "4", 
			"REG166_NOTIMER" => "4", 
			"REG167_INC" => "4", 
			"REG167_NOADC" => "4", 
			"REG167_NOADINT" => "4", 
			"REG167_NOCAPCOM" => "4", 
			"REG167_NOCPU" => "4", 
			"REG167_NOPEC" => "4", 
			"REG167_NOPORT" => "4", 
			"REG167_NOPWM" => "4", 
			"REG167_NORS232" => "4", 
			"REG167_NOTIMER" => "4", 
			"SETJMP_INC" => "4", 
			"SIGNAL_INC" => "4", 
			"STDARG_INC" => "4", 
			"STDDEF_INC" => "4", 
			"STDIO_INC" => "4", 
			"STDLIB_INC" => "4", 
			"STRING_INC" => "4", 
			"TIME_INC" => "4", 
			"!" => "5", 
			"$" => "5", 
			"&" => "5", 
			"(" => "5", 
			")" => "5", 
			"*" => "5", 
			"+" => "5", 
			"," => "5", 
			"-" => "5", 
			"." => "5", 
			"//" => "5", 
			"/" => "5", 
			":" => "5", 
			";" => "5", 
			"<" => "5", 
			"=" => "5", 
			">" => "5", 
			"[" => "5", 
			"]" => "5", 
			"{" => "5", 
			"|" => "5", 
			"}" => "5", 
			"~" => "5");

// Special extensions

// Each category can specify a PHP function that returns an altered
// version of the keyword.
        
        

$this->linkscripts    	= array(
			"1" => "donothing", 
			"2" => "donothing", 
			"3" => "donothing", 
			"4" => "donothing", 
			"5" => "donothing");
}


function donothing($keywordin)
{
	return $keywordin;
}

}?>
