<?php
$BEAUT_PATH = realpath(".")."/Services/COPage/syntax_highlight/php";
if (!isset ($BEAUT_PATH)) return;
require_once("$BEAUT_PATH/Beautifier/HFile.php");
  class HFile_sqr extends HFile{
   function HFile_sqr(){
     $this->HFile();	
/*************************************/
// Beautifier Highlighting Configuration File 
// SQR
/*************************************/
// Flags

$this->nocase            	= "1";
$this->notrim            	= "0";
$this->perl              	= "0";

// Colours

$this->colours        	= array("blue", "purple", "gray", "brown", "blue");
$this->quotecolour       	= "blue";
$this->blockcommentcolour	= "green";
$this->linecommentcolour 	= "green";

// Indent Strings

$this->indent            	= array();
$this->unindent          	= array();

// String characters and delimiters

$this->stringchars       	= array();
$this->delimiters        	= array("~", "!", "@", "%", "^", "&", "*", "(", ")", "+", "=", "|", "\\", "/", "{", "}", "[", "]", ":", ";", "\"", "'", "<", ">", " ", ",", "	", ".", "?");
$this->escchar           	= "";

// Comment settings

$this->linecommenton     	= array("!");
$this->blockcommenton    	= array("!");
$this->blockcommentoff   	= array("!");

// Keywords (keyword mapping to colour number)

$this->keywords          	= array(
			"begin-footing" => "1", 
			"begin-heading" => "1", 
			"begin-procedure" => "1", 
			"begin-program" => "1", 
			"begin-report" => "1", 
			"begin-setup" => "1", 
			"end-footing" => "1", 
			"end-heading" => "1", 
			"end-procedure" => "1", 
			"end-program" => "1", 
			"end-report" => "1", 
			"end-setup" => "1", 
			"Input" => "1", 
			"alter-printer" => "2", 
			"begin-document" => "2", 
			"begin-select" => "2", 
			"begin-sql" => "2", 
			"declare-chart" => "2", 
			"declare-image" => "2", 
			"declare-layout" => "2", 
			"declare-printer" => "2", 
			"declare-procedure" => "2", 
			"declare-report" => "2", 
			"end-declare" => "2", 
			"end-document" => "2", 
			"end-select" => "2", 
			"end-sql" => "2", 
			"load-lookup" => "2", 
			"#debug" => "3", 
			"#define" => "3", 
			"#else" => "3", 
			"#end-if" => "3", 
			"#endif" => "3", 
			"#if" => "3", 
			"#ifdef" => "3", 
			"#ifndef" => "3", 
			"#include" => "3", 
			"add" => "4", 
			"array-add" => "4", 
			"array-divide" => "4", 
			"array-multiply" => "4", 
			"array-subtract" => "4", 
			"ask" => "4", 
			"break" => "4", 
			"call" => "4", 
			"clear-array" => "4", 
			"close" => "4", 
			"columns" => "4", 
			"commit" => "4", 
			"concat" => "4", 
			"connect" => "4", 
			"create-array" => "4", 
			"date-time" => "4", 
			"display" => "4", 
			"divide" => "4", 
			"do" => "4", 
			"dollar-symbol" => "4", 
			"else" => "4", 
			"encode" => "4", 
			"end-evaluate" => "4", 
			"end-if" => "4", 
			"end-while" => "4", 
			"evaluate" => "4", 
			"execute" => "4", 
			"extract" => "4", 
			"find" => "4", 
			"font" => "4", 
			"get" => "4", 
			"goto" => "4", 
			"graphic" => "4", 
			"if" => "4", 
			"last-page" => "4", 
			"let" => "4", 
			"lookup" => "4", 
			"lowercase" => "4", 
			"money-symbol" => "4", 
			"move" => "4", 
			"multiply" => "4", 
			"new-page" => "4", 
			"new-report" => "4", 
			"next-column" => "4", 
			"next-listing" => "4", 
			"no-formfeed" => "4", 
			"open" => "4", 
			"page-number" => "4", 
			"page-size" => "4", 
			"position" => "4", 
			"print" => "4", 
			"print-bar-code" => "4", 
			"print-chart" => "4", 
			"print-direct" => "4", 
			"print-image" => "4", 
			"printer-deinit" => "4", 
			"printer-init" => "4", 
			"put" => "4", 
			"read" => "4", 
			"rollback" => "4", 
			"show" => "4", 
			"stop" => "4", 
			"string" => "4", 
			"subtract" => "4", 
			"unstring" => "4", 
			"uppercase" => "4", 
			"use" => "4", 
			"use-column" => "4", 
			"use-printer-type" => "4", 
			"use-procedure" => "4", 
			"use-report" => "4", 
			"while" => "4", 
			"write" => "4", 
			"#current-column" => "5", 
			"#current-line" => "5", 
			"#end-file" => "5", 
			"#page-count" => "5", 
			"#return-status" => "5", 
			"#sql-count" => "5", 
			"#sql-status" => "5", 
			"#sqr-pid" => "5", 
			"$sql-error" => "5", 
			"$sqr-database" => "5", 
			"$sqr-platform" => "5", 
			"$sqr-program" => "5", 
			"$sqr-report" => "5", 
			"$sqr-ver" => "5", 
			"$username" => "5", 
			"3d-effects" => "5", 
			"abs" => "5", 
			"acos" => "5", 
			"after-bold" => "5", 
			"after-page" => "5", 
			"after-report" => "5", 
			"and" => "5", 
			"array" => "5", 
			"as" => "5", 
			"ascii" => "5", 
			"asin" => "5", 
			"at-end" => "5", 
			"atan" => "5", 
			"beep" => "5", 
			"before-bold" => "5", 
			"before-page" => "5", 
			"before-report" => "5", 
			"blink" => "5", 
			"bold" => "5", 
			"bottom-margin" => "5", 
			"box" => "5", 
			"by" => "5", 
			"ceil" => "5", 
			"center" => "5", 
			"char" => "5", 
			"char-size" => "5", 
			"char-width" => "5", 
			"chars-inch" => "5", 
			"chart-size" => "5", 
			"cl" => "5", 
			"clear-line" => "5", 
			"clear-screen" => "5", 
			"cond" => "5", 
			"cos" => "5", 
			"cosh" => "5", 
			"cs" => "5", 
			"date" => "5", 
			"deg" => "5", 
			"delete" => "5", 
			"distinct" => "5", 
			"e10" => "5", 
			"edit" => "5", 
			"erase-page" => "5", 
			"exists" => "5", 
			"exp" => "5", 
			"extent" => "5", 
			"field" => "5", 
			"fill" => "5", 
			"fixed" => "5", 
			"fixed_nolf" => "5", 
			"floor" => "5", 
			"font-type" => "5", 
			"for-append" => "5", 
			"for-reading" => "5", 
			"for-reports" => "5", 
			"for-writing" => "5", 
			"formfeed" => "5", 
			"from" => "5", 
			"getenv" => "5", 
			"goto-top" => "5", 
			"group" => "5", 
			"having" => "5", 
			"horz-line" => "5", 
			"image-size" => "5", 
			"in" => "5", 
			"insert" => "5", 
			"instr" => "5", 
			"integer" => "5", 
			"into" => "5", 
			"isblank" => "5", 
			"isnull" => "5", 
			"is" => "5", 
			"key" => "5", 
			"layout" => "5", 
			"left-margin" => "5", 
			"legend" => "5", 
			"legend-placement" => "5", 
			"legend-presentation" => "5", 
			"legend-title" => "5", 
			"length" => "5", 
			"line-height" => "5", 
			"line-size" => "5", 
			"line-width" => "5", 
			"lines-inch" => "5", 
			"local" => "5", 
			"log10" => "5", 
			"loops" => "5", 
			"lower" => "5", 
			"lpad" => "5", 
			"ltrim" => "5", 
			"max-columns" => "5", 
			"max-lines" => "5", 
			"maxlen" => "5", 
			"mod" => "5", 
			"name" => "5", 
			"need" => "5", 
			"newline" => "5", 
			"newpage" => "5", 
			"no-advance" => "5", 
			"noprompt" => "5", 
			"normal" => "5", 
			"not" => "5", 
			"number" => "5", 
			"nvl" => "5", 
			"null" => "5", 
			"on-error" => "5", 
			"or" => "5", 
			"order" => "5", 
			"orientation" => "5", 
			"page-depth" => "5", 
			"paper-size" => "5", 
			"pie-segment-explode" => "5", 
			"pie-segment-percent-display" => "5", 
			"pie-segment-quantity-display" => "5", 
			"pitch" => "5", 
			"point-markers" => "5", 
			"point-size" => "5", 
			"power" => "5", 
			"printer-type" => "5", 
			"quiet" => "5", 
			"rad" => "5", 
			"range" => "5", 
			"record" => "5", 
			"rename" => "5", 
			"return_value" => "5", 
			"reverse" => "5", 
			"right-margin" => "5", 
			"round" => "5", 
			"rows" => "5", 
			"rpad" => "5", 
			"rtrim" => "5", 
			"select" => "5", 
			"sign" => "5", 
			"sin" => "5", 
			"sinh" => "5", 
			"size" => "5", 
			"skip" => "5", 
			"skiplines" => "5", 
			"sort" => "5", 
			"source" => "5", 
			"sqr-database" => "5", 
			"sqr-platform" => "5", 
			"sqrt" => "5", 
			"startup-file" => "5", 
			"status" => "5", 
			"sub-title" => "5", 
			"substr" => "5", 
			"symbol-set" => "5", 
			"table" => "5", 
			"tan" => "5", 
			"tanh" => "5", 
			"times" => "5", 
			"title" => "5", 
			"to" => "5", 
			"to_char" => "5", 
			"to_date" => "5", 
			"to_number" => "5", 
			"top-margin" => "5", 
			"translate" => "5", 
			"trunc" => "5", 
			"type" => "5", 
			"underline" => "5", 
			"update" => "5", 
			"upper" => "5", 
			"using" => "5", 
			"vary" => "5", 
			"vert-line" => "5", 
			"warn" => "5", 
			"when" => "5", 
			"when-other" => "5", 
			"where" => "5", 
			"with" => "5", 
			"x-axis-grid" => "5", 
			"x-axis-label" => "5", 
			"x-axis-major-increment" => "5", 
			"x-axis-major-tick-marks" => "5", 
			"x-axis-max-value" => "5", 
			"x-axis-min-value" => "5", 
			"x-axis-minor-increment" => "5", 
			"x-axis-minor-tick-marks" => "5", 
			"x-axis-scale" => "5", 
			"x-axis-tick-mark-placement" => "5", 
			"xor" => "5", 
			"y-axis-grid" => "5", 
			"y-axis-label" => "5", 
			"y-axis-major-increment" => "5", 
			"y-axis-major-tick-marks" => "5", 
			"y-axis-max-value" => "5", 
			"y-axis-min-value" => "5", 
			"y-axis-minor-increment" => "5", 
			"y-axis-minor-tick-marks" => "5", 
			"y-axis-scale" => "5", 
			"y-axis-tick-mark-placement" => "5");

// Special extensions

// Each category can specify a PHP function that returns an altered
// version of the keyword.
        
        

$this->linkscripts    	= array(
			"1" => "donothing", 
			"2" => "donothing", 
			"3" => "donothing", 
			"4" => "donothing", 
			"5" => "donothing");
}


function donothing($keywordin)
{
	return $keywordin;
}

}?>
