<?php
$BEAUT_PATH = realpath(".")."/Services/COPage/syntax_highlight/php";
if (!isset ($BEAUT_PATH)) return;
require_once("$BEAUT_PATH/Beautifier/HFile.php");
  class HFile_cfm45 extends HFile{
   function HFile_cfm45(){
     $this->HFile();	
/*************************************/
// Beautifier Highlighting Configuration File 
// 
/*************************************/
// Flags

$this->nocase            	= "0";
$this->notrim            	= "0";
$this->perl              	= "0";

// Colours

$this->colours        	= array("");
$this->quotecolour       	= "blue";
$this->blockcommentcolour	= "green";
$this->linecommentcolour 	= "green";

// Indent Strings

$this->indent            	= array();
$this->unindent          	= array();

// String characters and delimiters

$this->stringchars       	= array();
$this->delimiters        	= array();
$this->escchar           	= "";

// Comment settings

$this->linecommenton     	= array("");
$this->blockcommenton    	= array("");
$this->blockcommentoff   	= array("");

// Keywords (keyword mapping to colour number)

$this->keywords          	= array(
			"[Tag" => "", 
			"Group" => "", 
			"-" => "", 
			"COLD" => "", 
			"FUSION" => "", 
			"Tags]" => "", 
			"0=\"Abort" => "", 
			"page" => "", 
			"processing" => "", 
			":UEDS:<CFABORT>\"" => "", 
			"1=\"Embed" => "", 
			"Java" => "", 
			"applet" => "", 
			":UEDS:<CFAPPLET>\"" => "", 
			"2=\"Application" => "", 
			"name" => "", 
			":UEDS:<CFAPPLICATION>\"" => "", 
			"3=\"Associates" => "", 
			"sub" => "", 
			"tag" => "", 
			"to" => "", 
			"base" => "", 
			":UEDS:<CFASSOCIATE>\"" => "", 
			"4=\"Authenticates" => "", 
			"a" => "", 
			"user" => "", 
			"for" => "", 
			"security" => "", 
			":UEDS:<CFAUTHENTICATE>\"" => "", 
			"5=\"Break" => "", 
			"CFML" => "", 
			"loop" => "", 
			":UEDS:<CFBREAK>\"" => "", 
			"6=\"Caches" => "", 
			"ColdFusion" => "", 
			"pages" => "", 
			":UEDS:<CFCACHE>\"" => "", 
			"7=\"Utilized" => "", 
			"by" => "", 
			"CFSWITCH" => "", 
			":UEDS:<CFCASE>\"" => "", 
			"8=\"Utilized" => "", 
			"CFTRY" => "", 
			":UEDS:<CFCATCH>\"" => "", 
			"9=\"Table" => "", 
			"Column" => "", 
			"Header" => "", 
			":UEDS:<CFCOL>\"" => "", 
			"10=\"Create" => "", 
			"and" => "", 
			"administer" => "", 
			"Verity" => "", 
			"collections" => "", 
			":UEDS:<CFCOLLECTION>\"" => "", 
			"11=\"File" => "", 
			"content" => "", 
			"type" => "", 
			":UEDS:<CFCONTENT>\"" => "", 
			"12=\"Define/set" => "", 
			"cookie" => "", 
			"variables" => "", 
			":UEDS:<CFCOOKIE>\"" => "", 
			"13=\"Directory" => "", 
			"handling" => "", 
			"task" => "", 
			":UEDS:<CFDIRECTORY>\"" => "", 
			"14=\"Else" => "", 
			"statement" => "", 
			":UEDS:<CFELSE>\"" => "", 
			"15=\"Elseif" => "", 
			":UEDS:<CFELSEIF>\"" => "", 
			"16=\"Display" => "", 
			"custom" => "", 
			"HTML" => "", 
			"error" => "", 
			":UEDS:<CFERROR>\"" => "", 
			"17=\"Execute" => "", 
			"developer-specified" => "", 
			"process" => "", 
			"on" => "", 
			"server" => "", 
			":UEDS:<CFEXECUTE>" => "", 
			"18=\"Abort" => "", 
			"current" => "", 
			":UEDS:<CFEXIT>\"" => "", 
			"19=\"File" => "", 
			":UEDS:<CFFILE>\"" => "", 
			"20=\"Build/validate" => "", 
			"form" => "", 
			"input" => "", 
			":UEDS:<CFFORM>" => "", 
			"..." => "", 
			"</CFFORM>\"" => "", 
			"21=\"FTP" => "", 
			"file" => "", 
			"operations" => "", 
			":UEDS:<CFFTP>\"" => "", 
			"22=\"Create" => "", 
			"tabular" => "", 
			"data" => "", 
			"grid" => "", 
			"control" => "", 
			":UEDS:<CFGRID>\"" => "", 
			"23=\"Define" => "", 
			"CFGRID" => "", 
			"columns" => "", 
			":UEDS:<CFGRIDCOLUMN>\"" => "", 
			"24=\"Define" => "", 
			"rows" => "", 
			":UEDS:<CFRGRIDROW>\"" => "", 
			"25=\"Update" => "", 
			"ODBC" => "", 
			"source" => "", 
			"from" => "", 
			":UEDS:<CFGRIDUPDATE>\"" => "", 
			"26=\"Generate" => "", 
			"HTTP" => "", 
			"Headers" => "", 
			":UEDS:<CFHEADER>\"" => "", 
			"27=\"Writes" => "", 
			"text" => "", 
			"Head" => "", 
			":UEDS:<CFHTMLHEAD>\"" => "", 
			"28=\"Get/post" => "", 
			"tasks" => "", 
			":UEDS:<CFHTTP>\"" => "", 
			"29=\"Specfiy" => "", 
			"CFHTTP" => "", 
			"Post" => "", 
			"parameters" => "", 
			":UEDS:<CFHTTPPARAM>\"" => "", 
			"30=\"If" => "", 
			":UEDS:<CFIF>" => "", 
			"</CFIF>\"" => "", 
			"31=\"Impersonate" => "", 
			"defined" => "", 
			"in" => "", 
			"Advanced" => "", 
			"Security" => "", 
			":UEDS:<CFIMPERSONATE>\"" => "", 
			"32=\"Embedded" => "", 
			"reference" => "", 
			":UEDS:<CFINCLUDE>\"" => "", 
			"33=\"Create" => "", 
			"search" => "", 
			"index" => "", 
			":UEDS:<CFINDEX>\"" => "", 
			"34=\"Create" => "", 
			"elements" => "", 
			":UEDS:<CFINPUT>\"" => "", 
			"35=\"Insert" => "", 
			"record" => "", 
			":UEDS:<CFINSERT>\"" => "", 
			"36=\"LDAP" => "", 
			"directory" => "", 
			"access" => "", 
			":UEDS:<CFLDAP>\"" => "", 
			"37=\"Open" => "", 
			"CF" => "", 
			"Page" => "", 
			"or" => "", 
			":UEDS:<CFLOCATION>\"" => "", 
			"38=\"Restrict" => "", 
			"blocks" => "", 
			"of" => "", 
			"code" => "", 
			"single" => "", 
			"threaded" => "", 
			":UEDS:<CFLOCK>" => "", 
			"</CFLOCK>\"" => "", 
			"39=\"Repeat" => "", 
			"instructions" => "", 
			":UEDS:<CFLOOP>" => "", 
			"</CFLOOP>\"" => "", 
			"40=\"Assemble/post" => "", 
			"email" => "", 
			":UEDS:<CFMAIL>\"" => "", 
			"41=\"Attach" => "", 
			"add" => "", 
			"header" => "", 
			"an" => "", 
			"message" => "", 
			":UEDS:<CFMAILPARAM>\"" => "", 
			"42=\"Invoke" => "", 
			":UEDS:<CFMODULE>\"" => "", 
			"43=\"Create/use" => "", 
			"COM" => "", 
			"object" => "", 
			":UEDS:<CFOBJECT>\"" => "", 
			"44=\"Display" => "", 
			"DB" => "", 
			"query" => "", 
			"output" => "", 
			":UEDS:<CFOUTPUT>\"" => "", 
			"45=\"Define" => "", 
			"parameter/default" => "", 
			"value" => "", 
			":UEDS:<CFPARAM>\"" => "", 
			"46=\"Retrieve" => "", 
			"msg" => "", 
			"POP" => "", 
			":UEDS:<CFPOP>\"" => "", 
			"47=\"Suppresses" => "", 
			"extraneous" => "", 
			"white" => "", 
			"space" => "", 
			"other" => "", 
			":UEDS:<CFPROCESSINGDIRECTIVE>\"" => "", 
			"48=\"Parameters" => "", 
			"stored" => "", 
			"procedure" => "", 
			":UEDS:<CFPROCPARAM>\"" => "", 
			"49=\"Display" => "", 
			"results" => "", 
			":UEDS:<CFPROCRESULT>\"" => "", 
			"50=\"Pass" => "", 
			"SQL" => "", 
			"database" => "", 
			":UEDS:<CFQUERY>\"" => "", 
			"51=\"R/W/D" => "", 
			"keys" => "", 
			"values" => "", 
			"system" => "", 
			"registry" => "", 
			":UEDS:<CFQUERYPARAM>\"" => "", 
			"52=\"Directly" => "", 
			"manipulate" => "", 
			":UEDS:<CFREGISTRY>\"" => "", 
			"53=\"Embed" => "", 
			"Crystal" => "", 
			"Reports" => "", 
			"report" => "", 
			":UEDS:<CFREPORT>\"" => "", 
			"54=\"Rethrows" => "", 
			"the" => "", 
			"currently" => "", 
			"active" => "", 
			"exception" => "", 
			":UEDS:<CFRETHROW>\"" => "", 
			"55=\"Mark" => "", 
			"block" => "", 
			"script" => "", 
			":UEDS:<CFSCRIPT>" => "", 
			"</SFSCRIPT>\"" => "", 
			"56=\"Execute" => "", 
			"Verify" => "", 
			"indexed" => "", 
			":UEDS:<CFSEARCH>\"" => "", 
			"57=\"Create" => "", 
			"drop-down" => "", 
			"list" => "", 
			"CFFORM" => "", 
			":UEDS:<CFSELECT>\"" => "", 
			"58=\"Execute" => "", 
			"servlet" => "", 
			"JRun" => "", 
			"engine" => "", 
			":UEDS:<CFSERVLET>\"" => "", 
			"59=\"Passes" => "", 
			":UEDS:<CFSERVLETPARAM>\"" => "", 
			"60=\"Define" => "", 
			"variable" => "", 
			":UEDS:<CFSET>\"" => "", 
			"61=\"Define/control" => "", 
			"settings" => "", 
			":UEDS:<CFSETTING>\"" => "", 
			"62=\"Suppress" => "", 
			"produced" => "", 
			"within" => "", 
			"tags" => "", 
			"scope" => "", 
			":UEDS:<CFSILENT>\"" => "", 
			"63=\"Create" => "", 
			"slider" => "", 
			"element" => "", 
			":UEDS:<CFSLIDER>\"" => "", 
			"64=\"Call" => "", 
			":UEDS:<CFSTOREDPROC>\"" => "", 
			"65=\"Evalute" => "", 
			"passed" => "", 
			"expression" => "", 
			":UEDS:<CFSWITCH>\"" => "", 
			"66=\"Build" => "", 
			"table" => "", 
			":UEDS:<CFTABLE>\"" => "", 
			"67=\"Create" => "", 
			"single-line" => "", 
			"box" => "", 
			":UEDS:<CFTEXTINPUT>\"" => "", 
			"68=\"Raise" => "", 
			":UEDS:<CFTHROW>\"" => "", 
			"69=\"Groups" => "", 
			"CFQUERY" => "", 
			"into" => "", 
			"transaction" => "", 
			":UEDS:<CFTRANSACTION>\"" => "", 
			"70=\"Create" => "", 
			"tree" => "", 
			":UEDS:<CFTREE>\"" => "", 
			"71=\"Populate" => "", 
			":UEDS:<CFTREEITEM>\"" => "", 
			"72=\"Catch" => "", 
			"exceptions" => "", 
			":UEDS:<CFTRY>\"" => "", 
			"73=\"Update" => "", 
			"records" => "", 
			":UEDS:<CFUPDATE>\"" => "", 
			"74=\"Serialize/De-serialize" => "", 
			"XML-based" => "", 
			"WDDX" => "", 
			"format" => "", 
			":UEDS:<CFWDDX>\"" => "", 
			"75=\"" => "", 
			"[Group" => "", 
			"List]" => "", 
			"0=COLD" => "", 
			"Tags" => "", 
			"1=" => "");

// Special extensions

// Each category can specify a PHP function that returns an altered
// version of the keyword.
        
        

$this->linkscripts    	= array(
			"" => "donothing");
}


function donothing($keywordin)
{
	return $keywordin;
}

}?>
