<?php
$BEAUT_PATH = realpath(".")."/Services/COPage/syntax_highlight/php";
if (!isset ($BEAUT_PATH)) return;
require_once("$BEAUT_PATH/Beautifier/HFile.php");
  class HFile_dataflex extends HFile{
   function HFile_dataflex(){
     $this->HFile();	
/*************************************/
// Beautifier Highlighting Configuration File 
// DataFlex
/*************************************/
// Flags

$this->nocase            	= "1";
$this->notrim            	= "0";
$this->perl              	= "0";

// Colours

$this->colours        	= array("blue", "purple", "gray", "brown", "blue", "purple", "gray");
$this->quotecolour       	= "blue";
$this->blockcommentcolour	= "green";
$this->linecommentcolour 	= "green";

// Indent Strings

$this->indent            	= array("Then", "Begin", "Lock", "repeat", "while", "enumeration_list", "class", "object");
$this->unindent          	= array("End", "Next", "End If", "End Select", "Unlock", "loop", "end_enumeration_list", "end_class", "end_object");

// String characters and delimiters

$this->stringchars       	= array();
$this->delimiters        	= array();
$this->escchar           	= "";

// Comment settings

$this->linecommenton     	= array("//");
$this->blockcommenton    	= array("//*");
$this->blockcommentoff   	= array("*//");

// Keywords (keyword mapping to colour number)

$this->keywords          	= array(
			"#endheader" => "1", 
			"#header" => "1", 
			"#include" => "1", 
			"#replace" => "1", 
			"abort" => "2", 
			"abort_transaction" => "2", 
			"accept" => "2", 
			"activate_view" => "2", 
			"add" => "2", 
			"append" => "2", 
			"append_output" => "2", 
			"ascii" => "2", 
			"attach" => "2", 
			"autopage" => "2", 
			"backfield" => "2", 
			"begin" => "2", 
			"begin_contraints" => "2", 
			"begin_transaction" => "2", 
			"blankform" => "2", 
			"body" => "2", 
			"break" => "2", 
			"broadcast" => "2", 
			"broadcast_focus" => "2", 
			"calc" => "2", 
			"calculate" => "2", 
			"call" => "2", 
			"call_driver" => "2", 
			"cd_end_object" => "2", 
			"cd_popup_object" => "2", 
			"chain" => "2", 
			"character" => "2", 
			"class" => "2", 
			"clear" => "2", 
			"clear_option" => "2", 
			"clearform" => "2", 
			"clearscreen" => "2", 
			"clearwarning" => "2", 
			"clearxy" => "2", 
			"close" => "2", 
			"close_input" => "2", 
			"close_output" => "2", 
			"cmdline" => "2", 
			"constrain" => "2", 
			"contrained_clear" => "2", 
			"constrained_find" => "2", 
			"constraint_set" => "2", 
			"constraint_validate" => "2", 
			"copy_db" => "2", 
			"copy_records" => "2", 
			"copyfile" => "2", 
			"create_field" => "2", 
			"create_index" => "2", 
			"date" => "2", 
			"debug" => "2", 
			"declare_datafile" => "2", 
			"decrement" => "2", 
			"deferred_view" => "2", 
			"define" => "2", 
			"delegate" => "2", 
			"delete" => "2", 
			"delete_db" => "2", 
			"delete_field" => "2", 
			"delete_index" => "2", 
			"dependent_item" => "2", 
			"despool" => "2", 
			"direct_input" => "2", 
			"direct_output" => "2", 
			"directory" => "2", 
			"diskfree" => "2", 
			"display" => "2", 
			"else" => "2", 
			"end" => "2", 
			"end_class" => "2", 
			"end_constraints" => "2", 
			"end_function" => "2", 
			"end_enumeration_list" => "2", 
			"end_item_group" => "2", 
			"end_item_list" => "2", 
			"end_object" => "2", 
			"end_procedure" => "2", 
			"end_transaction" => "2", 
			"end_type" => "2", 
			"endgroup" => "2", 
			"entagain" => "2", 
			"entdisplay" => "2", 
			"enter" => "2", 
			"enterend" => "2", 
			"entergroup" => "2", 
			"entermode" => "2", 
			"entry" => "2", 
			"entry_item" => "2", 
			"entry_name_item" => "2", 
			"enumeration_list" => "2", 
			"erase_file" => "2", 
			"error" => "2", 
			"error_report" => "2", 
			"export_files" => "2", 
			"field" => "2", 
			"field_def" => "2", 
			"field_map" => "2", 
			"file_mode" => "2", 
			"file_size" => "2", 
			"filelist" => "2", 
			"fill_field" => "2", 
			"find" => "2", 
			"for" => "2", 
			"format" => "2", 
			"formfeed" => "2", 
			"forward" => "2", 
			"forward_begin_construct" => "2", 
			"forward_end_construct" => "2", 
			"from" => "2", 
			"function" => "2", 
			"function_return" => "2", 
			"get" => "2", 
			"get_argument_size" => "2", 
			"get_attribute" => "2", 
			"get_channel_position" => "2", 
			"get_channel_size" => "2", 
			"get_current_colors" => "2", 
			"get_current_directory" => "2", 
			"get_current_input_channel" => "2", 
			"get_current_lockcount" => "2", 
			"get_current_output_channel" => "2", 
			"get_current_user_count" => "2", 
			"get_date_format" => "2", 
			"get_environment" => "2", 
			"get_field_value" => "2", 
			"get_filelist" => "2", 
			"get_licensed_max_users" => "2", 
			"get_number_format" => "2", 
			"get_resource_name" => "2", 
			"get_resource_type" => "2", 
			"get_transaction_retry" => "2", 
			"get_video_mode" => "2", 
			"gosub" => "2", 
			"goto" => "2", 
			"gotoxy" => "2", 
			"group" => "2", 
			"header" => "2", 
			"help" => "2", 
			"if" => "2", 
			"ifchange" => "2", 
			"import_class_protocol" => "2", 
			"inactivate" => "2", 
			"include_resource" => "2", 
			"increment" => "2", 
			"ind" => "2", 
			"index_def" => "2", 
			"indicate" => "2", 
			"inherit_screen" => "2", 
			"inkey" => "2", 
			"inkey$" => "2", 
			"input" => "2", 
			"insert" => "2", 
			"is_file_included" => "2", 
			"item_group" => "2", 
			"item_list" => "2", 
			"keycheck" => "2", 
			"keyproc" => "2", 
			"left" => "2", 
			"length" => "2", 
			"load_def" => "2", 
			"local_driver" => "2", 
			"local" => "2", 
			"lock" => "2", 
			"login" => "2", 
			"logout" => "2", 
			"loop" => "2", 
			"make_file" => "2", 
			"memory" => "2", 
			"mid" => "2", 
			"move" => "2", 
			"movedate" => "2", 
			"moveint" => "2", 
			"movenum" => "2", 
			"movereal" => "2", 
			"movestr" => "2", 
			"move_sub_page" => "2", 
			"name" => "2", 
			"name_item" => "2", 
			"name_items" => "2", 
			"name_object" => "2", 
			"next" => "2", 
			"not" => "2", 
			"object" => "2", 
			"on" => "2", 
			"on_item" => "2", 
			"on_key" => "2", 
			"on_name_item" => "2", 
			"open" => "2", 
			"output" => "2", 
			"output_aux_file" => "2", 
			"output_wrap" => "2", 
			"pad" => "2", 
			"page" => "2", 
			"pagecheck" => "2", 
			"pathname" => "2", 
			"pos" => "2", 
			"print" => "2", 
			"print_wrap" => "2", 
			"procedure" => "2", 
			"procedure_return" => "2", 
			"property" => "2", 
			"read" => "2", 
			"read_block" => "2", 
			"read_dfini" => "2", 
			"read_hex" => "2", 
			"readln" => "2", 
			"register_function" => "2", 
			"register_object" => "2", 
			"register_procedure" => "2", 
			"register_resource" => "2", 
			"registration" => "2", 
			"relate" => "2", 
			"renamefile" => "2", 
			"repeat" => "2", 
			"repeat_item" => "2", 
			"replace" => "2", 
			"report" => "2", 
			"reportend" => "2", 
			"reread" => "2", 
			"return" => "2", 
			"right" => "2", 
			"runprogram" => "2", 
			"save" => "2", 
			"saverecord" => "2", 
			"screenmode" => "2", 
			"screen_optimize" => "2", 
			"section" => "2", 
			"send" => "2", 
			"set" => "2", 
			"set_argument_size" => "2", 
			"set_attribute" => "2", 
			"set_channel_position" => "2", 
			"set_dfpath" => "2", 
			"set_field_value" => "2", 
			"set_filelist" => "2", 
			"set_option" => "2", 
			"set_relate" => "2", 
			"set_resource_library" => "2", 
			"set_transaction_retry" => "2", 
			"set_video_mode" => "2", 
			"setchange" => "2", 
			"show" => "2", 
			"showln" => "2", 
			"showxy" => "2", 
			"sleep" => "2", 
			"sort" => "2", 
			"start_ui" => "2", 
			"stop" => "2", 
			"structure_abort" => "2", 
			"structure_copy" => "2", 
			"structure_end" => "2", 
			"structure_start" => "2", 
			"sub" => "2", 
			"sub_page" => "2", 
			"subtotal" => "2", 
			"sysconf" => "2", 
			"sysdate" => "2", 
			"sysdate4" => "2", 
			"system" => "2", 
			"to" => "2", 
			"trim" => "2", 
			"type" => "2", 
			"ui_accept" => "2", 
			"unload_driver" => "2", 
			"unlock" => "2", 
			"until" => "2", 
			"uppercase" => "2", 
			"use" => "2", 
			"vconstrain" => "2", 
			"vfind" => "2", 
			"while" => "2", 
			"write" => "2", 
			"write_hex" => "2", 
			"writeln" => "2", 
			"zerofile" => "2", 
			"abs" => "3", 
			"acos" => "3", 
			"asin" => "3", 
			"atan" => "3", 
			"callback" => "3", 
			"center" => "3", 
			"cos" => "3", 
			"eval" => "3", 
			"exp" => "3", 
			"hi" => "3", 
			"log" => "3", 
			"low" => "3", 
			"lowercase" => "3", 
			"ltrim" => "3", 
			"mod" => "3", 
			"overstrike" => "3", 
			"random" => "3", 
			"remove" => "3", 
			"replaces" => "3", 
			"round" => "3", 
			"rtrim" => "3", 
			"sin" => "3", 
			"sqrt" => "3", 
			"status" => "3", 
			"tan" => "3", 
			"an" => "4", 
			"and" => "4", 
			"as" => "4", 
			"contains" => "4", 
			"eq" => "4", 
			"ge" => "4", 
			"gt" => "4", 
			"iand" => "4", 
			"in" => "4", 
			"ior" => "4", 
			"is" => "4", 
			"le" => "4", 
			"lt" => "4", 
			"match" => "4", 
			"matches" => "4", 
			"max" => "4", 
			"min" => "4", 
			"ne" => "4", 
			"or" => "4", 
			"autoback" => "5", 
			"autoclear" => "5", 
			"autofind" => "5", 
			"autofind_ge" => "5", 
			"autoreturn" => "5", 
			"capslock" => "5", 
			"channel" => "5", 
			"check" => "5", 
			"displayonly" => "5", 
			"fill" => "5", 
			"findreq" => "5", 
			"float$" => "5", 
			"forceput" => "5", 
			"modal_insert" => "5", 
			"no_calc" => "5", 
			"noenter" => "5", 
			"noput" => "5", 
			"points" => "5", 
			"range" => "5", 
			"required" => "5", 
			"resident" => "5", 
			"resource" => "5", 
			"retain" => "5", 
			"retainall" => "5", 
			"signrt" => "5", 
			"skipfound" => "5", 
			"suppress" => "5", 
			"thousands" => "5", 
			"wait" => "5", 
			"zero_suppress" => "5", 
			"constrain_found_count" => "6", 
			"constrain_tests_count" => "6", 
			"current_image" => "6", 
			"current_window" => "6", 
			"indicator" => "7", 
			"integer" => "7", 
			"number" => "7", 
			"real" => "7", 
			"string" => "7");

// Special extensions

// Each category can specify a PHP function that returns an altered
// version of the keyword.
        
        

$this->linkscripts    	= array(
			"1" => "donothing", 
			"2" => "donothing", 
			"3" => "donothing", 
			"4" => "donothing", 
			"5" => "donothing", 
			"6" => "donothing", 
			"7" => "donothing");
}


function donothing($keywordin)
{
	return $keywordin;
}

}?>
