<?php
$BEAUT_PATH = realpath(".")."/Services/COPage/syntax_highlight/php";
if (!isset ($BEAUT_PATH)) return;
require_once("$BEAUT_PATH/Beautifier/HFile.php");
  class HFile_providex extends HFile{
   function HFile_providex(){
     $this->HFile();	
/*************************************/
// Beautifier Highlighting Configuration File 
// Providex
/*************************************/
// Flags

$this->nocase            	= "1";
$this->notrim            	= "0";
$this->perl              	= "0";

// Colours

$this->colours        	= array("blue", "purple", "gray", "brown");
$this->quotecolour       	= "blue";
$this->blockcommentcolour	= "green";
$this->linecommentcolour 	= "green";

// Indent Strings

$this->indent            	= array();
$this->unindent          	= array();

// String characters and delimiters

$this->stringchars       	= array();
$this->delimiters        	= array("@", "^", "&", "*", "(", ")", "-", "+", "=", "|", "\\", "/", "{", "}", "[", "]", ";", "\"", "<", ">", "	", " ", ",", "?", " ", ":");
$this->escchar           	= "";

// Comment settings

$this->linecommenton     	= array("!");
$this->blockcommenton    	= array("");
$this->blockcommentoff   	= array("");

// Keywords (keyword mapping to colour number)

$this->keywords          	= array(
			"ACCEPT" => "1", 
			"ADDR" => "1", 
			"ALL" => "1", 
			"AND" => "1", 
			"AUTO" => "1", 
			"AUTO_LOCK" => "1", 
			"BEGIN" => "1", 
			"BREAK" => "1", 
			"BYE" => "1", 
			"BUTTON" => "1", 
			"CALL" => "1", 
			"CASE" => "1", 
			"CHECK_BOX" => "1", 
			"CLEAR" => "1", 
			"CLIP_BOARD" => "1", 
			"CLOSE" => "1", 
			"CONTINUE" => "1", 
			"CONTROL" => "1", 
			"CUSTOM_VBX" => "1", 
			"CWDIR" => "1", 
			"DATA" => "1", 
			"DAY_FORMAT" => "1", 
			"DEF" => "1", 
			"DEFAULT" => "1", 
			"DEFCTL" => "1", 
			"DEFPRT" => "1", 
			"DEFTTY" => "1", 
			"DELETE" => "1", 
			"DICTIONARY" => "1", 
			"DIM" => "2", 
			"DIRECT" => "1", 
			"DIRECTORY" => "1", 
			"DISABLE" => "1", 
			"DROP" => "1", 
			"DROP_BOX" => "1", 
			"DUMP" => "1", 
			"EDIT" => "1", 
			"ELSE" => "1", 
			"ENABLE" => "1", 
			"END" => "3", 
			"END_IF" => "1", 
			"ENDTRACE" => "1", 
			"ENTER" => "1", 
			"ERASE" => "1", 
			"ERROR_HANDLER" => "1", 
			"ESCAPE" => "1", 
			"EXCEPT" => "1", 
			"EXECUTE" => "1", 
			"EXIT" => "1", 
			"EXITTO" => "1", 
			"EXTRACT" => "1", 
			"FI" => "1", 
			"FILE" => "1", 
			"FIND" => "1", 
			"FLOATING" => "1", 
			"FLOATINGPOINT" => "1", 
			"FN" => "1", 
			"FOR" => "1", 
			"FROM" => "1", 
			"GET_FILE_BOX" => "1", 
			"GOTO" => "1", 
			"GOSUB" => "1", 
			"H_SCROLLBAR" => "1", 
			"HIDE" => "1", 
			"IF" => "1", 
			"INDEXED" => "1", 
			"INPUT" => "1", 
			"INVOKE" => "1", 
			"IOLIST" => "1", 
			"KEYED" => "1", 
			"LET" => "1", 
			"LINE_SWITCH" => "1", 
			"LIST" => "1", 
			"LIST_BOX" => "1", 
			"LOAD" => "1", 
			"LOCAL" => "1", 
			"LOCK" => "1", 
			"LONG_FORM" => "1", 
			"MENU_BAR" => "1", 
			"MERGE" => "1", 
			"MESSAGE_LIB" => "1", 
			"MNEMONIC" => "1", 
			"MSGBOX" => "1", 
			"MULTI_LINE" => "1", 
			"MULTI_MEDIA" => "1", 
			"NEXT" => "1", 
			"OBTAIN" => "1", 
			"OFF" => "1", 
			"ON" => "1", 
			"OPEN" => "1", 
			"OR" => "1", 
			"PASSWORD" => "1", 
			"PERFORM" => "1", 
			"POINT" => "1", 
			"PRECISION" => "1", 
			"PREFIX" => "1", 
			"PREINPUT" => "1", 
			"PRINT" => "1", 
			"PROGRAM" => "1", 
			"PROCEED" => "1", 
			"PROCESS" => "1", 
			"PROPERTIES" => "1", 
			"PURGE" => "1", 
			"QUIT" => "1", 
			"RADIO_BUTTON" => "1", 
			"RANDOM" => "1", 
			"RANDOMIZE" => "1", 
			"READ" => "1", 
			"RECORD" => "1", 
			"REFILE" => "1", 
			"RELEASE" => "1", 
			"REM" => "1", 
			"REMOVE" => "1", 
			"RENAME" => "1", 
			"RENUMBER" => "1", 
			"REPEAT" => "1", 
			"RESET" => "1", 
			"RESTORE" => "1", 
			"RETRY" => "1", 
			"RETURN" => "1", 
			"ROUND" => "1", 
			"RUN" => "1", 
			"SAME" => "1", 
			"SAVE" => "1", 
			"SECURITY_MASK" => "1", 
			"SELECT" => "1", 
			"SERIAL" => "1", 
			"SERVER" => "1", 
			"SETMOUSE" => "1", 
			"SETCTL" => "1", 
			"SETDAY" => "1", 
			"SETDEV" => "1", 
			"SETDRIVE" => "1", 
			"SETERR" => "1", 
			"SETESC" => "1", 
			"SETFID" => "1", 
			"SETTIME" => "1", 
			"SETTRACE" => "1", 
			"SET_FOCUS" => "1", 
			"SET_NBF" => "1", 
			"SET_PARAM" => "1", 
			"SHORT_FORM" => "1", 
			"SHOW" => "1", 
			"SORT" => "1", 
			"START" => "1", 
			"STEP" => "1", 
			"STOP" => "1", 
			"SWAP" => "1", 
			"SWITCH" => "1", 
			"SYSTEM_HELP" => "1", 
			"SYSTEM_JRNL" => "1", 
			"TABLE" => "1", 
			"THEN" => "1", 
			"TO" => "1", 
			"TRANSLATE" => "1", 
			"TRISTATE_BOX" => "1", 
			"UNLOCK" => "1", 
			"UNTIL" => "1", 
			"USER_LEX" => "1", 
			"VARDROP_BOX" => "1", 
			"VARLIST_BOX" => "1", 
			"VIA" => "1", 
			"VIDEO_PALETTE" => "1", 
			"V_SCROLLBAR" => "1", 
			"WAIT" => "1", 
			"WEND" => "1", 
			"WHERE" => "1", 
			"WHILE" => "1", 
			"WINDOW" => "1", 
			"WINPRT_SETUP" => "1", 
			"WRITE" => "1", 
			"ABS" => "2", 
			"ACS" => "2", 
			"ARG" => "2", 
			"ASC" => "2", 
			"ASN" => "2", 
			"ATH" => "2", 
			"ATN" => "2", 
			"BIN" => "2", 
			"BSZ" => "3", 
			"CHG" => "2", 
			"CHR" => "2", 
			"COS" => "2", 
			"CPL" => "2", 
			"CRC" => "2", 
			"CSE" => "2", 
			"CTL" => "3", 
			"CVS" => "2", 
			"DEC" => "2", 
			"DIR" => "3", 
			"DLL" => "2", 
			"DLX" => "2", 
			"DSK" => "2", 
			"DTE" => "2", 
			"ENV" => "2", 
			"EPT" => "2", 
			"ERR" => "3", 
			"EVN" => "2", 
			"EVS" => "2", 
			"EXP" => "2", 
			"FFN" => "2", 
			"FIB" => "2", 
			"FID" => "2", 
			"FIN" => "2", 
			"FPT" => "2", 
			"GAP" => "2", 
			"GBL" => "2", 
			"GEP" => "2", 
			"HSA" => "2", 
			"HSH" => "2", 
			"HTA" => "2", 
			"HWN" => "2", 
			"I3E" => "2", 
			"I86" => "2", 
			"IND" => "3", 
			"INT" => "2", 
			"IOL" => "2", 
			"IOR" => "2", 
			"JUL" => "2", 
			"KEC" => "2", 
			"KEF" => "2", 
			"KEL" => "2", 
			"KEN" => "2", 
			"KEP" => "2", 
			"KEY" => "2", 
			"KGN" => "2", 
			"LCS" => "2", 
			"LEN" => "2", 
			"LOG" => "2", 
			"LRC" => "2", 
			"LST" => "2", 
			"MAX" => "2", 
			"MEM" => "2", 
			"MID" => "2", 
			"MIN" => "2", 
			"MNM" => "2", 
			"MOD" => "2", 
			"MSG" => "3", 
			"MSK" => "2", 
			"MXC" => "2", 
			"MXL" => "2", 
			"NOT" => "2", 
			"NUL" => "2", 
			"NUM" => "2", 
			"OBJ" => "2", 
			"OPT" => "3", 
			"PAD" => "2", 
			"PCK" => "2", 
			"PFX" => "3", 
			"PGM" => "2", 
			"POS" => "2", 
			"PRC" => "3", 
			"PRM" => "3", 
			"PTH" => "2", 
			"PUB" => "2", 
			"RCD" => "2", 
			"RDX" => "2", 
			"REC" => "3", 
			"RND" => "3", 
			"RNO" => "3", 
			"SGN" => "2", 
			"SIN" => "2", 
			"SQR" => "2", 
			"SRT" => "2", 
			"SSZ" => "2", 
			"STK" => "2", 
			"STP" => "2", 
			"STR" => "2", 
			"SWP" => "2", 
			"SYS" => "3", 
			"TAN" => "2", 
			"TBL" => "3", 
			"TCB" => "2", 
			"TRX" => "2", 
			"TSK" => "2", 
			"TXH" => "2", 
			"TXW" => "2", 
			"UCS" => "2", 
			"UPK" => "2", 
			"VAL" => "2", 
			"VIN" => "2", 
			"VIS" => "2", 
			"XEQ" => "2", 
			"XFA" => "2", 
			"XOR" => "2", 
			"ADD" => "3", 
			"BKG" => "3", 
			"CHN" => "3", 
			"DAY" => "3", 
			"DLM" => "3", 
			"DSZ" => "3", 
			"DOM" => "3", 
			"EOM" => "3", 
			"ERS" => "3", 
			"ESC" => "3", 
			"FLG" => "3", 
			"FMT" => "3", 
			"FNT" => "3", 
			"GFN" => "3", 
			"GID" => "3", 
			"HFN" => "3", 
			"HLP" => "3", 
			"HWD" => "3", 
			"ISZ" => "3", 
			"KNO" => "3", 
			"LFA" => "3", 
			"LFO" => "3", 
			"LIP" => "3", 
			"LPG" => "3", 
			"LWD" => "3", 
			"MDE" => "3", 
			"MSE" => "3", 
			"MSL" => "3", 
			"NAR" => "3", 
			"NID" => "3", 
			"NBF" => "3", 
			"PGN" => "3", 
			"PSZ" => "3", 
			"QUO" => "3", 
			"OWN" => "3", 
			"RET" => "3", 
			"RSZ" => "3", 
			"RTY" => "3", 
			"SEP" => "3", 
			"SID" => "3", 
			"SSN" => "3", 
			"SIZ" => "3", 
			"TIM" => "3", 
			"TME" => "3", 
			"TMS" => "3", 
			"TSM" => "3", 
			"TIP" => "3", 
			"UID" => "3", 
			"UNT" => "3", 
			"WHO" => "3", 
			"'" => "4");

// Special extensions

// Each category can specify a PHP function that returns an altered
// version of the keyword.
        
        

$this->linkscripts    	= array(
			"1" => "donothing", 
			"2" => "donothing", 
			"3" => "donothing", 
			"4" => "donothing");
}


function donothing($keywordin)
{
	return $keywordin;
}

}?>
