<?php

/* Copyright (c) 1998-2010 ILIAS open source, Extended GPL, see docs/LICENSE */

/**
 * Service class for tests.
 *
 * @author	Björn Heyser <bheyser@databay.de>
 * @version	$Id$
 *
 * @ingroup ModulesTest
 */
class ilTestService
{
	/**
	 * @var ilObjTest
	 */
	protected $object = null;
	
	/**
	 * @param	ilObjTest $a_object
	 * @access	public
	 */
	public function __construct(ilObjTest $a_object)
	{
		$this->object = $a_object;
	}

	/**
	 * @global	ilObjUser	$ilUser
	 * @param	integer		$active_id
	 * @param	boolean		$short
	 * @return	array		$passOverwiewData
	 */
	public function getPassOverviewData($active_id, $short = false)
	{
		$passOverwiewData = array();
		
		global $ilUser;

		$scoredPass = $this->object->_getResultPass($active_id);
		$lastPass = $this->object->_getPass($active_id);

		$testPercentage = 0;
		$testReachedPoints = 0;
		$testMaxPoints = 0;

		for( $pass = 0; $pass <= $lastPass; $pass++)
		{
			$passFinishDate = $this->object->getPassFinishDate($active_id, $pass);
			
			if( $passFinishDate <= 0 )
			{
				continue;
			}

			if( !$short )
			{
				$resultData =& $this->object->getTestResult($active_id, $pass);

				if (!$resultData["pass"]["total_max_points"])
				{
					$passPercentage = 0;
				}
				else
				{
					$passPercentage = ($resultData["pass"]["total_reached_points"]/$resultData["pass"]["total_max_points"])*100;
				}

				$passMaxPoints = $resultData["pass"]["total_max_points"];
				$passReachedPoints = $resultData["pass"]["total_reached_points"];
				
				$passAnsweredQuestions = $this->object->getAnsweredQuestionCount($active_id, $pass);
				$passTotalQuestions = count($resultData) - 2;

				if( $pass == $scoredPass )
				{
					$isScoredPass = true;
					
					if (!$resultData["test"]["total_max_points"])
					{
						$testPercentage = 0;
					}
					else
					{
						$testPercentage = ($resultData["test"]["total_reached_points"]/$resultData["test"]["total_max_points"])*100;
					}
					
					$testMaxPoints = $resultData["test"]["total_max_points"];
					$testReachedPoints = $resultData["test"]["total_reached_points"];
					
					$passOverwiewData['test'] = array(
						'active_id' => $active_id,
						'scored_pass' => $scoredPass,
						'max_points' => $testMaxPoints,
						'reached_points' => $testReachedPoints,
						'percentage' => $testPercentage
					);
				}
				else $isScoredPass = false;
				
				$passOverwiewData['passes'][] = array(
					'active_id' => $active_id,
					'pass' => $pass,
					'finishdate' => $passFinishDate,
					'max_points' => $passMaxPoints,
					'reached_points' => $passReachedPoints,
					'percentage' => $passPercentage,
					'answered_questions' => $passAnsweredQuestions,
					'total_questions' => $passTotalQuestions,
					'is_scored_pass' => $isScoredPass
				);
			}
		}

		return $passOverwiewData;
	}
	
	/**
	 * Returns the list of answers of a users test pass and offers a scoring option
	 *
	 * @param array $result_array An array containing the results of the users test pass (generated by ilObjTest::getTestResult)
	 * @param integer $active_id Active ID of the active user
	 * @param integer $pass Test pass
	 * @param boolean $show_solutions TRUE, if the solution output should be shown in the answers, FALSE otherwise
	 * @return string HTML code of the list of answers
	 * @access public
	 */
	public function getManScoringQuestionGuiList($activeId, $pass)
	{
		include_once "./Modules/Test/classes/class.ilObjAssessmentFolder.php";
		$manScoringQuestionTypes = ilObjAssessmentFolder::_getManualScoring();

		$testResultData = $this->object->getTestResult($activeId, $pass);
		
		$manScoringQuestionGuiList = array();
		
		foreach($testResultData as $questionData)
		{
			if( !isset($questionData['qid']) )
			{
				continue;
			}
			
			if( !isset($questionData['type']) )
			{
				throw new ilTestException('no question type given!');
			}

			$questionGUI = $this->object->createQuestionGUI("", $questionData['qid']);
			
			if( !in_array($questionGUI->object->getQuestionTypeID(), $manScoringQuestionTypes) )
			{
				continue;
			}
			
			$manScoringQuestionGuiList[ $questionData['qid'] ] = $questionGUI;
		}
		
		return $manScoringQuestionGuiList;
	}
	
	public static function isManScoringDone($activeId)
	{
		$assessmentSetting = new ilSetting("assessment");
		return $assessmentSetting->get("manscoring_done_" . $activeId, false);
	}
	
	public static function setManScoringDone($activeId, $manScoringDone)
	{
		$assessmentSetting = new ilSetting("assessment");
		$assessmentSetting->set("manscoring_done_" . $activeId, (bool)$manScoringDone);
	}
}

