#!/bin/bash

#set -x
#set -e
#make this file executable via chmod +x pre-commit
#copy this file and check_for_parse_errors onto .git/hooks/pre-commit
#happy errorfree commiting!
if .git_hooks/check_for_parse_errors 
then
	exit 0
else
	exit 1
fi
