<?php

/**
 * Class ilCloudGroupedListGUI
 * @author      Fabian Schmid <fs@studer-raimann.ch>
 * @description Unfortunatelly there's no possibility to get the amount of titems out of ilGroupedListGUI. therefore this class can help...
 */
class ilCloudGroupedListGUI extends ilGroupedListGUI
{

    /**
     * @var int
     */
    protected $count = 0;

    /**
     * @param        $a_content
     * @param string $a_href
     * @param string $a_target
     * @param string $a_onclick
     * @param string $a_add_class
     * @param string $a_id
     * @param string $a_ttip
     * @param string $a_tt_my
     * @param string $a_tt_at
     * @param bool   $a_tt_use_htmlspecialchars
     */
    public function addEntry(
        string $a_content,
        string $a_href = "",
        string $a_target = "",
        string $a_onclick = "",
        string $a_add_class = "",
        string $a_id = "",
        string $a_ttip = "",
        string $a_tt_my = "right center",
        string $a_tt_at = "left center",
        bool $a_tt_use_htmlspecialchars = true
    ) : void {
        $this->count++;
        parent::addEntry($a_content, $a_href, $a_target, $a_onclick, $a_add_class, $a_id, $a_ttip, $a_tt_my, $a_tt_at,
            $a_tt_use_htmlspecialchars); // TODO: Change the autogenerated stub
    }

    public function addGroupHeader(
        string $a_content,
        string $a_add_class = ""
    ) : void {
        $this->count++;
        parent::addGroupHeader($a_content, $a_add_class); // TODO: Change the autogenerated stub
    }

    public function addSeparator() : void
    {
        $this->count++;
        parent::addSeparator(); // TODO: Change the autogenerated stub
    }

    /**
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * @return bool
     */
    public function hasItems()
    {
        return $this->getCount() > 0;
    }
}
