<?php

/**
 * This file is part of ILIAS, a powerful learning management system
 * published by ILIAS open source e-Learning e.V.
 *
 * ILIAS is licensed with the GPL-3.0,
 * see https://www.gnu.org/licenses/gpl-3.0.en.html
 * You should have received a copy of said license along with the
 * source code, too.
 *
 * If this is not the case or you just want to try ILIAS, you'll find
 * us at:
 * https://www.ilias.de
 * https://github.com/ILIAS-eLearning
 *
 *********************************************************************/

use ILIAS\FileUpload\MimeType;

return [
    '3dm' => MimeType::X_WORLD__X_3DMF,
    '3dmf' => MimeType::X_WORLD__X_3DMF,
    '3gp' => MimeType::VIDEO__3_GPP,
    'a' => MimeType::APPLICATION__OCTET_STREAM,
    'aab' => MimeType::APPLICATION__X_AUTHORWARE_BIN,
    'aam' => MimeType::APPLICATION__X_AUTHORWARE_MAP,
    'aas' => MimeType::APPLICATION__X_AUTHORWARE_SEG,
    'abc' => MimeType::TEXT__VND_ABC,
    'acgi' => MimeType::TEXT__HTML,
    'afl' => MimeType::VIDEO__ANIMAFLEX,
    'ai' => MimeType::APPLICATION__POSTSCRIPT,
    'aif' => [
        MimeType::AUDIO__X_AIFF,
        MimeType::AUDIO__AIFF,
    ],
    'aifc' => [
        MimeType::AUDIO__X_AIFF,
        MimeType::AUDIO__AIFF,
    ],
    'aiff' => [
        MimeType::AUDIO__X_AIFF,
        MimeType::AUDIO__AIFF,
    ],
    'aim' => MimeType::APPLICATION__X_AIM,
    'aip' => MimeType::TEXT__X_AUDIOSOFT_INTRA,
    'ani' => MimeType::APPLICATION__X_NAVI_ANIMATION,
    'aos' => MimeType::APPLICATION__X_NOKIA_9000_COMMUNICATOR_ADD_ON_SOFTWARE,
    'aps' => MimeType::APPLICATION__MIME,
    'arc' => MimeType::APPLICATION__OCTET_STREAM,
    'arj' => [
        MimeType::APPLICATION__ARJ,
        MimeType::APPLICATION__OCTET_STREAM
    ],
    'art' => MimeType::IMAGE__X_JG,
    'arw' => [
        MimeType::IMAGE__X_SONY_ARW,
        MimeType::IMAGE__ARW,
    ],
    'asd' => MimeType::VIDEO__X_MS_ASF,
    'asf' => MimeType::VIDEO__X_MS_ASF,
    'asm' => MimeType::TEXT__X_ASM,
    'asn' => MimeType::APPLICATION__ASTOUND,
    'asp' => MimeType::TEXT__ASP,
    'asx' => [
        MimeType::VIDEO__X_MS_ASF,
        MimeType::APPLICATION__X_MPLAYER2,
        MimeType::VIDEO__X_MS_ASF_PLUGIN
    ],
    'au' => [
        MimeType::AUDIO__BASIC,
        MimeType::AUDIO__X_AU
    ],
    'avi' => [
        MimeType::VIDEO__X_MSVIDEO,
        MimeType::VIDEO__AVI,
        MimeType::VIDEO__MSVIDEO,
        MimeType::APPLICATION__X_TROFF_MSVIDEO,
    ],
    'avs' => MimeType::VIDEO__AVS_VIDEO,
    'bat' => MimeType::TEXT__PLAIN,
    'bcpio' => MimeType::APPLICATION__X_BCPIO,
    'bin' => [
        MimeType::APPLICATION__MAC_BINARY,
        MimeType::APPLICATION__MACBINARY,
        MimeType::APPLICATION__OCTET_STREAM,
        MimeType::APPLICATION__X_BINARY,
        MimeType::APPLICATION__X_MACBINARY,
    ],
    'bm' => MimeType::IMAGE__BMP,
    'bmp' => [
        MimeType::IMAGE__X_MS_BMP,
        MimeType::IMAGE__BMP,
        MimeType::IMAGE__X_WINDOWS_BMP,
    ],
    'boo' => MimeType::APPLICATION__BOOK,
    'book' => MimeType::APPLICATION__BOOK,
    'boz' => MimeType::APPLICATION__X_BZIP2,
    'bsh' => MimeType::APPLICATION__X_BSH,
    'bz' => MimeType::APPLICATION__X_BZIP,
    'bz2' => MimeType::APPLICATION__X_BZIP2,
    'c' => [
        MimeType::TEXT__PLAIN,
        MimeType::TEXT__X_C,
    ],
    'c++' => MimeType::TEXT__PLAIN,
    'cat' => MimeType::APPLICATION__VND_MS_PKI_SECCAT,
    'cc' => [
        MimeType::TEXT__PLAIN,
        MimeType::TEXT__X_C,
    ],
    'ccad' => MimeType::APPLICATION__CLARISCAD,
    'cco' => MimeType::APPLICATION__X_COCOA,
    'cdf' => [
        MimeType::APPLICATION__X_CDF,
        MimeType::APPLICATION__CDF,
        MimeType::APPLICATION__X_NETCDF,
    ],
    'cer' => [
        MimeType::APPLICATION__PKIX_CERT,
        MimeType::APPLICATION__X_X509_CA_CERT,
    ],
    'cha' => MimeType::APPLICATION__X_CHAT,
    'chat' => MimeType::APPLICATION__X_CHAT,
    'class' => [
        MimeType::APPLICATION__X_JAVA_APPLET,
        MimeType::APPLICATION__JAVA,
        MimeType::APPLICATION__JAVA_BYTE_CODE,
        MimeType::APPLICATION__X_JAVA_CLASS,
    ],
    'com' => [
        MimeType::APPLICATION__OCTET_STREAM,
        MimeType::TEXT__PLAIN,
    ],
    'conf' => MimeType::TEXT__PLAIN,
    'cpio' => MimeType::APPLICATION__X_CPIO,
    'cpp' => MimeType::TEXT__X_C,
    'cpt' => [
        MimeType::APPLICATION__MAC_COMPACTPRO,
        MimeType::APPLICATION__X_COMPACTPRO,
        MimeType::APPLICATION__X_CPT,
    ],
    'crl' => [
        MimeType::APPLICATION__PKCS_CRL,
        MimeType::APPLICATION__PKIX_CRL,
    ],
    'crt' => [
        MimeType::APPLICATION__X_X509_CA_CERT,
        MimeType::APPLICATION__PKIX_CERT,
        MimeType::APPLICATION__X_X509_USER_CERT,
    ],
    'crw' => [
        MimeType::IMAGE__X_CANON_CRW,
        MimeType::IMAGE__CRW,
    ],
    'cr2' => [
        MimeType::IMAGE__X_CANON_CR2,
        MimeType::IMAGE__CR2,
    ],
    'csh' => [
        MimeType::APPLICATION__X_CSH,
        MimeType::TEXT__X_SCRIPT_CSH,
    ],
    'css' => [
        MimeType::TEXT__CSS,
        MimeType::APPLICATION__X_POINTPLUS,
    ],
    'cxx' => MimeType::TEXT__PLAIN,
    'dcr' => MimeType::APPLICATION__X_DIRECTOR,
    'deepv' => MimeType::APPLICATION__X_DEEPV,
    'def' => MimeType::TEXT__PLAIN,
    'der' => MimeType::APPLICATION__X_X509_CA_CERT,
    'dif' => MimeType::VIDEO__X_DV,
    'dir' => MimeType::APPLICATION__X_DIRECTOR,
    'dl' => [
        MimeType::VIDEO__DL,
        MimeType::VIDEO__X_DL,
    ],
    'doc' => MimeType::APPLICATION__MSWORD,
    'docx' => MimeType::APPLICATION__VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_DOCUMENT,
    'dot' => MimeType::APPLICATION__MSWORD,
    'dotx' => MimeType::APPLICATION__VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_TEMPLATE,
    'dp' => MimeType::APPLICATION__COMMONGROUND,
    'dng' => [
        MimeType::IMAGE__X_ADOBE_DNG,
        MimeType::IMAGE__DNG,
    ],
    'drw' => MimeType::APPLICATION__DRAFTING,
    'dump' => MimeType::APPLICATION__OCTET_STREAM,
    'dv' => MimeType::VIDEO__X_DV,
    'dvi' => MimeType::APPLICATION__X_DVI,
    'dwf' => MimeType::MODEL__VND_DWF,
    'dwg' => [
        MimeType::APPLICATION__ACAD,
        MimeType::IMAGE__VND_DWG,
        MimeType::IMAGE__X_DWG,
    ],
    'dxf' => [
        MimeType::APPLICATION__DXF,
        MimeType::IMAGE__VND_DWG,
        MimeType::IMAGE__X_DWG,
    ],
    'dxr' => MimeType::APPLICATION__X_DIRECTOR,
    'el' => MimeType::TEXT__X_SCRIPT_ELISP,
    'elc' => MimeType::APPLICATION__X_ELC,
    'env' => MimeType::APPLICATION__X_ENVOY,
    'eps' => MimeType::APPLICATION__POSTSCRIPT,
    'epub' => MimeType::APPLICATION__EPUB,
    'es' => MimeType::APPLICATION__X_ESREHBER,
    'etx' => MimeType::TEXT__X_SETEXT,
    'evy' => [
        MimeType::APPLICATION__ENVOY,
        MimeType::APPLICATION__X_ENVOY,
    ],
    'exe' => MimeType::APPLICATION__OCTET_STREAM,
    'f' => [
        MimeType::TEXT__PLAIN,
        'f' => MimeType::TEXT__X_FORTRAN,
    ],
    'f77' => MimeType::TEXT__X_FORTRAN,
    'f90' => [
        MimeType::TEXT__PLAIN,
        MimeType::TEXT__X_FORTRAN,
    ],
    'fdf' => MimeType::APPLICATION__VND_FDF,
    'fif' => [
        MimeType::APPLICATION__FRACTALS,
        MimeType::IMAGE__FIF,
    ],
    'fli' => [
        MimeType::VIDEO__FLI,
        MimeType::VIDEO__X_FLI,
    ],
    'flo' => MimeType::IMAGE__FLORIAN,
    'flv' => MimeType::VIDEO__X_FLV,
    'flx' => MimeType::TEXT__VND_FMI_FLEXSTOR,
    'fmf' => MimeType::VIDEO__X_ATOMIC3D_FEATURE,
    'for' => [
        MimeType::TEXT__PLAIN,
        MimeType::TEXT__X_FORTRAN,
    ],
    'fpx' => [
        MimeType::IMAGE__VND_FPX,
        MimeType::IMAGE__VND_NET_FPX,
    ],
    'frl' => MimeType::APPLICATION__FREELOADER,
    'funk' => MimeType::AUDIO__MAKE,
    'g' => MimeType::TEXT__PLAIN,
    'g3' => MimeType::IMAGE__G3FAX,
    'gif' => MimeType::IMAGE__GIF,
    'gl' => [
        MimeType::VIDEO__GL,
        MimeType::VIDEO__X_GL,
    ],
    'gsd' => MimeType::AUDIO__X_GSM,
    'gsm' => MimeType::AUDIO__X_GSM,
    'gsp' => MimeType::APPLICATION__X_GSP,
    'gss' => MimeType::APPLICATION__X_GSS,
    'gtar' => MimeType::APPLICATION__X_GTAR,
    'gz' => [
        MimeType::APPLICATION__X_COMPRESSED,
        MimeType::APPLICATION__X_GZIP,
    ],
    'gzip' => [
        MimeType::APPLICATION__X_GZIP,
        MimeType::MULTIPART__X_GZIP,
    ],
    'h' => [
        MimeType::TEXT__PLAIN,
        MimeType::TEXT__X_H,
    ],
    'hdf' => MimeType::APPLICATION__X_HDF,
    'help' => MimeType::APPLICATION__X_HELPFILE,
    'hgl' => MimeType::APPLICATION__VND_HP_HPGL,
    'hh' => [
        MimeType::TEXT__PLAIN,
        MimeType::TEXT__X_H,
    ],
    'hlb' => MimeType::TEXT__X_SCRIPT,
    'hlp' => [
        MimeType::APPLICATION__HLP,
        MimeType::APPLICATION__X_HELPFILE,
        MimeType::APPLICATION__X_WINHELP,
    ],
    'hpg' => MimeType::APPLICATION__VND_HP_HPGL,
    'hpgl' => MimeType::APPLICATION__VND_HP_HPGL,
    'hqx' => [
        MimeType::APPLICATION__BINHEX,
        MimeType::APPLICATION__BINHEX4,
        MimeType::APPLICATION__MAC_BINHEX,
        MimeType::APPLICATION__MAC_BINHEX40,
        MimeType::APPLICATION__X_BINHEX40,
        MimeType::APPLICATION__X_MAC_BINHEX40,
    ],
    'hta' => MimeType::APPLICATION__HTA,
    'htc' => MimeType::TEXT__X_COMPONENT,
    'htm' => MimeType::TEXT__HTML,
    'html' => MimeType::TEXT__HTML,
    'htmls' => MimeType::TEXT__HTML,
    'htt' => MimeType::TEXT__WEBVIEWHTML,
    'htx' => MimeType::TEXT__HTML,
    'ice' => MimeType::X_CONFERENCE__X_COOLTALK,
    'ics' => MimeType::TEXT__CALENDAR,
    'ico' => MimeType::IMAGE__X_ICON,
    'idc' => MimeType::TEXT__PLAIN,
    'ief' => MimeType::IMAGE__IEF,
    'iefs' => MimeType::IMAGE__IEF,
    'iges' => [
        MimeType::APPLICATION__IGES,
        MimeType::MODEL__IGES,
    ],
    'igs' => [
        MimeType::APPLICATION__IGES,
        MimeType::MODEL__IGES,
    ],
    'ima' => MimeType::APPLICATION__X_IMA,
    'imap' => MimeType::APPLICATION__X_HTTPD_IMAP,
    'inf' => MimeType::APPLICATION__INF,
    'ins' => MimeType::APPLICATION__X_INTERNETT_SIGNUP,
    'ip' => MimeType::APPLICATION__X_IP2,
    'isu' => MimeType::VIDEO__X_ISVIDEO,
    'it' => MimeType::AUDIO__IT,
    'iv' => MimeType::APPLICATION__X_INVENTOR,
    'ivr' => MimeType::I_WORLD__I_VRML,
    'ivy' => MimeType::APPLICATION__X_LIVESCREEN,
    'jam' => MimeType::AUDIO__X_JAM,
    'jav' => [
        MimeType::TEXT__PLAIN,
        MimeType::TEXT__X_JAVA_SOURCE,
    ],
    'java' => [
        MimeType::TEXT__PLAIN,
        MimeType::TEXT__X_JAVA_SOURCE,
    ],
    'jcm' => MimeType::APPLICATION__X_JAVA_COMMERCE,
    'jfif' => [
        MimeType::IMAGE__JPEG,
        MimeType::IMAGE__PJPEG,
    ],
    'jfif-tbnl' => MimeType::IMAGE__JPEG,
    'jpe' => [
        MimeType::IMAGE__JPEG,
        MimeType::IMAGE__PJPEG,
    ],
    'jpeg' => [
        MimeType::IMAGE__JPEG,
        MimeType::IMAGE__PJPEG,
    ],
    'jpg' => [
        MimeType::IMAGE__JPEG,
        MimeType::IMAGE__PJPEG,
    ],
    'jps' => MimeType::IMAGE__X_JPS,
    'js' => [
        MimeType::APPLICATION__JAVASCRIPT,
        MimeType::APPLICATION__X_JAVASCRIPT,
        MimeType::APPLICATION__ECMASCRIPT,
        MimeType::TEXT__JAVASCRIPT,
        MimeType::TEXT__ECMASCRIPT,
    ],
    'json' => [
        MimeType::APPLICATION__JSON, // rfc4627
        MimeType::APPLICATION__JAVASCRIPT,
    ],
    'jut' => MimeType::IMAGE__JUTVISION,
    'kar' => [
        MimeType::AUDIO__MIDI,
        MimeType::MUSIC__X_KARAOKE,
    ],
    'ksh' => [
        MimeType::APPLICATION__X_KSH,
        MimeType::TEXT__X_SCRIPT_KSH,
    ],
    'la' => [
        MimeType::AUDIO__NSPAUDIO,
        MimeType::AUDIO__X_NSPAUDIO,
    ],
    'lam' => MimeType::AUDIO__X_LIVEAUDIO,
    'latex' => MimeType::APPLICATION__X_LATEX,
    'lha' => [
        MimeType::APPLICATION__LHA,
        MimeType::APPLICATION__OCTET_STREAM,
        MimeType::APPLICATION__X_LHA,
    ],
    'lhx' => MimeType::APPLICATION__OCTET_STREAM,
    'list' => MimeType::TEXT__PLAIN,
    'lma' => [
        MimeType::AUDIO__NSPAUDIO,
        MimeType::AUDIO__X_NSPAUDIO,
    ],
    'log' => MimeType::TEXT__PLAIN,
    'lsp' => [
        MimeType::APPLICATION__X_LISP,
        MimeType::TEXT__X_SCRIPT_LISP,
    ],
    'lst' => MimeType::TEXT__PLAIN,
    'lsx' => MimeType::TEXT__X_LA_ASF,
    'ltx' => MimeType::APPLICATION__X_LATEX,
    'lzh' => [
        MimeType::APPLICATION__OCTET_STREAM,
        MimeType::APPLICATION__X_LZH,
    ],
    'lzx' => [
        MimeType::APPLICATION__LZX,
        MimeType::APPLICATION__OCTET_STREAM,
        MimeType::APPLICATION__X_LZX,
    ],
    'm' => [
        MimeType::TEXT__PLAIN,
        MimeType::TEXT__X_M,
    ],
    'm1v' => MimeType::VIDEO__MPEG,
    'm2a' => MimeType::AUDIO__MPEG,
    'm2v' => MimeType::VIDEO__MPEG,
    'm3u' => MimeType::AUDIO__X_MPEQURL,
    'm4a' => MimeType::AUDIO__MP4,
    'm4v' => MimeType::VIDEO__MP4,
    'man' => MimeType::APPLICATION__X_TROFF_MAN,
    'map' => MimeType::APPLICATION__X_NAVIMAP,
    'mar' => MimeType::TEXT__PLAIN,
    'mbd' => MimeType::APPLICATION__MBEDLET,
    'mc$' => MimeType::APPLICATION__X_MAGIC_CAP_PACKAGE_1_0,
    'mcd' => [
        MimeType::APPLICATION__MCAD,
        MimeType::APPLICATION__X_MATHCAD,
    ],
    'mcf' => [
        MimeType::IMAGE__VASA,
        MimeType::TEXT__MCF,
    ],
    'mcp' => MimeType::APPLICATION__NETMC,
    'me' => MimeType::APPLICATION__X_TROFF_ME,
    'mht' => MimeType::MESSAGE__RFC822,
    'mhtml' => MimeType::MESSAGE__RFC822,
    'md' => MimeType::TEXT__MARKDOWN,
    'mid' => [
        MimeType::AUDIO__MIDI,
        MimeType::APPLICATION__X_MIDI,
        MimeType::AUDIO__X_MID,
        MimeType::AUDIO__X_MIDI,
        MimeType::MUSIC__CRESCENDO,
        MimeType::X_MUSIC__X_MIDI,
    ],
    'midi' => [
        MimeType::AUDIO__MIDI,
        MimeType::APPLICATION__X_MIDI,
        MimeType::AUDIO__X_MID,
        MimeType::AUDIO__X_MIDI,
        MimeType::MUSIC__CRESCENDO,
        MimeType::X_MUSIC__X_MIDI,
    ],
    'mif' => [
        MimeType::APPLICATION__X_FRAME,
        MimeType::APPLICATION__X_MIF,
    ],
    'mime' => [
        MimeType::MESSAGE__RFC822,
        MimeType::WWW__MIME,
    ],
    'mjf' => MimeType::AUDIO__X_VND_AUDIOEXPLOSION_MJUICEMEDIAFILE,
    'mjpg' => MimeType::VIDEO__X_MOTION_JPEG,
    'mm' => [
        MimeType::APPLICATION__BASE64,
        MimeType::APPLICATION__X_MEME,
    ],
    'mme' => MimeType::APPLICATION__BASE64,
    'mobi' => MimeType::APPLICATION__X_MOBI,
    'mod' => [
        MimeType::AUDIO__MOD,
        MimeType::AUDIO__X_MOD,
    ],
    'moov' => MimeType::VIDEO__QUICKTIME,
    'mov' => MimeType::VIDEO__QUICKTIME,
    'movie' => MimeType::VIDEO__X_SGI_MOVIE,
    'mp2' => [
        MimeType::AUDIO__MPEG,
        MimeType::AUDIO__X_MPEG,
        MimeType::VIDEO__MPEG,
        MimeType::VIDEO__X_MPEG,
        MimeType::VIDEO__X_MPEQ2A,
    ],
    'mp3' => [
        MimeType::AUDIO__MPEG,
        MimeType::AUDIO__MPEG3,
        MimeType::AUDIO__X_MPEG_3,
        MimeType::VIDEO__MPEG,
        MimeType::VIDEO__X_MPEG,
    ],
    'mp4' => MimeType::VIDEO__MP4,
    'mpa' => [
        MimeType::AUDIO__MPEG,
        MimeType::VIDEO__MPEG,
    ],
    'mpc' => MimeType::APPLICATION__X_PROJECT,
    'mpe' => MimeType::VIDEO__MPEG,
    'mpeg' => MimeType::VIDEO__MPEG,
    'mpg' => [
        MimeType::AUDIO__MPEG,
        MimeType::VIDEO__MPEG,
    ],
    'mpga' => MimeType::AUDIO__MPEG,
    'mpp' => MimeType::APPLICATION__VND_MS_PROJECT,
    'mpt' => MimeType::APPLICATION__X_PROJECT,
    'mpv' => MimeType::APPLICATION__X_PROJECT,
    'mpx' => MimeType::APPLICATION__X_PROJECT,
    'mrc' => MimeType::APPLICATION__MARC,
    'ms' => MimeType::APPLICATION__X_TROFF_MS,
    'mv' => MimeType::VIDEO__X_SGI_MOVIE,
    'mv4' => MimeType::VIDEO__MP4,
    'my' => MimeType::AUDIO__MAKE,
    'mzz' => MimeType::APPLICATION__X_VND_AUDIOEXPLOSION_MZZ,
    'nap' => MimeType::IMAGE__NAPLPS,
    'naplps' => MimeType::IMAGE__NAPLPS,
    'nc' => MimeType::APPLICATION__X_NETCDF,
    'ncm' => MimeType::APPLICATION__VND_NOKIA_CONFIGURATION_MESSAGE,
    'nef' => [
        MimeType::IMAGE__X_NIKON_NEF,
        MimeType::IMAGE__NEF,
    ],
    'nif' => MimeType::IMAGE__X_NIFF,
    'niff' => MimeType::IMAGE__X_NIFF,
    'nix' => MimeType::APPLICATION__X_MIX_TRANSFER,
    'nsc' => MimeType::APPLICATION__X_CONFERENCE,
    'nvd' => MimeType::APPLICATION__X_NAVIDOC,
    'o' => MimeType::APPLICATION__OCTET_STREAM,
    'oda' => MimeType::APPLICATION__ODA,
    'oga' => MimeType::AUDIO__OGG,
    'ogg' => MimeType::AUDIO__OGG,
    'ogv' => MimeType::VIDEO__OGG,
    'ogx' => MimeType::APPLICATION__OGG,
    'omc' => MimeType::APPLICATION__X_OMC,
    'omcd' => MimeType::APPLICATION__X_OMCDATAMAKER,
    'omcr' => MimeType::APPLICATION__X_OMCREGERATOR,
    'p' => MimeType::TEXT__X_PASCAL,
    'p10' => [
        MimeType::APPLICATION__PKCS10,
        MimeType::APPLICATION__X_PKCS10,
    ],
    'p12' => [
        MimeType::APPLICATION__PKCS_12,
        MimeType::APPLICATION__X_PKCS12,
    ],
    'p7a' => MimeType::APPLICATION__X_PKCS7_SIGNATURE,
    'p7c' => [
        MimeType::APPLICATION__PKCS7_MIME,
        MimeType::APPLICATION__X_PKCS7_MIME,
    ],
    'p7m' => [
        MimeType::APPLICATION__PKCS7_MIME,
        MimeType::APPLICATION__X_PKCS7_MIME,
    ],
    'p7r' => MimeType::APPLICATION__X_PKCS7_CERTREQRESP,
    'p7s' => MimeType::APPLICATION__PKCS7_SIGNATURE,
    'part' => MimeType::APPLICATION__PRO_ENG,
    'pas' => MimeType::TEXT__PASCAL,
    'pbm' => MimeType::IMAGE__X_PORTABLE_BITMAP,
    'pcl' => [
        MimeType::APPLICATION__VND_HP_PCL,
        MimeType::APPLICATION__X_PCL,
    ],
    'pct' => MimeType::IMAGE__X_PICT,
    'pcx' => MimeType::IMAGE__X_PCX,
    'pdb' => MimeType::CHEMICAL__X_PDB,
    'pdf' => MimeType::APPLICATION__PDF,
    'pfunk' => [
        MimeType::AUDIO__MAKE,
        MimeType::AUDIO__MAKE_MY_FUNK,
    ],
    'pgm' => [
        MimeType::IMAGE__X_PORTABLE_GRAYMAP,
        MimeType::IMAGE__X_PORTABLE_GREYMAP,
    ],
    'pic' => MimeType::IMAGE__PICT,
    'pict' => MimeType::IMAGE__PICT,
    'pkg' => MimeType::APPLICATION__X_NEWTON_COMPATIBLE_PKG,
    'pko' => MimeType::APPLICATION__VND_MS_PKI_PKO,
    'pl' => [
        MimeType::TEXT__PLAIN,
        MimeType::TEXT__X_SCRIPT_PERL,
    ],
    'plx' => MimeType::APPLICATION__X_PIXCLSCRIPT,
    'pm' => [
        MimeType::IMAGE__X_XPIXMAP,
        MimeType::TEXT__X_SCRIPT_PERL_MODULE,
    ],
    'pm4' => MimeType::APPLICATION__X_PAGEMAKER,
    'pm5' => MimeType::APPLICATION__X_PAGEMAKER,
    'png' => MimeType::IMAGE__PNG,
    'pnm' => [
        MimeType::APPLICATION__X_PORTABLE_ANYMAP,
        MimeType::IMAGE__X_PORTABLE_ANYMAP,
    ],
    'pot' => [
        MimeType::APPLICATION__MSPOWERPOINT,
        MimeType::APPLICATION__VND_MS_POWERPOINT,
    ],
    'potx' => MimeType::APPLICATION__VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_TEMPLATE,
    'pov' => MimeType::MODEL__X_POV,
    'ppa' => MimeType::APPLICATION__VND_MS_POWERPOINT,
    'ppm' => MimeType::IMAGE__X_PORTABLE_PIXMAP,
    'pps' => [
        MimeType::APPLICATION__MSPOWERPOINT,
        MimeType::APPLICATION__VND_MS_POWERPOINT,
    ],
    'ppsx' => MimeType::APPLICATION__VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_SLIDESHOW,
    'ppt' => [
        MimeType::APPLICATION__MSPOWERPOINT,
        MimeType::APPLICATION__POWERPOINT,
        MimeType::APPLICATION__VND_MS_POWERPOINT,
        MimeType::APPLICATION__X_MSPOWERPOINT,
    ],
    'pptx' => MimeType::APPLICATION__VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_PRESENTATION,
    'ppz' => MimeType::APPLICATION__MSPOWERPOINT,
    'pre' => MimeType::APPLICATION__X_FREELANCE,
    'prt' => MimeType::APPLICATION__PRO_ENG,
    'ps' => MimeType::APPLICATION__POSTSCRIPT,
    'psd' => MimeType::APPLICATION__OCTET_STREAM,
    'pvu' => MimeType::PALEOVU__X_PV,
    'pwz' => MimeType::APPLICATION__VND_MS_POWERPOINT,
    'py' => MimeType::TEXT__X_SCRIPT_PHYTON,
    'pyc' => MimeType::APPLICATION__X_BYTECODE_PYTHON,
    'qcp' => MimeType::AUDIO__VND_QCELP,
    'qd3' => MimeType::X_WORLD__X_3DMF,
    'qd3d' => MimeType::X_WORLD__X_3DMF,
    'qif' => MimeType::IMAGE__X_QUICKTIME,
    'qt' => MimeType::VIDEO__QUICKTIME,
    'qtc' => MimeType::VIDEO__X_QTC,
    'qti' => MimeType::IMAGE__X_QUICKTIME,
    'qtif' => MimeType::IMAGE__X_QUICKTIME,
    'ra' => [
        MimeType::AUDIO__X_PN_REALAUDIO,
        MimeType::AUDIO__X_PN_REALAUDIO_PLUGIN,
        MimeType::AUDIO__X_REALAUDIO,
    ],
    'ram' => MimeType::AUDIO__X_PN_REALAUDIO,
    'ras' => [
        MimeType::APPLICATION__X_CMU_RASTER,
        MimeType::IMAGE__CMU_RASTER,
        MimeType::IMAGE__X_CMU_RASTER,
    ],
    'rast' => MimeType::IMAGE__CMU_RASTER,
    'rexx' => MimeType::TEXT__X_SCRIPT_REXX,
    'rf' => MimeType::IMAGE__VND_RN_REALFLASH,
    'rgb' => MimeType::IMAGE__X_RGB,
    'rm' => [
        MimeType::APPLICATION__VND_RN_REALMEDIA,
        MimeType::AUDIO__X_PN_REALAUDIO,
    ],
    'rmi' => MimeType::AUDIO__MID,
    'rmm' => MimeType::AUDIO__X_PN_REALAUDIO,
    'rmp' => [
        MimeType::AUDIO__X_PN_REALAUDIO,
        MimeType::AUDIO__X_PN_REALAUDIO_PLUGIN,
    ],
    'rng' => [
        MimeType::APPLICATION__RINGING_TONES,
        MimeType::APPLICATION__VND_NOKIA_RINGING_TONE,
    ],
    'rnx' => MimeType::APPLICATION__VND_RN_REALPLAYER,
    'roff' => MimeType::APPLICATION__X_TROFF,
    'rp' => MimeType::IMAGE__VND_RN_REALPIX,
    'rpm' => MimeType::AUDIO__X_PN_REALAUDIO_PLUGIN,
    'rt' => [
        MimeType::TEXT__RICHTEXT,
        MimeType::TEXT__VND_RN_REALTEXT,
    ],
    'rtf' => [
        MimeType::APPLICATION__RTF,
        MimeType::APPLICATION__X_RTF,
        MimeType::TEXT__RICHTEXT,
    ],
    'rtx' => [
        MimeType::APPLICATION__RTF,
        MimeType::TEXT__RICHTEXT,
    ],
    'rv' => MimeType::VIDEO__VND_RN_REALVIDEO,
    's' => MimeType::TEXT__X_ASM,
    's3m' => MimeType::AUDIO__S3M,
    'saveme' => MimeType::APPLICATION__OCTET_STREAM,
    'sbk' => MimeType::APPLICATION__X_TBOOK,
    'scm' => [
        MimeType::APPLICATION__X_LOTUSSCREENCAM,
        MimeType::TEXT__X_SCRIPT_GUILE,
        MimeType::TEXT__X_SCRIPT_SCHEME,
        MimeType::VIDEO__X_SCM,
    ],
    'sdml' => MimeType::TEXT__PLAIN,
    'sdp' => [
        MimeType::APPLICATION__SDP,
        MimeType::APPLICATION__X_SDP,
    ],
    'sdr' => MimeType::APPLICATION__SOUNDER,
    'seb' => MimeType::APPLICATION__SEB,
    'sea' => [
        MimeType::APPLICATION__SEA,
        MimeType::APPLICATION__X_SEA,
    ],
    'set' => MimeType::APPLICATION__SET,
    'sgm' => [
        MimeType::TEXT__SGML,
        MimeType::TEXT__X_SGML,
    ],
    'sgml' => [
        MimeType::TEXT__SGML,
        MimeType::TEXT__X_SGML,
    ],
    'sh' => [
        MimeType::APPLICATION__X_BSH,
        MimeType::APPLICATION__X_SH,
        MimeType::APPLICATION__X_SHAR,
        MimeType::TEXT__X_SCRIPT_SH,
    ],
    'shar' => [
        MimeType::APPLICATION__X_BSH,
        MimeType::APPLICATION__X_SHAR,
    ],
    'shtml' => [
        MimeType::TEXT__HTML,
        MimeType::TEXT__X_SERVER_PARSED_HTML,
    ],
    'sid' => MimeType::AUDIO__X_PSID,
    'sit' => [
        MimeType::APPLICATION__X_SIT,
        MimeType::APPLICATION__X_STUFFIT,
    ],
    'skd' => MimeType::APPLICATION__X_KOAN,
    'skm' => MimeType::APPLICATION__X_KOAN,
    'skp' => MimeType::APPLICATION__X_KOAN,
    'skt' => MimeType::APPLICATION__X_KOAN,
    'sl' => MimeType::APPLICATION__X_SEELOGO,
    'sldx' => MimeType::APPLICATION__VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_SLIDE,
    'smi' => MimeType::APPLICATION__SMIL,
    'smil' => MimeType::APPLICATION__SMIL,
    'snd' => [
        MimeType::AUDIO__BASIC,
        MimeType::AUDIO__X_ADPCM,
    ],
    'sol' => MimeType::APPLICATION__SOLIDS,
    'spc' => [
        MimeType::APPLICATION__X_PKCS7_CERTIFICATES,
        MimeType::TEXT__X_SPEECH,
    ],
    'spl' => MimeType::APPLICATION__FUTURESPLASH,
    'spr' => MimeType::APPLICATION__X_SPRITE,
    'sprite' => MimeType::APPLICATION__X_SPRITE,
    'src' => MimeType::APPLICATION__X_WAIS_SOURCE,
    'ssi' => MimeType::TEXT__X_SERVER_PARSED_HTML,
    'ssm' => MimeType::APPLICATION__STREAMINGMEDIA,
    'sst' => MimeType::APPLICATION__VND_MS_PKI_CERTSTORE,
    'step' => MimeType::APPLICATION__STEP,
    'stl' => [
        MimeType::APPLICATION__SLA,
        MimeType::APPLICATION__VND_MS_PKI_STL,
        MimeType::APPLICATION__X_NAVISTYLE,
    ],
    'stp' => MimeType::APPLICATION__STEP,
    'sv4cpio' => MimeType::APPLICATION__X_SV4CPIO,
    'sv4crc' => MimeType::APPLICATION__X_SV4CRC,
    'svf' => [
        MimeType::IMAGE__VND_DWG,
        MimeType::IMAGE__X_DWG,
    ],
    'svg' => MimeType::IMAGE__SVG_XML,
    'svr' => [
        MimeType::APPLICATION__X_WORLD,
        MimeType::X_WORLD__X_SVR,
    ],
    'swf' => MimeType::APPLICATION__X_SHOCKWAVE_FLASH,
    't' => MimeType::APPLICATION__X_TROFF,
    'talk' => MimeType::TEXT__X_SPEECH,
    'tar' => MimeType::APPLICATION__X_TAR,
    'tbk' => [
        MimeType::APPLICATION__TOOLBOOK,
        MimeType::APPLICATION__X_TBOOK,
    ],
    'tcl' => [
        MimeType::APPLICATION__X_TCL,
        MimeType::TEXT__X_SCRIPT_TCL,
    ],
    'tcsh' => MimeType::TEXT__X_SCRIPT_TCSH,
    'tex' => MimeType::APPLICATION__X_TEX,
    'texi' => MimeType::APPLICATION__X_TEXINFO,
    'texinfo' => MimeType::APPLICATION__X_TEXINFO,
    'text' => [
        MimeType::TEXT__PLAIN,
        MimeType::APPLICATION__PLAIN,
    ],
    'tgz' => [
        MimeType::APPLICATION__GNUTAR,
        MimeType::APPLICATION__X_COMPRESSED,
    ],
    'tif' => [
        MimeType::IMAGE__TIFF,
        MimeType::IMAGE__X_TIFF,
    ],
    'tiff' => [
        MimeType::IMAGE__TIFF,
        MimeType::IMAGE__X_TIFF,
    ],
    'tr' => MimeType::APPLICATION__X_TROFF,
    'tsi' => MimeType::AUDIO__TSP_AUDIO,
    'tsp' => [
        MimeType::APPLICATION__DSPTYPE,
        MimeType::AUDIO__TSPLAYER,
    ],
    'tsv' => MimeType::TEXT__TAB_SEPARATED_VALUES,
    'turbot' => MimeType::IMAGE__FLORIAN,
    'txt' => MimeType::TEXT__PLAIN,
    'uil' => MimeType::TEXT__X_UIL,
    'uni' => MimeType::TEXT__URI_LIST,
    'unis' => MimeType::TEXT__URI_LIST,
    'unv' => MimeType::APPLICATION__I_DEAS,
    'uri' => MimeType::TEXT__URI_LIST,
    'uris' => MimeType::TEXT__URI_LIST,
    'ustar' => [
        MimeType::APPLICATION__X_USTAR,
        MimeType::MULTIPART__X_USTAR,
    ],
    'uu' => [
        MimeType::APPLICATION__OCTET_STREAM,
        MimeType::TEXT__X_UUENCODE,
    ],
    'uue' => MimeType::TEXT__X_UUENCODE,
    'vcd' => MimeType::APPLICATION__X_CDLINK,
    'vcs' => MimeType::TEXT__X_VCALENDAR,
    'vda' => MimeType::APPLICATION__VDA,
    'vdo' => MimeType::VIDEO__VDO,
    'vew' => MimeType::APPLICATION__GROUPWISE,
    'vimeo' => MimeType::VIDEO__VIMEO,
    'viv' => [
        MimeType::VIDEO__VIVO,
        MimeType::VIDEO__VND_VIVO,
    ],
    'vivo' => [
        MimeType::VIDEO__VIVO,
        MimeType::VIDEO__VND_VIVO,
    ],
    'vmd' => MimeType::APPLICATION__VOCALTEC_MEDIA_DESC,
    'vmf' => MimeType::APPLICATION__VOCALTEC_MEDIA_FILE,
    'voc' => [
        MimeType::AUDIO__VOC,
        MimeType::AUDIO__X_VOC,
    ],
    'vos' => MimeType::VIDEO__VOSAIC,
    'vox' => MimeType::AUDIO__VOXWARE,
    'vqe' => MimeType::AUDIO__X_TWINVQ_PLUGIN,
    'vqf' => MimeType::AUDIO__X_TWINVQ,
    'vql' => MimeType::AUDIO__X_TWINVQ_PLUGIN,
    'vrml' => [
        MimeType::APPLICATION__X_VRML,
        MimeType::MODEL__VRML,
        MimeType::X_WORLD__X_VRML,
    ],
    'vrt' => MimeType::X_WORLD__X_VRT,
    'vsd' => MimeType::APPLICATION__X_VISIO,
    'vst' => MimeType::APPLICATION__X_VISIO,
    'vsw' => MimeType::APPLICATION__X_VISIO,
    'vtt' => MimeType::TEXT__VTT,
    'w60' => MimeType::APPLICATION__WORDPERFECT6_0,
    'w61' => MimeType::APPLICATION__WORDPERFECT6_1,
    'w6w' => MimeType::APPLICATION__MSWORD,
    'wav' => [
        MimeType::AUDIO__X_WAV,
        MimeType::AUDIO__WAV,
    ],
    'wb1' => MimeType::APPLICATION__X_QPRO,
    'wbmp' => MimeType::IMAGE__VND_WAP_WBMP,
    'web' => MimeType::APPLICATION__VND_XARA,
    'webm' => MimeType::VIDEO__WEBM,
    'wiz' => MimeType::APPLICATION__MSWORD,
    'wk1' => MimeType::APPLICATION__X_123,
    'wm' => MimeType::VIDEO__X_MS_WM,
    'wma' => MimeType::AUDIO__X_MS_WMA,
    'wmd' => MimeType::VIDEO__X_MS_WMD,
    'wmf' => MimeType::WINDOWS__METAFILE,
    'wml' => MimeType::TEXT__VND_WAP_WML,
    'wmlc' => MimeType::APPLICATION__VND_WAP_WMLC,
    'wmls' => MimeType::TEXT__VND_WAP_WMLSCRIPT,
    'wmlsc' => MimeType::APPLICATION__VND_WAP_WMLSCRIPTC,
    'wmv' => MimeType::VIDEO__X_MS_WMV,
    'wmx' => MimeType::VIDEO__X_MS_WMX,
    'wmz' => MimeType::VIDEO__X_MS_WMZ,
    'woff' => MimeType::APPLICATION__FONT_WOFF,
    'word' => MimeType::APPLICATION__MSWORD,
    'wp' => MimeType::APPLICATION__WORDPERFECT,
    'wp5' => [
        MimeType::APPLICATION__WORDPERFECT,
        MimeType::APPLICATION__WORDPERFECT6_0,
    ],
    'wp6' => MimeType::APPLICATION__WORDPERFECT,
    'wpd' => [
        MimeType::APPLICATION__WORDPERFECT,
        MimeType::APPLICATION__X_WPWIN,
    ],
    'wq1' => MimeType::APPLICATION__X_LOTUS,
    'wri' => [
        MimeType::APPLICATION__MSWRITE,
        MimeType::APPLICATION__X_WRI,
    ],
    'wrl' => [
        MimeType::APPLICATION__X_WORLD,
        MimeType::MODEL__VRML,
        MimeType::X_WORLD__X_VRML,
    ],
    'wrz' => [
        MimeType::MODEL__VRML,
        MimeType::X_WORLD__X_VRML,
    ],
    'wsc' => MimeType::TEXT__SCRIPLET,
    'wsrc' => MimeType::APPLICATION__X_WAIS_SOURCE,
    'wtk' => MimeType::APPLICATION__X_WINTALK,
    'wvx' => MimeType::VIDEO__X_MS_WVX,
    'x-png' => MimeType::IMAGE__PNG,
    'xbm' => [
        MimeType::IMAGE__X_XBITMAP,
        MimeType::IMAGE__X_XBM,
        MimeType::IMAGE__XBM,
    ],
    'xdr' => MimeType::VIDEO__X_AMT_DEMORUN,
    'xgz' => MimeType::XGL__DRAWING,
    'xhtml' => MimeType::APPLICATION__XHTML_XML,
    'xif' => MimeType::IMAGE__VND_XIFF,
    'xl' => MimeType::APPLICATION__EXCEL,
    'xla' => [
        MimeType::APPLICATION__EXCEL,
        MimeType::APPLICATION__X_EXCEL,
        MimeType::APPLICATION__X_MSEXCEL,
    ],
    'xlam' => MimeType::APPLICATION__VND_MS_EXCEL_ADDIN_MACRO_ENABLED_12,
    'xlb' => [
        MimeType::APPLICATION__EXCEL,
        MimeType::APPLICATION__VND_MS_EXCEL,
        MimeType::APPLICATION__X_EXCEL,
    ],
    'xlc' => [
        MimeType::APPLICATION__EXCEL,
        MimeType::APPLICATION__VND_MS_EXCEL,
        MimeType::APPLICATION__X_EXCEL,
    ],
    'xld' => [
        MimeType::APPLICATION__EXCEL,
        MimeType::APPLICATION__X_EXCEL,
    ],
    'xlk' => [
        MimeType::APPLICATION__EXCEL,
        MimeType::APPLICATION__X_EXCEL,
    ],
    'xll' => [
        MimeType::APPLICATION__EXCEL,
        MimeType::APPLICATION__VND_MS_EXCEL,
        MimeType::APPLICATION__X_EXCEL,
    ],
    'xlm' => [
        MimeType::APPLICATION__EXCEL,
        MimeType::APPLICATION__VND_MS_EXCEL,
        MimeType::APPLICATION__X_EXCEL,
    ],
    'xls' => [
        MimeType::APPLICATION__EXCEL,
        MimeType::APPLICATION__VND_MS_EXCEL,
        MimeType::APPLICATION__X_EXCEL,
        MimeType::APPLICATION__X_MSEXCEL,
    ],
    'xlsb' => MimeType::APPLICATION__VND_MS_EXCEL_SHEET_BINARY_MACRO_ENABLED_12,
    'xlsx' => MimeType::APPLICATION__VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_SHEET,
    'xlt' => [
        MimeType::APPLICATION__EXCEL,
        MimeType::APPLICATION__X_EXCEL,
    ],
    'xltx' => MimeType::APPLICATION__VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_TEMPLATE,
    'xlv' => [
        MimeType::APPLICATION__EXCEL,
        MimeType::APPLICATION__X_EXCEL,
    ],
    'xlw' => [
        MimeType::APPLICATION__EXCEL,
        MimeType::APPLICATION__VND_MS_EXCEL,
        MimeType::APPLICATION__X_EXCEL,
        MimeType::APPLICATION__X_MSEXCEL,
    ],
    'xm' => MimeType::AUDIO__XM,
    'xml' => [
        MimeType::TEXT__XML,
        MimeType::APPLICATION__XML,
    ],
    'xmz' => MimeType::XGL__MOVIE,
    'xpix' => MimeType::APPLICATION__X_VND_LS_XPIX,
    'xpm' => [
        MimeType::IMAGE__XPM,
        MimeType::IMAGE__X_XPIXMAP,
    ],
    'xsl' => MimeType::APPLICATION__XML,
    'xsr' => MimeType::VIDEO__X_AMT_SHOWRUN,
    'xwd' => [
        MimeType::IMAGE__X_XWD,
        MimeType::IMAGE__X_XWINDOWDUMP,
    ],
    'xyz' => MimeType::CHEMICAL__X_PDB,
    'youtube' => MimeType::VIDEO__YOUTUBE,
    'z' => [
        MimeType::APPLICATION__X_COMPRESS,
        MimeType::APPLICATION__X_COMPRESSED,
    ],
    'zip' => [
        MimeType::APPLICATION__ZIP,
        MimeType::APPLICATION__X_COMPRESSED,
        MimeType::APPLICATION__X_ZIP_COMPRESSED,
        MimeType::MULTIPART__X_ZIP,
    ],
    'zoo' => MimeType::APPLICATION__OCTET_STREAM,
    'zsh' => MimeType::TEXT__X_SCRIPT_ZSH,
];
