<?php return array (
  'ILIAS\\GlobalScreen\\Scope\\MainMenu\\Provider\\StaticMainMenuProvider' => 
  array (
    0 => 'ILIAS\\Administration\\AdministrationMainBarProvider',
    1 => 'ILIAS\\Badge\\Provider\\BadgeMainBarProvider',
    2 => 'ILIAS\\Calendar\\Provider\\CalendarMainBarProvider',
    3 => 'ILIAS\\Certificate\\Provider\\CertificateMainBarProvider',
    4 => 'ILIAS\\Contact\\Provider\\ContactMainBarProvider',
    5 => 'ILIAS\\LearningHistory\\LearningHistoryMainBarProvider',
    6 => 'ILIAS\\LearningProgress\\LPMainBarProvider',
    7 => 'ILIAS\\Mail\\Provider\\MailMainBarProvider',
    8 => 'ILIAS\\MainMenu\\Provider\\ChatMainBarProvider',
    9 => 'ILIAS\\MainMenu\\Provider\\CustomMainBarProvider',
    10 => 'ILIAS\\MainMenu\\Provider\\StandardTopItemsProvider',
    11 => 'ILIAS\\MyStaff\\Provider\\StaffMainBarProvider',
    12 => 'ILIAS\\News\\Provider\\NewsMainBarProvider',
    13 => 'ILIAS\\Notes\\Provider\\NotesMainBarProvider',
    14 => 'ILIAS\\PersonalDesktop\\PDMainBarProvider',
    15 => 'ILIAS\\PersonalWorkspace\\Provider\\WorkspaceMainBarProvider',
    16 => 'ILIAS\\Portfolio\\Provider\\PortfolioMainBarProvider',
    17 => 'ILIAS\\Repository\\Provider\\RepositoryMainBarProvider',
    18 => 'ILIAS\\Skill\\Provider\\SkillMainBarProvider',
    19 => 'ILIAS\\Tagging\\Provider\\TaggingMainBarProvider',
    20 => 'ILIAS\\Tasks\\DerivedTasks\\Provider\\DerivedTaskMainBarProvider',
    21 => 'ilPluginGlobalScreenNullProvider',
  ),
  'ILIAS\\GlobalScreen\\Scope\\MetaBar\\Provider\\StaticMetaBarProvider' => 
  array (
    0 => 'ILIAS\\BackgroundTasks\\Provider\\BackgroundTasksMetaBarProvider',
    1 => 'ILIAS\\GlobalScreen\\Provider\\GSMetaBarProvider',
    2 => 'ILIAS\\GlobalScreen\\Scope\\MetaBar\\Provider\\NotificationCenterProvider',
    3 => 'ILIAS\\Search\\Provider\\SearchMetaBarProvider',
    4 => 'ILIAS\\User\\Provider\\UserMetaBarProvider',
    5 => 'ilAwarenessMetaBarProvider',
  ),
  'ILIAS\\GlobalScreen\\Scope\\Tool\\Provider\\DynamicToolProvider' => 
  array (
    0 => 'ForumGlobalScreenToolsProvider',
    1 => 'ILIAS\\Init\\Provider\\InitToolProvider',
    2 => 'ILIAS\\OrgUnit\\Provider\\OrgUnitToolProvider',
    3 => 'MailGlobalScreenToolProvider',
    4 => 'ilAdminGSToolProvider',
    5 => 'ilCOPageEditGSToolProvider',
    6 => 'ilLMEditGSToolProvider',
    7 => 'ilLMGSToolProvider',
    8 => 'ilMediaPoolGSToolProvider',
    9 => 'ilRepositoryGSToolProvider',
    10 => 'ilSAHSEditGSToolProvider',
    11 => 'ilSkillGSToolProvider',
    12 => 'ilTaxonomyGSToolProvider',
    13 => 'ilWorkspaceGSToolProvider',
  ),
  'ILIAS\\GlobalScreen\\Scope\\Layout\\Provider\\ModificationProvider' => 
  array (
    0 => 'ILIAS\\Container\\Screen\\MemberViewLayoutProvider',
    1 => 'ILIAS\\GlobalScreen\\Provider\\GSModificationProvider',
    2 => 'ILIAS\\UICore\\PageContentProvider',
  ),
  'ILIAS\\GlobalScreen\\Scope\\Notification\\Provider\\NotificationProvider' => 
  array (
    0 => 'ILIAS\\BackgroundTasks\\Provider\\BTNotificationProvider',
    1 => 'ILIAS\\Contact\\Provider\\ContactNotificationProvider',
    2 => 'ILIAS\\Mail\\Provider\\MailNotificationProvider',
  ),
);