<?php
/* Copyright (c) 1998-2017 ILIAS open source, Extended GPL, see docs/LICENSE */

require_once 'Services/Xml/classes/class.ilXmlWriter.php';
require_once 'Modules/Chatroom/classes/class.ilChatroom.php';

/**
 * Class ilChatroomXMLWriter
 */
class ilChatroomXMLParser extends ilXmlWriter
{
	/**
	 * @var ilObjChatroom
	 */
	protected $chat;

	/**
	 * @var ilChatroom
	 */
	protected $room;

	/**
	 * ilChatroomXMLWriter constructor.
	 * @param ilObjChatroom $chat
	 */
	public function __construct(ilObjChatroom $chat)
	{
		$this->chat = $chat;

		$this->room = ilChatroom::byObjectId($this->chat->getId());
		if(!$this->room)
		{
			$this->room = new ilChatroom();
			$this->room->setSetting('object_id', $this->chat->getId());
		}

		parent::__construct();
	}

	/**
	 * 
	 */
	public function start()
	{
		$this->xmlStartTag('Chatroom', null);

		$this->xmlElement('ObjId', null, (int)$this->chat->getId());
		$this->xmlElement('Title',  null, $this->chat->getTitle());
		$this->xmlElement('Description',  null, $this->chat->getDescription());
		$this->xmlElement('OnlineStatus',  null, (int)$this->room->getSetting('online_status'));
		$this->xmlElement('AllowAnonymous',  null, (int)$this->room->getSetting('allow_anonymous'));
		$this->xmlElement('AllowCustomUsernames',  null, (int)$this->room->getSetting('allow_custom_usernames'));
		$this->xmlElement('EnableHistory',  null, (int)$this->room->getSetting('enable_history'));
		$this->xmlElement('RestrictHistory',  null, (int)$this->room->getSetting('restrict_history'));
		$this->xmlElement('PrivateRoomsEnabled',  null, (int)$this->room->getSetting('private_rooms_enabled'));
		$this->xmlElement('DisplayPastMessages',  null, (int)$this->room->getSetting('display_past_msgs'));
		$this->xmlElement('AllowPrivateRooms',  null, (int)$this->room->getSetting('allow_private_rooms'));
		$this->xmlElement('AutoGeneratedUsernameSchema',  null, $this->room->getSetting('autogen_usernames'));

		$this->xmlEndTag('Chatroom');
	}

	/**
	 * @return string
	 */
	public function getXML()
	{
		// Replace ascii code 11 characters because of problems with xml sax parser
		return str_replace('&#11;', '', $this->xmlDumpMem(false));
	}
}