<?php return [
    '3dm' => ILIAS\FileUpload\MimeType::X_WORLD__X_3DMF,
    '3dmf' => ILIAS\FileUpload\MimeType::X_WORLD__X_3DMF,
    '3gp' => ILIAS\FileUpload\MimeType::VIDEO__3_GPP,
    'a' => ILIAS\FileUpload\MimeType::APPLICATION__OCTET_STREAM,
    'aab' => ILIAS\FileUpload\MimeType::APPLICATION__X_AUTHORWARE_BIN,
    'aam' => ILIAS\FileUpload\MimeType::APPLICATION__X_AUTHORWARE_MAP,
    'aas' => ILIAS\FileUpload\MimeType::APPLICATION__X_AUTHORWARE_SEG,
    'abc' => ILIAS\FileUpload\MimeType::TEXT__VND_ABC,
    'acgi' => ILIAS\FileUpload\MimeType::TEXT__HTML,
    'afl' => ILIAS\FileUpload\MimeType::VIDEO__ANIMAFLEX,
    'ai' => ILIAS\FileUpload\MimeType::APPLICATION__POSTSCRIPT,
    'aif' => [
        ILIAS\FileUpload\MimeType::AUDIO__X_AIFF,
        ILIAS\FileUpload\MimeType::AUDIO__AIFF,
    ],
    'aifc' => [
        ILIAS\FileUpload\MimeType::AUDIO__X_AIFF,
        ILIAS\FileUpload\MimeType::AUDIO__AIFF,
    ],
    'aiff' => [
        ILIAS\FileUpload\MimeType::AUDIO__X_AIFF,
        ILIAS\FileUpload\MimeType::AUDIO__AIFF,
    ],
    'aim' => ILIAS\FileUpload\MimeType::APPLICATION__X_AIM,
    'aip' => ILIAS\FileUpload\MimeType::TEXT__X_AUDIOSOFT_INTRA,
    'ani' => ILIAS\FileUpload\MimeType::APPLICATION__X_NAVI_ANIMATION,
    'aos' => ILIAS\FileUpload\MimeType::APPLICATION__X_NOKIA_9000_COMMUNICATOR_ADD_ON_SOFTWARE,
    'aps' => ILIAS\FileUpload\MimeType::APPLICATION__MIME,
    'arc' => ILIAS\FileUpload\MimeType::APPLICATION__OCTET_STREAM,
    'arj' => [
        ILIAS\FileUpload\MimeType::APPLICATION__ARJ,
        ILIAS\FileUpload\MimeType::APPLICATION__OCTET_STREAM
    ],
    'art' => ILIAS\FileUpload\MimeType::IMAGE__X_JG,
    'arw' => [
        ILIAS\FileUpload\MimeType::IMAGE__X_SONY_ARW,
        ILIAS\FileUpload\MimeType::IMAGE__ARW,
    ],
    'asd' => ILIAS\FileUpload\MimeType::VIDEO__X_MS_ASF,
    'asf' => ILIAS\FileUpload\MimeType::VIDEO__X_MS_ASF,
    'asm' => ILIAS\FileUpload\MimeType::TEXT__X_ASM,
    'asn' => ILIAS\FileUpload\MimeType::APPLICATION__ASTOUND,
    'asp' => ILIAS\FileUpload\MimeType::TEXT__ASP,
    'asx' => [
        ILIAS\FileUpload\MimeType::VIDEO__X_MS_ASF,
        ILIAS\FileUpload\MimeType::APPLICATION__X_MPLAYER2,
        ILIAS\FileUpload\MimeType::VIDEO__X_MS_ASF_PLUGIN
    ],
    'au' => [
        ILIAS\FileUpload\MimeType::AUDIO__BASIC,
        ILIAS\FileUpload\MimeType::AUDIO__X_AU
    ],
    'avi' => [
        ILIAS\FileUpload\MimeType::VIDEO__X_MSVIDEO,
        ILIAS\FileUpload\MimeType::VIDEO__AVI,
        ILIAS\FileUpload\MimeType::VIDEO__MSVIDEO,
        ILIAS\FileUpload\MimeType::APPLICATION__X_TROFF_MSVIDEO,
    ],
    'avs' => ILIAS\FileUpload\MimeType::VIDEO__AVS_VIDEO,
    'bat' => ILIAS\FileUpload\MimeType::TEXT__PLAIN,
    'bcpio' => ILIAS\FileUpload\MimeType::APPLICATION__X_BCPIO,
    'bin' => [
        ILIAS\FileUpload\MimeType::APPLICATION__MAC_BINARY,
        ILIAS\FileUpload\MimeType::APPLICATION__MACBINARY,
        ILIAS\FileUpload\MimeType::APPLICATION__OCTET_STREAM,
        ILIAS\FileUpload\MimeType::APPLICATION__X_BINARY,
        ILIAS\FileUpload\MimeType::APPLICATION__X_MACBINARY,
    ],
    'bm' => ILIAS\FileUpload\MimeType::IMAGE__BMP,
    'bmp' => [
        ILIAS\FileUpload\MimeType::IMAGE__X_MS_BMP,
        ILIAS\FileUpload\MimeType::IMAGE__BMP,
        ILIAS\FileUpload\MimeType::IMAGE__X_WINDOWS_BMP,
    ],
    'boo' => ILIAS\FileUpload\MimeType::APPLICATION__BOOK,
    'book' => ILIAS\FileUpload\MimeType::APPLICATION__BOOK,
    'boz' => ILIAS\FileUpload\MimeType::APPLICATION__X_BZIP2,
    'bsh' => ILIAS\FileUpload\MimeType::APPLICATION__X_BSH,
    'bz' => ILIAS\FileUpload\MimeType::APPLICATION__X_BZIP,
    'bz2' => ILIAS\FileUpload\MimeType::APPLICATION__X_BZIP2,
    'c' => [
        ILIAS\FileUpload\MimeType::TEXT__PLAIN,
        ILIAS\FileUpload\MimeType::TEXT__X_C,
    ],
    'c++' => ILIAS\FileUpload\MimeType::TEXT__PLAIN,
    'cat' => ILIAS\FileUpload\MimeType::APPLICATION__VND_MS_PKI_SECCAT,
    'cc' => [
        ILIAS\FileUpload\MimeType::TEXT__PLAIN,
        ILIAS\FileUpload\MimeType::TEXT__X_C,
    ],
    'ccad' => ILIAS\FileUpload\MimeType::APPLICATION__CLARISCAD,
    'cco' => ILIAS\FileUpload\MimeType::APPLICATION__X_COCOA,
    'cdf' => [
        ILIAS\FileUpload\MimeType::APPLICATION__X_CDF,
        ILIAS\FileUpload\MimeType::APPLICATION__CDF,
        ILIAS\FileUpload\MimeType::APPLICATION__X_NETCDF,
    ],
    'cer' => [
        ILIAS\FileUpload\MimeType::APPLICATION__PKIX_CERT,
        ILIAS\FileUpload\MimeType::APPLICATION__X_X509_CA_CERT,
    ],
    'cha' => ILIAS\FileUpload\MimeType::APPLICATION__X_CHAT,
    'chat' => ILIAS\FileUpload\MimeType::APPLICATION__X_CHAT,
    'class' => [
        ILIAS\FileUpload\MimeType::APPLICATION__X_JAVA_APPLET,
        ILIAS\FileUpload\MimeType::APPLICATION__JAVA,
        ILIAS\FileUpload\MimeType::APPLICATION__JAVA_BYTE_CODE,
        ILIAS\FileUpload\MimeType::APPLICATION__X_JAVA_CLASS,
    ],
    'com' => [
        ILIAS\FileUpload\MimeType::APPLICATION__OCTET_STREAM,
        ILIAS\FileUpload\MimeType::TEXT__PLAIN,
    ],
    'conf' => ILIAS\FileUpload\MimeType::TEXT__PLAIN,
    'cpio' => ILIAS\FileUpload\MimeType::APPLICATION__X_CPIO,
    'cpp' => ILIAS\FileUpload\MimeType::TEXT__X_C,
    'cpt' => [
        ILIAS\FileUpload\MimeType::APPLICATION__MAC_COMPACTPRO,
        ILIAS\FileUpload\MimeType::APPLICATION__X_COMPACTPRO,
        ILIAS\FileUpload\MimeType::APPLICATION__X_CPT,
    ],
    'crl' => [
        ILIAS\FileUpload\MimeType::APPLICATION__PKCS_CRL,
        ILIAS\FileUpload\MimeType::APPLICATION__PKIX_CRL,
    ],
    'crt' => [
        ILIAS\FileUpload\MimeType::APPLICATION__X_X509_CA_CERT,
        ILIAS\FileUpload\MimeType::APPLICATION__PKIX_CERT,
        ILIAS\FileUpload\MimeType::APPLICATION__X_X509_USER_CERT,
    ],
    'crw' => [
        ILIAS\FileUpload\MimeType::IMAGE__X_CANON_CRW,
        ILIAS\FileUpload\MimeType::IMAGE__CRW,
    ],
    'cr2' => [
        ILIAS\FileUpload\MimeType::IMAGE__X_CANON_CR2,
        ILIAS\FileUpload\MimeType::IMAGE__CR2,
    ],
    'csh' => [
        ILIAS\FileUpload\MimeType::APPLICATION__X_CSH,
        ILIAS\FileUpload\MimeType::TEXT__X_SCRIPT_CSH,
    ],
    'css' => [
        ILIAS\FileUpload\MimeType::TEXT__CSS,
        ILIAS\FileUpload\MimeType::APPLICATION__X_POINTPLUS,
    ],
    'cxx' => ILIAS\FileUpload\MimeType::TEXT__PLAIN,
    'dcr' => ILIAS\FileUpload\MimeType::APPLICATION__X_DIRECTOR,
    'deepv' => ILIAS\FileUpload\MimeType::APPLICATION__X_DEEPV,
    'def' => ILIAS\FileUpload\MimeType::TEXT__PLAIN,
    'der' => ILIAS\FileUpload\MimeType::APPLICATION__X_X509_CA_CERT,
    'dif' => ILIAS\FileUpload\MimeType::VIDEO__X_DV,
    'dir' => ILIAS\FileUpload\MimeType::APPLICATION__X_DIRECTOR,
    'dl' => [
        ILIAS\FileUpload\MimeType::VIDEO__DL,
        ILIAS\FileUpload\MimeType::VIDEO__X_DL,
    ],
    'doc' => ILIAS\FileUpload\MimeType::APPLICATION__MSWORD,
    'docx' => ILIAS\FileUpload\MimeType::APPLICATION__VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_DOCUMENT,
    'dot' => ILIAS\FileUpload\MimeType::APPLICATION__MSWORD,
    'dotx' => ILIAS\FileUpload\MimeType::APPLICATION__VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_TEMPLATE,
    'dp' => ILIAS\FileUpload\MimeType::APPLICATION__COMMONGROUND,
    'dng' => [
        ILIAS\FileUpload\MimeType::IMAGE__X_ADOBE_DNG,
        ILIAS\FileUpload\MimeType::IMAGE__DNG,
    ],
    'drw' => ILIAS\FileUpload\MimeType::APPLICATION__DRAFTING,
    'dump' => ILIAS\FileUpload\MimeType::APPLICATION__OCTET_STREAM,
    'dv' => ILIAS\FileUpload\MimeType::VIDEO__X_DV,
    'dvi' => ILIAS\FileUpload\MimeType::APPLICATION__X_DVI,
    'dwf' => ILIAS\FileUpload\MimeType::MODEL__VND_DWF,
    'dwg' => [
        ILIAS\FileUpload\MimeType::APPLICATION__ACAD,
        ILIAS\FileUpload\MimeType::IMAGE__VND_DWG,
        ILIAS\FileUpload\MimeType::IMAGE__X_DWG,
    ],
    'dxf' => [
        ILIAS\FileUpload\MimeType::APPLICATION__DXF,
        ILIAS\FileUpload\MimeType::IMAGE__VND_DWG,
        ILIAS\FileUpload\MimeType::IMAGE__X_DWG,
    ],
    'dxr' => ILIAS\FileUpload\MimeType::APPLICATION__X_DIRECTOR,
    'el' => ILIAS\FileUpload\MimeType::TEXT__X_SCRIPT_ELISP,
    'elc' => ILIAS\FileUpload\MimeType::APPLICATION__X_ELC,
    'env' => ILIAS\FileUpload\MimeType::APPLICATION__X_ENVOY,
    'eps' => ILIAS\FileUpload\MimeType::APPLICATION__POSTSCRIPT,
    'epub' => ILIAS\FileUpload\MimeType::APPLICATION__EPUB,
    'es' => ILIAS\FileUpload\MimeType::APPLICATION__X_ESREHBER,
    'etx' => ILIAS\FileUpload\MimeType::TEXT__X_SETEXT,
    'evy' => [
        ILIAS\FileUpload\MimeType::APPLICATION__ENVOY,
        ILIAS\FileUpload\MimeType::APPLICATION__X_ENVOY,
    ],
    'exe' => ILIAS\FileUpload\MimeType::APPLICATION__OCTET_STREAM,
    'f' => [
        ILIAS\FileUpload\MimeType::TEXT__PLAIN,
        'f' => ILIAS\FileUpload\MimeType::TEXT__X_FORTRAN,
    ],
    'f77' => ILIAS\FileUpload\MimeType::TEXT__X_FORTRAN,
    'f90' => [
        ILIAS\FileUpload\MimeType::TEXT__PLAIN,
        ILIAS\FileUpload\MimeType::TEXT__X_FORTRAN,
    ],
    'fdf' => ILIAS\FileUpload\MimeType::APPLICATION__VND_FDF,
    'fif' => [
        ILIAS\FileUpload\MimeType::APPLICATION__FRACTALS,
        ILIAS\FileUpload\MimeType::IMAGE__FIF,
    ],
    'fli' => [
        ILIAS\FileUpload\MimeType::VIDEO__FLI,
        ILIAS\FileUpload\MimeType::VIDEO__X_FLI,
    ],
    'flo' => ILIAS\FileUpload\MimeType::IMAGE__FLORIAN,
    'flv' => ILIAS\FileUpload\MimeType::VIDEO__X_FLV,
    'flx' => ILIAS\FileUpload\MimeType::TEXT__VND_FMI_FLEXSTOR,
    'fmf' => ILIAS\FileUpload\MimeType::VIDEO__X_ATOMIC3D_FEATURE,
    'for' => [
        ILIAS\FileUpload\MimeType::TEXT__PLAIN,
        ILIAS\FileUpload\MimeType::TEXT__X_FORTRAN,
    ],
    'fpx' => [
        ILIAS\FileUpload\MimeType::IMAGE__VND_FPX,
        ILIAS\FileUpload\MimeType::IMAGE__VND_NET_FPX,
    ],
    'frl' => ILIAS\FileUpload\MimeType::APPLICATION__FREELOADER,
    'funk' => ILIAS\FileUpload\MimeType::AUDIO__MAKE,
    'g' => ILIAS\FileUpload\MimeType::TEXT__PLAIN,
    'g3' => ILIAS\FileUpload\MimeType::IMAGE__G3FAX,
    'gif' => ILIAS\FileUpload\MimeType::IMAGE__GIF,
    'gl' => [
        ILIAS\FileUpload\MimeType::VIDEO__GL,
        ILIAS\FileUpload\MimeType::VIDEO__X_GL,
    ],
    'gsd' => ILIAS\FileUpload\MimeType::AUDIO__X_GSM,
    'gsm' => ILIAS\FileUpload\MimeType::AUDIO__X_GSM,
    'gsp' => ILIAS\FileUpload\MimeType::APPLICATION__X_GSP,
    'gss' => ILIAS\FileUpload\MimeType::APPLICATION__X_GSS,
    'gtar' => ILIAS\FileUpload\MimeType::APPLICATION__X_GTAR,
    'gz' => [
        ILIAS\FileUpload\MimeType::APPLICATION__X_COMPRESSED,
        ILIAS\FileUpload\MimeType::APPLICATION__X_GZIP,
    ],
    'gzip' => [
        ILIAS\FileUpload\MimeType::APPLICATION__X_GZIP,
        ILIAS\FileUpload\MimeType::MULTIPART__X_GZIP,
    ],
    'h' => [
        ILIAS\FileUpload\MimeType::TEXT__PLAIN,
        ILIAS\FileUpload\MimeType::TEXT__X_H,
    ],
    'hdf' => ILIAS\FileUpload\MimeType::APPLICATION__X_HDF,
    'help' => ILIAS\FileUpload\MimeType::APPLICATION__X_HELPFILE,
    'hgl' => ILIAS\FileUpload\MimeType::APPLICATION__VND_HP_HPGL,
    'hh' => [
        ILIAS\FileUpload\MimeType::TEXT__PLAIN,
        ILIAS\FileUpload\MimeType::TEXT__X_H,
    ],
    'hlb' => ILIAS\FileUpload\MimeType::TEXT__X_SCRIPT,
    'hlp' => [
        ILIAS\FileUpload\MimeType::APPLICATION__HLP,
        ILIAS\FileUpload\MimeType::APPLICATION__X_HELPFILE,
        ILIAS\FileUpload\MimeType::APPLICATION__X_WINHELP,
    ],
    'hpg' => ILIAS\FileUpload\MimeType::APPLICATION__VND_HP_HPGL,
    'hpgl' => ILIAS\FileUpload\MimeType::APPLICATION__VND_HP_HPGL,
    'hqx' => [
        ILIAS\FileUpload\MimeType::APPLICATION__BINHEX,
        ILIAS\FileUpload\MimeType::APPLICATION__BINHEX4,
        ILIAS\FileUpload\MimeType::APPLICATION__MAC_BINHEX,
        ILIAS\FileUpload\MimeType::APPLICATION__MAC_BINHEX40,
        ILIAS\FileUpload\MimeType::APPLICATION__X_BINHEX40,
        ILIAS\FileUpload\MimeType::APPLICATION__X_MAC_BINHEX40,
    ],
    'hta' => ILIAS\FileUpload\MimeType::APPLICATION__HTA,
    'htc' => ILIAS\FileUpload\MimeType::TEXT__X_COMPONENT,
    'htm' => ILIAS\FileUpload\MimeType::TEXT__HTML,
    'html' => ILIAS\FileUpload\MimeType::TEXT__HTML,
    'htmls' => ILIAS\FileUpload\MimeType::TEXT__HTML,
    'htt' => ILIAS\FileUpload\MimeType::TEXT__WEBVIEWHTML,
    'htx' => ILIAS\FileUpload\MimeType::TEXT__HTML,
    'ice' => ILIAS\FileUpload\MimeType::X_CONFERENCE__X_COOLTALK,
    'ics' => ILIAS\FileUpload\MimeType::TEXT__CALENDAR,
    'ico' => ILIAS\FileUpload\MimeType::IMAGE__X_ICON,
    'idc' => ILIAS\FileUpload\MimeType::TEXT__PLAIN,
    'ief' => ILIAS\FileUpload\MimeType::IMAGE__IEF,
    'iefs' => ILIAS\FileUpload\MimeType::IMAGE__IEF,
    'iges' => [
        ILIAS\FileUpload\MimeType::APPLICATION__IGES,
        ILIAS\FileUpload\MimeType::MODEL__IGES,
    ],
    'igs' => [
        ILIAS\FileUpload\MimeType::APPLICATION__IGES,
        ILIAS\FileUpload\MimeType::MODEL__IGES,
    ],
    'ima' => ILIAS\FileUpload\MimeType::APPLICATION__X_IMA,
    'imap' => ILIAS\FileUpload\MimeType::APPLICATION__X_HTTPD_IMAP,
    'inf' => ILIAS\FileUpload\MimeType::APPLICATION__INF,
    'ins' => ILIAS\FileUpload\MimeType::APPLICATION__X_INTERNETT_SIGNUP,
    'ip' => ILIAS\FileUpload\MimeType::APPLICATION__X_IP2,
    'isu' => ILIAS\FileUpload\MimeType::VIDEO__X_ISVIDEO,
    'it' => ILIAS\FileUpload\MimeType::AUDIO__IT,
    'iv' => ILIAS\FileUpload\MimeType::APPLICATION__X_INVENTOR,
    'ivr' => ILIAS\FileUpload\MimeType::I_WORLD__I_VRML,
    'ivy' => ILIAS\FileUpload\MimeType::APPLICATION__X_LIVESCREEN,
    'jam' => ILIAS\FileUpload\MimeType::AUDIO__X_JAM,
    'jav' => [
        ILIAS\FileUpload\MimeType::TEXT__PLAIN,
        ILIAS\FileUpload\MimeType::TEXT__X_JAVA_SOURCE,
    ],
    'java' => [
        ILIAS\FileUpload\MimeType::TEXT__PLAIN,
        ILIAS\FileUpload\MimeType::TEXT__X_JAVA_SOURCE,
    ],
    'jcm' => ILIAS\FileUpload\MimeType::APPLICATION__X_JAVA_COMMERCE,
    'jfif' => [
        ILIAS\FileUpload\MimeType::IMAGE__JPEG,
        ILIAS\FileUpload\MimeType::IMAGE__PJPEG,
    ],
    'jfif-tbnl' => ILIAS\FileUpload\MimeType::IMAGE__JPEG,
    'jpe' => [
        ILIAS\FileUpload\MimeType::IMAGE__JPEG,
        ILIAS\FileUpload\MimeType::IMAGE__PJPEG,
    ],
    'jpeg' => [
        ILIAS\FileUpload\MimeType::IMAGE__JPEG,
        ILIAS\FileUpload\MimeType::IMAGE__PJPEG,
    ],
    'jpg' => [
        ILIAS\FileUpload\MimeType::IMAGE__JPEG,
        ILIAS\FileUpload\MimeType::IMAGE__PJPEG,
    ],
    'jps' => ILIAS\FileUpload\MimeType::IMAGE__X_JPS,
    'js' => [
        ILIAS\FileUpload\MimeType::APPLICATION__JAVASCRIPT,
        ILIAS\FileUpload\MimeType::APPLICATION__X_JAVASCRIPT,
        ILIAS\FileUpload\MimeType::APPLICATION__ECMASCRIPT,
        ILIAS\FileUpload\MimeType::TEXT__JAVASCRIPT,
        ILIAS\FileUpload\MimeType::TEXT__ECMASCRIPT,
    ],
    'json' => [
        ILIAS\FileUpload\MimeType::APPLICATION__JSON, // rfc4627
        ILIAS\FileUpload\MimeType::APPLICATION__JAVASCRIPT,
    ],
    'jut' => ILIAS\FileUpload\MimeType::IMAGE__JUTVISION,
    'kar' => [
        ILIAS\FileUpload\MimeType::AUDIO__MIDI,
        ILIAS\FileUpload\MimeType::MUSIC__X_KARAOKE,
    ],
    'ksh' => [
        ILIAS\FileUpload\MimeType::APPLICATION__X_KSH,
        ILIAS\FileUpload\MimeType::TEXT__X_SCRIPT_KSH,
    ],
    'la' => [
        ILIAS\FileUpload\MimeType::AUDIO__NSPAUDIO,
        ILIAS\FileUpload\MimeType::AUDIO__X_NSPAUDIO,
    ],
    'lam' => ILIAS\FileUpload\MimeType::AUDIO__X_LIVEAUDIO,
    'latex' => ILIAS\FileUpload\MimeType::APPLICATION__X_LATEX,
    'lha' => [
        ILIAS\FileUpload\MimeType::APPLICATION__LHA,
        ILIAS\FileUpload\MimeType::APPLICATION__OCTET_STREAM,
        ILIAS\FileUpload\MimeType::APPLICATION__X_LHA,
    ],
    'lhx' => ILIAS\FileUpload\MimeType::APPLICATION__OCTET_STREAM,
    'list' => ILIAS\FileUpload\MimeType::TEXT__PLAIN,
    'lma' => [
        ILIAS\FileUpload\MimeType::AUDIO__NSPAUDIO,
        ILIAS\FileUpload\MimeType::AUDIO__X_NSPAUDIO,
    ],
    'log' => ILIAS\FileUpload\MimeType::TEXT__PLAIN,
    'lsp' => [
        ILIAS\FileUpload\MimeType::APPLICATION__X_LISP,
        ILIAS\FileUpload\MimeType::TEXT__X_SCRIPT_LISP,
    ],
    'lst' => ILIAS\FileUpload\MimeType::TEXT__PLAIN,
    'lsx' => ILIAS\FileUpload\MimeType::TEXT__X_LA_ASF,
    'ltx' => ILIAS\FileUpload\MimeType::APPLICATION__X_LATEX,
    'lzh' => [
        ILIAS\FileUpload\MimeType::APPLICATION__OCTET_STREAM,
        ILIAS\FileUpload\MimeType::APPLICATION__X_LZH,
    ],
    'lzx' => [
        ILIAS\FileUpload\MimeType::APPLICATION__LZX,
        ILIAS\FileUpload\MimeType::APPLICATION__OCTET_STREAM,
        ILIAS\FileUpload\MimeType::APPLICATION__X_LZX,
    ],
    'm' => [
        ILIAS\FileUpload\MimeType::TEXT__PLAIN,
        ILIAS\FileUpload\MimeType::TEXT__X_M,
    ],
    'm1v' => ILIAS\FileUpload\MimeType::VIDEO__MPEG,
    'm2a' => ILIAS\FileUpload\MimeType::AUDIO__MPEG,
    'm2v' => ILIAS\FileUpload\MimeType::VIDEO__MPEG,
    'm3u' => ILIAS\FileUpload\MimeType::AUDIO__X_MPEQURL,
    'm4a' => ILIAS\FileUpload\MimeType::AUDIO__MP4,
    'm4v' => ILIAS\FileUpload\MimeType::VIDEO__MP4,
    'man' => ILIAS\FileUpload\MimeType::APPLICATION__X_TROFF_MAN,
    'map' => ILIAS\FileUpload\MimeType::APPLICATION__X_NAVIMAP,
    'mar' => ILIAS\FileUpload\MimeType::TEXT__PLAIN,
    'mbd' => ILIAS\FileUpload\MimeType::APPLICATION__MBEDLET,
    'mc$' => ILIAS\FileUpload\MimeType::APPLICATION__X_MAGIC_CAP_PACKAGE_1_0,
    'mcd' => [
        ILIAS\FileUpload\MimeType::APPLICATION__MCAD,
        ILIAS\FileUpload\MimeType::APPLICATION__X_MATHCAD,
    ],
    'mcf' => [
        ILIAS\FileUpload\MimeType::IMAGE__VASA,
        ILIAS\FileUpload\MimeType::TEXT__MCF,
    ],
    'mcp' => ILIAS\FileUpload\MimeType::APPLICATION__NETMC,
    'me' => ILIAS\FileUpload\MimeType::APPLICATION__X_TROFF_ME,
    'mht' => ILIAS\FileUpload\MimeType::MESSAGE__RFC822,
    'mhtml' => ILIAS\FileUpload\MimeType::MESSAGE__RFC822,
    'md' => ILIAS\FileUpload\MimeType::TEXT__MARKDOWN,
    'mid' => [
        ILIAS\FileUpload\MimeType::AUDIO__MIDI,
        ILIAS\FileUpload\MimeType::APPLICATION__X_MIDI,
        ILIAS\FileUpload\MimeType::AUDIO__X_MID,
        ILIAS\FileUpload\MimeType::AUDIO__X_MIDI,
        ILIAS\FileUpload\MimeType::MUSIC__CRESCENDO,
        ILIAS\FileUpload\MimeType::X_MUSIC__X_MIDI,
    ],
    'midi' => [
        ILIAS\FileUpload\MimeType::AUDIO__MIDI,
        ILIAS\FileUpload\MimeType::APPLICATION__X_MIDI,
        ILIAS\FileUpload\MimeType::AUDIO__X_MID,
        ILIAS\FileUpload\MimeType::AUDIO__X_MIDI,
        ILIAS\FileUpload\MimeType::MUSIC__CRESCENDO,
        ILIAS\FileUpload\MimeType::X_MUSIC__X_MIDI,
    ],
    'mif' => [
        ILIAS\FileUpload\MimeType::APPLICATION__X_FRAME,
        ILIAS\FileUpload\MimeType::APPLICATION__X_MIF,
    ],
    'mime' => [
        ILIAS\FileUpload\MimeType::MESSAGE__RFC822,
        ILIAS\FileUpload\MimeType::WWW__MIME,
    ],
    'mjf' => ILIAS\FileUpload\MimeType::AUDIO__X_VND_AUDIOEXPLOSION_MJUICEMEDIAFILE,
    'mjpg' => ILIAS\FileUpload\MimeType::VIDEO__X_MOTION_JPEG,
    'mm' => [
        ILIAS\FileUpload\MimeType::APPLICATION__BASE64,
        ILIAS\FileUpload\MimeType::APPLICATION__X_MEME,
    ],
    'mme' => ILIAS\FileUpload\MimeType::APPLICATION__BASE64,
    'mobi' => ILIAS\FileUpload\MimeType::APPLICATION__X_MOBI,
    'mod' => [
        ILIAS\FileUpload\MimeType::AUDIO__MOD,
        ILIAS\FileUpload\MimeType::AUDIO__X_MOD,
    ],
    'moov' => ILIAS\FileUpload\MimeType::VIDEO__QUICKTIME,
    'mov' => ILIAS\FileUpload\MimeType::VIDEO__QUICKTIME,
    'movie' => ILIAS\FileUpload\MimeType::VIDEO__X_SGI_MOVIE,
    'mp2' => [
        ILIAS\FileUpload\MimeType::AUDIO__MPEG,
        ILIAS\FileUpload\MimeType::AUDIO__X_MPEG,
        ILIAS\FileUpload\MimeType::VIDEO__MPEG,
        ILIAS\FileUpload\MimeType::VIDEO__X_MPEG,
        ILIAS\FileUpload\MimeType::VIDEO__X_MPEQ2A,
    ],
    'mp3' => [
        ILIAS\FileUpload\MimeType::AUDIO__MPEG,
        ILIAS\FileUpload\MimeType::AUDIO__MPEG3,
        ILIAS\FileUpload\MimeType::AUDIO__X_MPEG_3,
        ILIAS\FileUpload\MimeType::VIDEO__MPEG,
        ILIAS\FileUpload\MimeType::VIDEO__X_MPEG,
    ],
    'mp4' => ILIAS\FileUpload\MimeType::VIDEO__MP4,
    'mpa' => [
        ILIAS\FileUpload\MimeType::AUDIO__MPEG,
        ILIAS\FileUpload\MimeType::VIDEO__MPEG,
    ],
    'mpc' => ILIAS\FileUpload\MimeType::APPLICATION__X_PROJECT,
    'mpe' => ILIAS\FileUpload\MimeType::VIDEO__MPEG,
    'mpeg' => ILIAS\FileUpload\MimeType::VIDEO__MPEG,
    'mpg' => [
        ILIAS\FileUpload\MimeType::AUDIO__MPEG,
        ILIAS\FileUpload\MimeType::VIDEO__MPEG,
    ],
    'mpga' => ILIAS\FileUpload\MimeType::AUDIO__MPEG,
    'mpp' => ILIAS\FileUpload\MimeType::APPLICATION__VND_MS_PROJECT,
    'mpt' => ILIAS\FileUpload\MimeType::APPLICATION__X_PROJECT,
    'mpv' => ILIAS\FileUpload\MimeType::APPLICATION__X_PROJECT,
    'mpx' => ILIAS\FileUpload\MimeType::APPLICATION__X_PROJECT,
    'mrc' => ILIAS\FileUpload\MimeType::APPLICATION__MARC,
    'ms' => ILIAS\FileUpload\MimeType::APPLICATION__X_TROFF_MS,
    'mv' => ILIAS\FileUpload\MimeType::VIDEO__X_SGI_MOVIE,
    'mv4' => ILIAS\FileUpload\MimeType::VIDEO__MP4,
    'my' => ILIAS\FileUpload\MimeType::AUDIO__MAKE,
    'mzz' => ILIAS\FileUpload\MimeType::APPLICATION__X_VND_AUDIOEXPLOSION_MZZ,
    'nap' => ILIAS\FileUpload\MimeType::IMAGE__NAPLPS,
    'naplps' => ILIAS\FileUpload\MimeType::IMAGE__NAPLPS,
    'nc' => ILIAS\FileUpload\MimeType::APPLICATION__X_NETCDF,
    'ncm' => ILIAS\FileUpload\MimeType::APPLICATION__VND_NOKIA_CONFIGURATION_MESSAGE,
    'nef' => [
        ILIAS\FileUpload\MimeType::IMAGE__X_NIKON_NEF,
        ILIAS\FileUpload\MimeType::IMAGE__NEF,
    ],
    'nif' => ILIAS\FileUpload\MimeType::IMAGE__X_NIFF,
    'niff' => ILIAS\FileUpload\MimeType::IMAGE__X_NIFF,
    'nix' => ILIAS\FileUpload\MimeType::APPLICATION__X_MIX_TRANSFER,
    'nsc' => ILIAS\FileUpload\MimeType::APPLICATION__X_CONFERENCE,
    'nvd' => ILIAS\FileUpload\MimeType::APPLICATION__X_NAVIDOC,
    'o' => ILIAS\FileUpload\MimeType::APPLICATION__OCTET_STREAM,
    'oda' => ILIAS\FileUpload\MimeType::APPLICATION__ODA,
    'oga' => ILIAS\FileUpload\MimeType::AUDIO__OGG,
    'ogg' => ILIAS\FileUpload\MimeType::AUDIO__OGG,
    'ogv' => ILIAS\FileUpload\MimeType::VIDEO__OGG,
    'ogx' => ILIAS\FileUpload\MimeType::APPLICATION__OGG,
    'omc' => ILIAS\FileUpload\MimeType::APPLICATION__X_OMC,
    'omcd' => ILIAS\FileUpload\MimeType::APPLICATION__X_OMCDATAMAKER,
    'omcr' => ILIAS\FileUpload\MimeType::APPLICATION__X_OMCREGERATOR,
    'p' => ILIAS\FileUpload\MimeType::TEXT__X_PASCAL,
    'p10' => [
        ILIAS\FileUpload\MimeType::APPLICATION__PKCS10,
        ILIAS\FileUpload\MimeType::APPLICATION__X_PKCS10,
    ],
    'p12' => [
        ILIAS\FileUpload\MimeType::APPLICATION__PKCS_12,
        ILIAS\FileUpload\MimeType::APPLICATION__X_PKCS12,
    ],
    'p7a' => ILIAS\FileUpload\MimeType::APPLICATION__X_PKCS7_SIGNATURE,
    'p7c' => [
        ILIAS\FileUpload\MimeType::APPLICATION__PKCS7_MIME,
        ILIAS\FileUpload\MimeType::APPLICATION__X_PKCS7_MIME,
    ],
    'p7m' => [
        ILIAS\FileUpload\MimeType::APPLICATION__PKCS7_MIME,
        ILIAS\FileUpload\MimeType::APPLICATION__X_PKCS7_MIME,
    ],
    'p7r' => ILIAS\FileUpload\MimeType::APPLICATION__X_PKCS7_CERTREQRESP,
    'p7s' => ILIAS\FileUpload\MimeType::APPLICATION__PKCS7_SIGNATURE,
    'part' => ILIAS\FileUpload\MimeType::APPLICATION__PRO_ENG,
    'pas' => ILIAS\FileUpload\MimeType::TEXT__PASCAL,
    'pbm' => ILIAS\FileUpload\MimeType::IMAGE__X_PORTABLE_BITMAP,
    'pcl' => [
        ILIAS\FileUpload\MimeType::APPLICATION__VND_HP_PCL,
        ILIAS\FileUpload\MimeType::APPLICATION__X_PCL,
    ],
    'pct' => ILIAS\FileUpload\MimeType::IMAGE__X_PICT,
    'pcx' => ILIAS\FileUpload\MimeType::IMAGE__X_PCX,
    'pdb' => ILIAS\FileUpload\MimeType::CHEMICAL__X_PDB,
    'pdf' => ILIAS\FileUpload\MimeType::APPLICATION__PDF,
    'pfunk' => [
        ILIAS\FileUpload\MimeType::AUDIO__MAKE,
        ILIAS\FileUpload\MimeType::AUDIO__MAKE_MY_FUNK,
    ],
    'pgm' => [
        ILIAS\FileUpload\MimeType::IMAGE__X_PORTABLE_GRAYMAP,
        ILIAS\FileUpload\MimeType::IMAGE__X_PORTABLE_GREYMAP,
    ],
    'pic' => ILIAS\FileUpload\MimeType::IMAGE__PICT,
    'pict' => ILIAS\FileUpload\MimeType::IMAGE__PICT,
    'pkg' => ILIAS\FileUpload\MimeType::APPLICATION__X_NEWTON_COMPATIBLE_PKG,
    'pko' => ILIAS\FileUpload\MimeType::APPLICATION__VND_MS_PKI_PKO,
    'pl' => [
        ILIAS\FileUpload\MimeType::TEXT__PLAIN,
        ILIAS\FileUpload\MimeType::TEXT__X_SCRIPT_PERL,
    ],
    'plx' => ILIAS\FileUpload\MimeType::APPLICATION__X_PIXCLSCRIPT,
    'pm' => [
        ILIAS\FileUpload\MimeType::IMAGE__X_XPIXMAP,
        ILIAS\FileUpload\MimeType::TEXT__X_SCRIPT_PERL_MODULE,
    ],
    'pm4' => ILIAS\FileUpload\MimeType::APPLICATION__X_PAGEMAKER,
    'pm5' => ILIAS\FileUpload\MimeType::APPLICATION__X_PAGEMAKER,
    'png' => ILIAS\FileUpload\MimeType::IMAGE__PNG,
    'pnm' => [
        ILIAS\FileUpload\MimeType::APPLICATION__X_PORTABLE_ANYMAP,
        ILIAS\FileUpload\MimeType::IMAGE__X_PORTABLE_ANYMAP,
    ],
    'pot' => [
        ILIAS\FileUpload\MimeType::APPLICATION__MSPOWERPOINT,
        ILIAS\FileUpload\MimeType::APPLICATION__VND_MS_POWERPOINT,
    ],
    'potx' => ILIAS\FileUpload\MimeType::APPLICATION__VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_TEMPLATE,
    'pov' => ILIAS\FileUpload\MimeType::MODEL__X_POV,
    'ppa' => ILIAS\FileUpload\MimeType::APPLICATION__VND_MS_POWERPOINT,
    'ppm' => ILIAS\FileUpload\MimeType::IMAGE__X_PORTABLE_PIXMAP,
    'pps' => [
        ILIAS\FileUpload\MimeType::APPLICATION__MSPOWERPOINT,
        ILIAS\FileUpload\MimeType::APPLICATION__VND_MS_POWERPOINT,
    ],
    'ppsx' => ILIAS\FileUpload\MimeType::APPLICATION__VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_SLIDESHOW,
    'ppt' => [
        ILIAS\FileUpload\MimeType::APPLICATION__MSPOWERPOINT,
        ILIAS\FileUpload\MimeType::APPLICATION__POWERPOINT,
        ILIAS\FileUpload\MimeType::APPLICATION__VND_MS_POWERPOINT,
        ILIAS\FileUpload\MimeType::APPLICATION__X_MSPOWERPOINT,
    ],
    'pptx' => ILIAS\FileUpload\MimeType::APPLICATION__VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_PRESENTATION,
    'ppz' => ILIAS\FileUpload\MimeType::APPLICATION__MSPOWERPOINT,
    'pre' => ILIAS\FileUpload\MimeType::APPLICATION__X_FREELANCE,
    'prt' => ILIAS\FileUpload\MimeType::APPLICATION__PRO_ENG,
    'ps' => ILIAS\FileUpload\MimeType::APPLICATION__POSTSCRIPT,
    'psd' => ILIAS\FileUpload\MimeType::APPLICATION__OCTET_STREAM,
    'pvu' => ILIAS\FileUpload\MimeType::PALEOVU__X_PV,
    'pwz' => ILIAS\FileUpload\MimeType::APPLICATION__VND_MS_POWERPOINT,
    'py' => ILIAS\FileUpload\MimeType::TEXT__X_SCRIPT_PHYTON,
    'pyc' => ILIAS\FileUpload\MimeType::APPLICATION__X_BYTECODE_PYTHON,
    'qcp' => ILIAS\FileUpload\MimeType::AUDIO__VND_QCELP,
    'qd3' => ILIAS\FileUpload\MimeType::X_WORLD__X_3DMF,
    'qd3d' => ILIAS\FileUpload\MimeType::X_WORLD__X_3DMF,
    'qif' => ILIAS\FileUpload\MimeType::IMAGE__X_QUICKTIME,
    'qt' => ILIAS\FileUpload\MimeType::VIDEO__QUICKTIME,
    'qtc' => ILIAS\FileUpload\MimeType::VIDEO__X_QTC,
    'qti' => ILIAS\FileUpload\MimeType::IMAGE__X_QUICKTIME,
    'qtif' => ILIAS\FileUpload\MimeType::IMAGE__X_QUICKTIME,
    'ra' => [
        ILIAS\FileUpload\MimeType::AUDIO__X_PN_REALAUDIO,
        ILIAS\FileUpload\MimeType::AUDIO__X_PN_REALAUDIO_PLUGIN,
        ILIAS\FileUpload\MimeType::AUDIO__X_REALAUDIO,
    ],
    'ram' => ILIAS\FileUpload\MimeType::AUDIO__X_PN_REALAUDIO,
    'ras' => [
        ILIAS\FileUpload\MimeType::APPLICATION__X_CMU_RASTER,
        ILIAS\FileUpload\MimeType::IMAGE__CMU_RASTER,
        ILIAS\FileUpload\MimeType::IMAGE__X_CMU_RASTER,
    ],
    'rast' => ILIAS\FileUpload\MimeType::IMAGE__CMU_RASTER,
    'rexx' => ILIAS\FileUpload\MimeType::TEXT__X_SCRIPT_REXX,
    'rf' => ILIAS\FileUpload\MimeType::IMAGE__VND_RN_REALFLASH,
    'rgb' => ILIAS\FileUpload\MimeType::IMAGE__X_RGB,
    'rm' => [
        ILIAS\FileUpload\MimeType::APPLICATION__VND_RN_REALMEDIA,
        ILIAS\FileUpload\MimeType::AUDIO__X_PN_REALAUDIO,
    ],
    'rmi' => ILIAS\FileUpload\MimeType::AUDIO__MID,
    'rmm' => ILIAS\FileUpload\MimeType::AUDIO__X_PN_REALAUDIO,
    'rmp' => [
        ILIAS\FileUpload\MimeType::AUDIO__X_PN_REALAUDIO,
        ILIAS\FileUpload\MimeType::AUDIO__X_PN_REALAUDIO_PLUGIN,
    ],
    'rng' => [
        ILIAS\FileUpload\MimeType::APPLICATION__RINGING_TONES,
        ILIAS\FileUpload\MimeType::APPLICATION__VND_NOKIA_RINGING_TONE,
    ],
    'rnx' => ILIAS\FileUpload\MimeType::APPLICATION__VND_RN_REALPLAYER,
    'roff' => ILIAS\FileUpload\MimeType::APPLICATION__X_TROFF,
    'rp' => ILIAS\FileUpload\MimeType::IMAGE__VND_RN_REALPIX,
    'rpm' => ILIAS\FileUpload\MimeType::AUDIO__X_PN_REALAUDIO_PLUGIN,
    'rt' => [
        ILIAS\FileUpload\MimeType::TEXT__RICHTEXT,
        ILIAS\FileUpload\MimeType::TEXT__VND_RN_REALTEXT,
    ],
    'rtf' => [
        ILIAS\FileUpload\MimeType::APPLICATION__RTF,
        ILIAS\FileUpload\MimeType::APPLICATION__X_RTF,
        ILIAS\FileUpload\MimeType::TEXT__RICHTEXT,
    ],
    'rtx' => [
        ILIAS\FileUpload\MimeType::APPLICATION__RTF,
        ILIAS\FileUpload\MimeType::TEXT__RICHTEXT,
    ],
    'rv' => ILIAS\FileUpload\MimeType::VIDEO__VND_RN_REALVIDEO,
    's' => ILIAS\FileUpload\MimeType::TEXT__X_ASM,
    's3m' => ILIAS\FileUpload\MimeType::AUDIO__S3M,
    'saveme' => ILIAS\FileUpload\MimeType::APPLICATION__OCTET_STREAM,
    'sbk' => ILIAS\FileUpload\MimeType::APPLICATION__X_TBOOK,
    'scm' => [
        ILIAS\FileUpload\MimeType::APPLICATION__X_LOTUSSCREENCAM,
        ILIAS\FileUpload\MimeType::TEXT__X_SCRIPT_GUILE,
        ILIAS\FileUpload\MimeType::TEXT__X_SCRIPT_SCHEME,
        ILIAS\FileUpload\MimeType::VIDEO__X_SCM,
    ],
    'sdml' => ILIAS\FileUpload\MimeType::TEXT__PLAIN,
    'sdp' => [
        ILIAS\FileUpload\MimeType::APPLICATION__SDP,
        ILIAS\FileUpload\MimeType::APPLICATION__X_SDP,
    ],
    'sdr' => ILIAS\FileUpload\MimeType::APPLICATION__SOUNDER,
    'seb' => ILIAS\FileUpload\MimeType::APPLICATION__SEB,
    'sea' => [
        ILIAS\FileUpload\MimeType::APPLICATION__SEA,
        ILIAS\FileUpload\MimeType::APPLICATION__X_SEA,
    ],
    'set' => ILIAS\FileUpload\MimeType::APPLICATION__SET,
    'sgm' => [
        ILIAS\FileUpload\MimeType::TEXT__SGML,
        ILIAS\FileUpload\MimeType::TEXT__X_SGML,
    ],
    'sgml' => [
        ILIAS\FileUpload\MimeType::TEXT__SGML,
        ILIAS\FileUpload\MimeType::TEXT__X_SGML,
    ],
    'sh' => [
        ILIAS\FileUpload\MimeType::APPLICATION__X_BSH,
        ILIAS\FileUpload\MimeType::APPLICATION__X_SH,
        ILIAS\FileUpload\MimeType::APPLICATION__X_SHAR,
        ILIAS\FileUpload\MimeType::TEXT__X_SCRIPT_SH,
    ],
    'shar' => [
        ILIAS\FileUpload\MimeType::APPLICATION__X_BSH,
        ILIAS\FileUpload\MimeType::APPLICATION__X_SHAR,
    ],
    'shtml' => [
        ILIAS\FileUpload\MimeType::TEXT__HTML,
        ILIAS\FileUpload\MimeType::TEXT__X_SERVER_PARSED_HTML,
    ],
    'sid' => ILIAS\FileUpload\MimeType::AUDIO__X_PSID,
    'sit' => [
        ILIAS\FileUpload\MimeType::APPLICATION__X_SIT,
        ILIAS\FileUpload\MimeType::APPLICATION__X_STUFFIT,
    ],
    'skd' => ILIAS\FileUpload\MimeType::APPLICATION__X_KOAN,
    'skm' => ILIAS\FileUpload\MimeType::APPLICATION__X_KOAN,
    'skp' => ILIAS\FileUpload\MimeType::APPLICATION__X_KOAN,
    'skt' => ILIAS\FileUpload\MimeType::APPLICATION__X_KOAN,
    'sl' => ILIAS\FileUpload\MimeType::APPLICATION__X_SEELOGO,
    'sldx' => ILIAS\FileUpload\MimeType::APPLICATION__VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_SLIDE,
    'smi' => ILIAS\FileUpload\MimeType::APPLICATION__SMIL,
    'smil' => ILIAS\FileUpload\MimeType::APPLICATION__SMIL,
    'snd' => [
        ILIAS\FileUpload\MimeType::AUDIO__BASIC,
        ILIAS\FileUpload\MimeType::AUDIO__X_ADPCM,
    ],
    'sol' => ILIAS\FileUpload\MimeType::APPLICATION__SOLIDS,
    'spc' => [
        ILIAS\FileUpload\MimeType::APPLICATION__X_PKCS7_CERTIFICATES,
        ILIAS\FileUpload\MimeType::TEXT__X_SPEECH,
    ],
    'spl' => ILIAS\FileUpload\MimeType::APPLICATION__FUTURESPLASH,
    'spr' => ILIAS\FileUpload\MimeType::APPLICATION__X_SPRITE,
    'sprite' => ILIAS\FileUpload\MimeType::APPLICATION__X_SPRITE,
    'src' => ILIAS\FileUpload\MimeType::APPLICATION__X_WAIS_SOURCE,
    'ssi' => ILIAS\FileUpload\MimeType::TEXT__X_SERVER_PARSED_HTML,
    'ssm' => ILIAS\FileUpload\MimeType::APPLICATION__STREAMINGMEDIA,
    'sst' => ILIAS\FileUpload\MimeType::APPLICATION__VND_MS_PKI_CERTSTORE,
    'step' => ILIAS\FileUpload\MimeType::APPLICATION__STEP,
    'stl' => [
        ILIAS\FileUpload\MimeType::APPLICATION__SLA,
        ILIAS\FileUpload\MimeType::APPLICATION__VND_MS_PKI_STL,
        ILIAS\FileUpload\MimeType::APPLICATION__X_NAVISTYLE,
    ],
    'stp' => ILIAS\FileUpload\MimeType::APPLICATION__STEP,
    'sv4cpio' => ILIAS\FileUpload\MimeType::APPLICATION__X_SV4CPIO,
    'sv4crc' => ILIAS\FileUpload\MimeType::APPLICATION__X_SV4CRC,
    'svf' => [
        ILIAS\FileUpload\MimeType::IMAGE__VND_DWG,
        ILIAS\FileUpload\MimeType::IMAGE__X_DWG,
    ],
    'svg' => ILIAS\FileUpload\MimeType::IMAGE__SVG_XML,
    'svr' => [
        ILIAS\FileUpload\MimeType::APPLICATION__X_WORLD,
        ILIAS\FileUpload\MimeType::X_WORLD__X_SVR,
    ],
    'swf' => ILIAS\FileUpload\MimeType::APPLICATION__X_SHOCKWAVE_FLASH,
    't' => ILIAS\FileUpload\MimeType::APPLICATION__X_TROFF,
    'talk' => ILIAS\FileUpload\MimeType::TEXT__X_SPEECH,
    'tar' => ILIAS\FileUpload\MimeType::APPLICATION__X_TAR,
    'tbk' => [
        ILIAS\FileUpload\MimeType::APPLICATION__TOOLBOOK,
        ILIAS\FileUpload\MimeType::APPLICATION__X_TBOOK,
    ],
    'tcl' => [
        ILIAS\FileUpload\MimeType::APPLICATION__X_TCL,
        ILIAS\FileUpload\MimeType::TEXT__X_SCRIPT_TCL,
    ],
    'tcsh' => ILIAS\FileUpload\MimeType::TEXT__X_SCRIPT_TCSH,
    'tex' => ILIAS\FileUpload\MimeType::APPLICATION__X_TEX,
    'texi' => ILIAS\FileUpload\MimeType::APPLICATION__X_TEXINFO,
    'texinfo' => ILIAS\FileUpload\MimeType::APPLICATION__X_TEXINFO,
    'text' => [
        ILIAS\FileUpload\MimeType::TEXT__PLAIN,
        ILIAS\FileUpload\MimeType::APPLICATION__PLAIN,
    ],
    'tgz' => [
        ILIAS\FileUpload\MimeType::APPLICATION__GNUTAR,
        ILIAS\FileUpload\MimeType::APPLICATION__X_COMPRESSED,
    ],
    'tif' => [
        ILIAS\FileUpload\MimeType::IMAGE__TIFF,
        ILIAS\FileUpload\MimeType::IMAGE__X_TIFF,
    ],
    'tiff' => [
        ILIAS\FileUpload\MimeType::IMAGE__TIFF,
        ILIAS\FileUpload\MimeType::IMAGE__X_TIFF,
    ],
    'tr' => ILIAS\FileUpload\MimeType::APPLICATION__X_TROFF,
    'tsi' => ILIAS\FileUpload\MimeType::AUDIO__TSP_AUDIO,
    'tsp' => [
        ILIAS\FileUpload\MimeType::APPLICATION__DSPTYPE,
        ILIAS\FileUpload\MimeType::AUDIO__TSPLAYER,
    ],
    'tsv' => ILIAS\FileUpload\MimeType::TEXT__TAB_SEPARATED_VALUES,
    'turbot' => ILIAS\FileUpload\MimeType::IMAGE__FLORIAN,
    'txt' => ILIAS\FileUpload\MimeType::TEXT__PLAIN,
    'uil' => ILIAS\FileUpload\MimeType::TEXT__X_UIL,
    'uni' => ILIAS\FileUpload\MimeType::TEXT__URI_LIST,
    'unis' => ILIAS\FileUpload\MimeType::TEXT__URI_LIST,
    'unv' => ILIAS\FileUpload\MimeType::APPLICATION__I_DEAS,
    'uri' => ILIAS\FileUpload\MimeType::TEXT__URI_LIST,
    'uris' => ILIAS\FileUpload\MimeType::TEXT__URI_LIST,
    'ustar' => [
        ILIAS\FileUpload\MimeType::APPLICATION__X_USTAR,
        ILIAS\FileUpload\MimeType::MULTIPART__X_USTAR,
    ],
    'uu' => [
        ILIAS\FileUpload\MimeType::APPLICATION__OCTET_STREAM,
        ILIAS\FileUpload\MimeType::TEXT__X_UUENCODE,
    ],
    'uue' => ILIAS\FileUpload\MimeType::TEXT__X_UUENCODE,
    'vcd' => ILIAS\FileUpload\MimeType::APPLICATION__X_CDLINK,
    'vcs' => ILIAS\FileUpload\MimeType::TEXT__X_VCALENDAR,
    'vda' => ILIAS\FileUpload\MimeType::APPLICATION__VDA,
    'vdo' => ILIAS\FileUpload\MimeType::VIDEO__VDO,
    'vew' => ILIAS\FileUpload\MimeType::APPLICATION__GROUPWISE,
    'vimeo' => ILIAS\FileUpload\MimeType::VIDEO__VIMEO,
    'viv' => [
        ILIAS\FileUpload\MimeType::VIDEO__VIVO,
        ILIAS\FileUpload\MimeType::VIDEO__VND_VIVO,
    ],
    'vivo' => [
        ILIAS\FileUpload\MimeType::VIDEO__VIVO,
        ILIAS\FileUpload\MimeType::VIDEO__VND_VIVO,
    ],
    'vmd' => ILIAS\FileUpload\MimeType::APPLICATION__VOCALTEC_MEDIA_DESC,
    'vmf' => ILIAS\FileUpload\MimeType::APPLICATION__VOCALTEC_MEDIA_FILE,
    'voc' => [
        ILIAS\FileUpload\MimeType::AUDIO__VOC,
        ILIAS\FileUpload\MimeType::AUDIO__X_VOC,
    ],
    'vos' => ILIAS\FileUpload\MimeType::VIDEO__VOSAIC,
    'vox' => ILIAS\FileUpload\MimeType::AUDIO__VOXWARE,
    'vqe' => ILIAS\FileUpload\MimeType::AUDIO__X_TWINVQ_PLUGIN,
    'vqf' => ILIAS\FileUpload\MimeType::AUDIO__X_TWINVQ,
    'vql' => ILIAS\FileUpload\MimeType::AUDIO__X_TWINVQ_PLUGIN,
    'vrml' => [
        ILIAS\FileUpload\MimeType::APPLICATION__X_VRML,
        ILIAS\FileUpload\MimeType::MODEL__VRML,
        ILIAS\FileUpload\MimeType::X_WORLD__X_VRML,
    ],
    'vrt' => ILIAS\FileUpload\MimeType::X_WORLD__X_VRT,
    'vsd' => ILIAS\FileUpload\MimeType::APPLICATION__X_VISIO,
    'vst' => ILIAS\FileUpload\MimeType::APPLICATION__X_VISIO,
    'vsw' => ILIAS\FileUpload\MimeType::APPLICATION__X_VISIO,
    'vtt' => ILIAS\FileUpload\MimeType::TEXT__VTT,
    'w60' => ILIAS\FileUpload\MimeType::APPLICATION__WORDPERFECT6_0,
    'w61' => ILIAS\FileUpload\MimeType::APPLICATION__WORDPERFECT6_1,
    'w6w' => ILIAS\FileUpload\MimeType::APPLICATION__MSWORD,
    'wav' => [
        ILIAS\FileUpload\MimeType::AUDIO__X_WAV,
        ILIAS\FileUpload\MimeType::AUDIO__WAV,
    ],
    'wb1' => ILIAS\FileUpload\MimeType::APPLICATION__X_QPRO,
    'wbmp' => ILIAS\FileUpload\MimeType::IMAGE__VND_WAP_WBMP,
    'web' => ILIAS\FileUpload\MimeType::APPLICATION__VND_XARA,
    'webm' => ILIAS\FileUpload\MimeType::VIDEO__WEBM,
    'wiz' => ILIAS\FileUpload\MimeType::APPLICATION__MSWORD,
    'wk1' => ILIAS\FileUpload\MimeType::APPLICATION__X_123,
    'wm' => ILIAS\FileUpload\MimeType::VIDEO__X_MS_WM,
    'wma' => ILIAS\FileUpload\MimeType::AUDIO__X_MS_WMA,
    'wmd' => ILIAS\FileUpload\MimeType::VIDEO__X_MS_WMD,
    'wmf' => ILIAS\FileUpload\MimeType::WINDOWS__METAFILE,
    'wml' => ILIAS\FileUpload\MimeType::TEXT__VND_WAP_WML,
    'wmlc' => ILIAS\FileUpload\MimeType::APPLICATION__VND_WAP_WMLC,
    'wmls' => ILIAS\FileUpload\MimeType::TEXT__VND_WAP_WMLSCRIPT,
    'wmlsc' => ILIAS\FileUpload\MimeType::APPLICATION__VND_WAP_WMLSCRIPTC,
    'wmv' => ILIAS\FileUpload\MimeType::VIDEO__X_MS_WMV,
    'wmx' => ILIAS\FileUpload\MimeType::VIDEO__X_MS_WMX,
    'wmz' => ILIAS\FileUpload\MimeType::VIDEO__X_MS_WMZ,
    'woff' => ILIAS\FileUpload\MimeType::APPLICATION__FONT_WOFF,
    'word' => ILIAS\FileUpload\MimeType::APPLICATION__MSWORD,
    'wp' => ILIAS\FileUpload\MimeType::APPLICATION__WORDPERFECT,
    'wp5' => [
        ILIAS\FileUpload\MimeType::APPLICATION__WORDPERFECT,
        ILIAS\FileUpload\MimeType::APPLICATION__WORDPERFECT6_0,
    ],
    'wp6' => ILIAS\FileUpload\MimeType::APPLICATION__WORDPERFECT,
    'wpd' => [
        ILIAS\FileUpload\MimeType::APPLICATION__WORDPERFECT,
        ILIAS\FileUpload\MimeType::APPLICATION__X_WPWIN,
    ],
    'wq1' => ILIAS\FileUpload\MimeType::APPLICATION__X_LOTUS,
    'wri' => [
        ILIAS\FileUpload\MimeType::APPLICATION__MSWRITE,
        ILIAS\FileUpload\MimeType::APPLICATION__X_WRI,
    ],
    'wrl' => [
        ILIAS\FileUpload\MimeType::APPLICATION__X_WORLD,
        ILIAS\FileUpload\MimeType::MODEL__VRML,
        ILIAS\FileUpload\MimeType::X_WORLD__X_VRML,
    ],
    'wrz' => [
        ILIAS\FileUpload\MimeType::MODEL__VRML,
        ILIAS\FileUpload\MimeType::X_WORLD__X_VRML,
    ],
    'wsc' => ILIAS\FileUpload\MimeType::TEXT__SCRIPLET,
    'wsrc' => ILIAS\FileUpload\MimeType::APPLICATION__X_WAIS_SOURCE,
    'wtk' => ILIAS\FileUpload\MimeType::APPLICATION__X_WINTALK,
    'wvx' => ILIAS\FileUpload\MimeType::VIDEO__X_MS_WVX,
    'x-png' => ILIAS\FileUpload\MimeType::IMAGE__PNG,
    'xbm' => [
        ILIAS\FileUpload\MimeType::IMAGE__X_XBITMAP,
        ILIAS\FileUpload\MimeType::IMAGE__X_XBM,
        ILIAS\FileUpload\MimeType::IMAGE__XBM,
    ],
    'xdr' => ILIAS\FileUpload\MimeType::VIDEO__X_AMT_DEMORUN,
    'xgz' => ILIAS\FileUpload\MimeType::XGL__DRAWING,
    'xhtml' => ILIAS\FileUpload\MimeType::APPLICATION__XHTML_XML,
    'xif' => ILIAS\FileUpload\MimeType::IMAGE__VND_XIFF,
    'xl' => ILIAS\FileUpload\MimeType::APPLICATION__EXCEL,
    'xla' => [
        ILIAS\FileUpload\MimeType::APPLICATION__EXCEL,
        ILIAS\FileUpload\MimeType::APPLICATION__X_EXCEL,
        ILIAS\FileUpload\MimeType::APPLICATION__X_MSEXCEL,
    ],
    'xlam' => ILIAS\FileUpload\MimeType::APPLICATION__VND_MS_EXCEL_ADDIN_MACRO_ENABLED_12,
    'xlb' => [
        ILIAS\FileUpload\MimeType::APPLICATION__EXCEL,
        ILIAS\FileUpload\MimeType::APPLICATION__VND_MS_EXCEL,
        ILIAS\FileUpload\MimeType::APPLICATION__X_EXCEL,
    ],
    'xlc' => [
        ILIAS\FileUpload\MimeType::APPLICATION__EXCEL,
        ILIAS\FileUpload\MimeType::APPLICATION__VND_MS_EXCEL,
        ILIAS\FileUpload\MimeType::APPLICATION__X_EXCEL,
    ],
    'xld' => [
        ILIAS\FileUpload\MimeType::APPLICATION__EXCEL,
        ILIAS\FileUpload\MimeType::APPLICATION__X_EXCEL,
    ],
    'xlk' => [
        ILIAS\FileUpload\MimeType::APPLICATION__EXCEL,
        ILIAS\FileUpload\MimeType::APPLICATION__X_EXCEL,
    ],
    'xll' => [
        ILIAS\FileUpload\MimeType::APPLICATION__EXCEL,
        ILIAS\FileUpload\MimeType::APPLICATION__VND_MS_EXCEL,
        ILIAS\FileUpload\MimeType::APPLICATION__X_EXCEL,
    ],
    'xlm' => [
        ILIAS\FileUpload\MimeType::APPLICATION__EXCEL,
        ILIAS\FileUpload\MimeType::APPLICATION__VND_MS_EXCEL,
        ILIAS\FileUpload\MimeType::APPLICATION__X_EXCEL,
    ],
    'xls' => [
        ILIAS\FileUpload\MimeType::APPLICATION__EXCEL,
        ILIAS\FileUpload\MimeType::APPLICATION__VND_MS_EXCEL,
        ILIAS\FileUpload\MimeType::APPLICATION__X_EXCEL,
        ILIAS\FileUpload\MimeType::APPLICATION__X_MSEXCEL,
    ],
    'xlsb' => ILIAS\FileUpload\MimeType::APPLICATION__VND_MS_EXCEL_SHEET_BINARY_MACRO_ENABLED_12,
    'xlsx' => ILIAS\FileUpload\MimeType::APPLICATION__VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_SHEET,
    'xlt' => [
        ILIAS\FileUpload\MimeType::APPLICATION__EXCEL,
        ILIAS\FileUpload\MimeType::APPLICATION__X_EXCEL,
    ],
    'xltx' => ILIAS\FileUpload\MimeType::APPLICATION__VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_TEMPLATE,
    'xlv' => [
        ILIAS\FileUpload\MimeType::APPLICATION__EXCEL,
        ILIAS\FileUpload\MimeType::APPLICATION__X_EXCEL,
    ],
    'xlw' => [
        ILIAS\FileUpload\MimeType::APPLICATION__EXCEL,
        ILIAS\FileUpload\MimeType::APPLICATION__VND_MS_EXCEL,
        ILIAS\FileUpload\MimeType::APPLICATION__X_EXCEL,
        ILIAS\FileUpload\MimeType::APPLICATION__X_MSEXCEL,
    ],
    'xm' => ILIAS\FileUpload\MimeType::AUDIO__XM,
    'xml' => [
        ILIAS\FileUpload\MimeType::TEXT__XML,
        ILIAS\FileUpload\MimeType::APPLICATION__XML,
    ],
    'xmz' => ILIAS\FileUpload\MimeType::XGL__MOVIE,
    'xpix' => ILIAS\FileUpload\MimeType::APPLICATION__X_VND_LS_XPIX,
    'xpm' => [
        ILIAS\FileUpload\MimeType::IMAGE__XPM,
        ILIAS\FileUpload\MimeType::IMAGE__X_XPIXMAP,
    ],
    'xsl' => ILIAS\FileUpload\MimeType::APPLICATION__XML,
    'xsr' => ILIAS\FileUpload\MimeType::VIDEO__X_AMT_SHOWRUN,
    'xwd' => [
        ILIAS\FileUpload\MimeType::IMAGE__X_XWD,
        ILIAS\FileUpload\MimeType::IMAGE__X_XWINDOWDUMP,
    ],
    'xyz' => ILIAS\FileUpload\MimeType::CHEMICAL__X_PDB,
    'youtube' => ILIAS\FileUpload\MimeType::VIDEO__YOUTUBE,
    'z' => [
        ILIAS\FileUpload\MimeType::APPLICATION__X_COMPRESS,
        ILIAS\FileUpload\MimeType::APPLICATION__X_COMPRESSED,
    ],
    'zip' => [
        ILIAS\FileUpload\MimeType::APPLICATION__ZIP,
        ILIAS\FileUpload\MimeType::APPLICATION__X_COMPRESSED,
        ILIAS\FileUpload\MimeType::APPLICATION__X_ZIP_COMPRESSED,
        ILIAS\FileUpload\MimeType::MULTIPART__X_ZIP,
    ],
    'zoo' => ILIAS\FileUpload\MimeType::APPLICATION__OCTET_STREAM,
    'zsh' => ILIAS\FileUpload\MimeType::TEXT__X_SCRIPT_ZSH,
];
