<?php

/* SETTINGS START */

$themeSettings = array(
'bar_background' => '#F6F6F8',
'bar_gradient_start' => '#F6F6F8',
'bar_gradient_center' => '#F2F3F4',
'bar_gradient_end' => '#EEEFF0',
'bar_border' => '#B3BAC7',
'bar_color' => '#333333',
'bar_color_disabled' => '#A7A7A7',
'bar_border_light' => '#E5E5E5',
'bar_font_family' => 'Helvetica, Arial, "lucida grande",tahoma,verdana,arial,sans-serif',
'bar_font_size' => '12px',
'bar_text_background' => '#FFFFFF',
'tab_background' => '#EDEFF4',
'tab_color' => '#111111',
'tab_border' => '#A2A3A5',
'tab_font_family' => 'Helvetica, Arial, "lucida grande",tahoma,verdana,arial,sans-serif',
'tab_font_size' => '12px',
'tab_font_size_small' => '11px',
'tab_color_self' => '#3E454C',
'tab_title_color' => '#FFFFFF',
'tab_title_backgroud_light' => '#E1E2E5',
'tab_title_background' => '#4E6AAB',
'tab_title_gradient_start' => '#4E6AAB',
'tab_title_gradient_center' => '#4966A7',
'tab_title_gradient_end' => '#4B67A8', 
'tab_title_border' => '#2E4588',
'tab_title_font_family' => 'Helvetica, Arial, "lucida grande",tahoma,verdana,arial,sans-serif',
'tab_title_font_size' => '12px',
'tab_title_font_size_large' => '12px',
'tab_title_text_background' => '#3EA9BD',
'tab_sub_background' => '#FFFFFF',
'tab_sub_color' => '#111111',
'tab_border_light' => '#D1D2D4',
'tab_border_lighter' => '#C9D0DA',
'tooltip_background' => '#282828',
'tooltip_color' => '#FFFFFF',
'tooltip_color_light' => '#EEEEEE',
'tooltip_font_family' => 'Helvetica, Arial, "lucida grande",tahoma,verdana,arial,sans-serif',
'tooltip_font_size' => '12px',
'tooltip_break' => '#D3D7DC',
'tab_link_color' => '#288597',
);

/* SETTINGS END */