<?php

/* SETTINGS START */

$themeSettings = array(
'menu_element_hover_color' => '#00A7E9',
'left_header_background' => '#304650',
'left_header_color' => '#FFFFFF',
'left_header_font_family' => '"Lucida Grande",Verdana,Arial,"Bitstream Vera Sans",sans-serif',
'left_header_font_size' => '13px',
'left_header_font_size_small' => '11px',
'left_content_background' => '#FFFFFF',
'left_content_active_color' => '#304650',
'left_content_user_color' => '#304650',
'left_content_color' => '#111111',
'left_content_font_family' => '"Lucida Grande",Verdana,Arial,"Bitstream Vera Sans",sans-serif',
'left_content_border_light' => '#CCCCCC',
'left_content_seperator_color' => '#666666',
'left_content_seperator_hr_background' => '#CCCCCC',
'right_header_background' => '#4BBCE8',
'right_header_color' => '#FFFFFF',
'right_header_active_color' => '#FFFFFF',
'right_header_menu_background' => '#304650',
'right_header_dropdown_color' => '#666666',
'right_header_font_family' => 'Tahoma,Verdana,Arial,"Bitstream Vera Sans",sans-serif',
'right_header_border'=>'#EBEBEB',
'messagecount_background' => '#E85871',
'closebox_background' => '#FF2B33',
'right_content_background' => '#EEEEEE',
'right_content_border' => '#5D5D5D',
'right_content_color' => '#C0C0C0',
'right_content_lem_color' => '#6E6E6E',
'right_content_lem_background' => '#FFFFFF',
'right_content_lem_border' => '#CCCCCC',
'right_content_font_family' => '"Lucida Grande",Verdana,Arial,"Bitstream Vera Sans",sans-serif',
'right_content_font_size' => '13px',
'right_content_font_size_small' => '11px',
'right_content_self_color'=>'#595959',
'right_content_self_link_color'=>'#1C97D0',
'right_content_self_background' => '#FFFFFF',
'right_content_other_color' => '#FFFFFF',
'right_content_other_background' => '#4BBCE8',
'right_content_other_link_color'=>'#FFFFFF',
'right_inputcontainer_background' => '#EEEEEE',
'right_inputcontainer_button_background' => '#4BBCE8',
'right_input_primary_color' => '#4BBCE8',
'right_input_color' => '#111111',
'right_dropdown_popup_background' => '#FFFFFF',
'right_dropdown_popup_color' => '#111111',
'right_dropdown_popup_border'=> '#868686',
'tooltip_background' => '#304650',
'tooltip_color' => '#FFFFFF',
'tooltip_color_light' => '#EEEEEE',
'tooltip_font_family' => '"Lucida Grande",Verdana,Arial,"Bitstream Vera Sans",sans-serif',
'tooltip_font_size' => '11px',
'tooltip_break' => '#666666'
);

/* SETTINGS END */
