<?php
$BEAUT_PATH = realpath(".")."/Services/COPage/syntax_highlight/php";
if (!isset ($BEAUT_PATH)) return;
require_once("$BEAUT_PATH/Beautifier/HFile.php");
  class HFile_asm68hc11 extends HFile{
   function HFile_asm68hc11(){
     $this->HFile();	
/*************************************/
// Beautifier Highlighting Configuration File 
// 68HC11 ASM
/*************************************/
// Flags

$this->nocase            	= "1";
$this->notrim            	= "0";
$this->perl              	= "0";

// Colours

$this->colours        	= array("blue", "purple", "gray", "brown", "blue", "purple");
$this->quotecolour       	= "blue";
$this->blockcommentcolour	= "green";
$this->linecommentcolour 	= "green";

// Indent Strings

$this->indent            	= array();
$this->unindent          	= array();

// String characters and delimiters

$this->stringchars       	= array();
$this->delimiters        	= array("~", "!", "@", "^", "&", "(", ")", "-", "+", "=", "|", "\\", "/", "{", "}", "[", "]", ":", "'", "\"", "<", ">", " ", ",", " ", ".", "?");
$this->escchar           	= "";

// Comment settings

$this->linecommenton     	= array(";");
$this->blockcommenton    	= array("");
$this->blockcommentoff   	= array("");

// Keywords (keyword mapping to colour number)

$this->keywords          	= array(
			"ABX" => "1", 
			"ABY" => "1", 
			"ADCA" => "1", 
			"ADCB" => "1", 
			"ADDA" => "1", 
			"ADDB" => "1", 
			"ADDD" => "1", 
			"ANDA" => "1", 
			"ANDB" => "1", 
			"ANDCC" => "1", 
			"ASLA" => "1", 
			"ASLB" => "1", 
			"ASL" => "1", 
			"ASRA" => "1", 
			"ASRB" => "1", 
			"ASR" => "1", 
			"BCC" => "1", 
			"BCLR" => "1", 
			"BCS" => "1", 
			"BEQ" => "1", 
			"BGE" => "1", 
			"BGT" => "1", 
			"BHI" => "1", 
			"BHS" => "1", 
			"BLE" => "1", 
			"BLO" => "1", 
			"BLS" => "1", 
			"BLT" => "1", 
			"BMI" => "1", 
			"BNE" => "1", 
			"BPL" => "1", 
			"BRA" => "1", 
			"BRCLR" => "1", 
			"BRN" => "1", 
			"BSET" => "1", 
			"BSR" => "1", 
			"BVC" => "1", 
			"BVS" => "1", 
			"BITA" => "1", 
			"BITB" => "1", 
			"CLC" => "1", 
			"CLI" => "1", 
			"CLRA" => "1", 
			"CLRB" => "1", 
			"CLR" => "1", 
			"CMPA" => "1", 
			"CMPB" => "1", 
			"CMPD" => "1", 
			"CMPS" => "1", 
			"CMPU" => "1", 
			"CMPX" => "1", 
			"CMPY" => "1", 
			"COMA" => "1", 
			"COMB" => "1", 
			"COM" => "1", 
			"CPD" => "1", 
			"CPX" => "1", 
			"CPY" => "1", 
			"CWAI" => "1", 
			"DAA" => "1", 
			"DECA" => "1", 
			"DECB" => "1", 
			"DEC" => "1", 
			"DEX" => "1", 
			"DEY" => "1", 
			"EORA" => "1", 
			"EORB" => "1", 
			"EXG" => "1", 
			"IDIV" => "1", 
			"INCA" => "1", 
			"INCB" => "1", 
			"INC" => "1", 
			"INX" => "1", 
			"INY" => "1", 
			"JMP" => "1", 
			"JSR" => "1", 
			"LDA" => "1", 
			"LDAA" => "1", 
			"LDAB" => "1", 
			"LDB" => "1", 
			"LDD" => "1", 
			"LDS" => "1", 
			"LDU" => "1", 
			"LDX" => "1", 
			"LDY" => "1", 
			"LEAS" => "1", 
			"LEAU" => "1", 
			"LEAX" => "1", 
			"LEAY" => "1", 
			"LSLA" => "1", 
			"LSLB" => "1", 
			"LSLD" => "1", 
			"LSL" => "1", 
			"LSRA" => "1", 
			"LSRB" => "1", 
			"LSR" => "1", 
			"LBCC" => "1", 
			"LBCS" => "1", 
			"LBEQ" => "1", 
			"LBGE" => "1", 
			"LBGT" => "1", 
			"LBHI" => "1", 
			"LBHS" => "1", 
			"LBLE" => "1", 
			"LBLO" => "1", 
			"LBLS" => "1", 
			"LBLT" => "1", 
			"LBMI" => "1", 
			"LBNE" => "1", 
			"LBPL" => "1", 
			"LBRA" => "1", 
			"LBRN" => "1", 
			"LBSR" => "1", 
			"LBVC" => "1", 
			"LBVS" => "1", 
			"MUL" => "1", 
			"NEGA" => "1", 
			"NEGB" => "1", 
			"NEG" => "1", 
			"NOP" => "1", 
			"ORA" => "1", 
			"ORAA" => "1", 
			"ORAB" => "1", 
			"ORB" => "1", 
			"ORCC" => "1", 
			"BeautifierA" => "1", 
			"BeautifierB" => "1", 
			"BeautifierS" => "1", 
			"BeautifierU" => "1", 
			"BeautifierX" => "1", 
			"BeautifierY" => "1", 
			"PULA" => "1", 
			"PULB" => "1", 
			"PULS" => "1", 
			"PULU" => "1", 
			"PULX" => "1", 
			"PULY" => "1", 
			"ROLA" => "1", 
			"ROLB" => "1", 
			"ROL" => "1", 
			"RORA" => "1", 
			"RORB" => "1", 
			"ROR" => "1", 
			"RTI" => "1", 
			"RTS" => "1", 
			"SBCA" => "1", 
			"SBCB" => "1", 
			"SEC" => "1", 
			"SEX" => "1", 
			"SEI" => "1", 
			"STA" => "1", 
			"STAA" => "1", 
			"STAB" => "1", 
			"STB" => "1", 
			"STD" => "1", 
			"STOP" => "1", 
			"STS" => "1", 
			"STU" => "1", 
			"STX" => "1", 
			"STY" => "1", 
			"SUBA" => "1", 
			"SUBB" => "1", 
			"SUBD" => "1", 
			"SWI" => "1", 
			"SWI2" => "1", 
			"SWI3" => "1", 
			"SYNC" => "1", 
			"TAB" => "1", 
			"TAP" => "1", 
			"TBA" => "1", 
			"TFR" => "1", 
			"TSTA" => "1", 
			"TSTB" => "1", 
			"TST" => "1", 
			"XGDX" => "1", 
			"TCNT" => "2", 
			"TI4O5" => "2", 
			"TIC1" => "2", 
			"TIC2" => "2", 
			"TIC3" => "2", 
			"TOC1" => "2", 
			"TOC2" => "2", 
			"TOC3" => "2", 
			"TOC4" => "2", 
			"TCTL1" => "2", 
			"TCTL2" => "2", 
			"TMSK1" => "2", 
			"TFLG1" => "2", 
			"TMSK2" => "2", 
			"TFLG2" => "2", 
			"TEST1" => "2", 
			"BASE" => "2", 
			"BAUD" => "2", 
			"BPROT" => "2", 
			"PORTA" => "2", 
			"PORTB" => "2", 
			"PORTC" => "2", 
			"PORTCL" => "2", 
			"PORTD" => "2", 
			"PORTE" => "2", 
			"PPROG" => "2", 
			"PIOC" => "2", 
			"PACTL" => "2", 
			"PACNT" => "2", 
			"DDRA" => "2", 
			"DDRB" => "2", 
			"DDRC" => "2", 
			"DDRD" => "2", 
			"DDRE" => "2", 
			"SCCR1" => "2", 
			"SCCR2" => "2", 
			"SCSR" => "2", 
			"SCDR" => "2", 
			"SPCR" => "2", 
			"SPSR" => "2", 
			"SPDR" => "2", 
			"ADCTL" => "2", 
			"ADR1" => "2", 
			"ADR2" => "2", 
			"ADR3" => "2", 
			"ADR4" => "2", 
			"RESV1" => "2", 
			"RESV2" => "2", 
			"RESV3" => "2", 
			"RESV4" => "2", 
			"OPTION" => "2", 
			"OC1D" => "2", 
			"OC1M" => "2", 
			"CONFIG" => "2", 
			"COPRST" => "2", 
			"CFORC" => "2", 
			"INIT" => "2", 
			"HPRIO" => "2", 
			"#ifdef" => "3", 
			"#ifndef" => "3", 
			"#define" => "3", 
			"#endif" => "3", 
			"#include" => "3", 
			"#else" => "3", 
			"FCB" => "4", 
			"FCC" => "4", 
			"FDB" => "4", 
			"EQU" => "4", 
			"ENDM" => "4", 
			"MACRO" => "4", 
			"ORG" => "4", 
			"SETDP" => "4", 
			"#" => "5", 
			"#$" => "5", 
			"#%" => "5", 
			"IRQINT" => "6", 
			"PAIINT" => "6", 
			"PAOVINT" => "6", 
			"RTIINT" => "6", 
			"RESETINT" => "6", 
			"SCIINT" => "6", 
			"SPIINT" => "6", 
			"SWIINT" => "6", 
			"TOINT" => "6", 
			"TOC5INT" => "6", 
			"TOC4INT" => "6", 
			"TOC3INT" => "6", 
			"TOC2INT" => "6", 
			"TOC1INT" => "6", 
			"TIC3INT" => "6", 
			"TIC2INT" => "6", 
			"TIC1INT" => "6", 
			"XIRQINT" => "6", 
			"BADOPINT" => "6", 
			"NOCOPINT" => "6", 
			"CMEINT" => "6");

// Special extensions

// Each category can specify a PHP function that returns an altered
// version of the keyword.
        
        

$this->linkscripts    	= array(
			"1" => "donothing", 
			"2" => "donothing", 
			"3" => "donothing", 
			"4" => "donothing", 
			"5" => "donothing", 
			"6" => "donothing");
}


function donothing($keywordin)
{
	return $keywordin;
}

}?>
