<?php
$BEAUT_PATH = realpath(".")."/Services/COPage/syntax_highlight/php";
if (!isset ($BEAUT_PATH)) return;
require_once("$BEAUT_PATH/Beautifier/HFile.php");
  class HFile_postscript extends HFile{
   function HFile_postscript(){
     $this->HFile();	
/*************************************/
// Beautifier Highlighting Configuration File 
// PostScript
/*************************************/
// Flags

$this->nocase            	= "0";
$this->notrim            	= "0";
$this->perl              	= "0";

// Colours

$this->colours        	= array("brown", "blue", "purple", "gray");
$this->quotecolour       	= "blue";
$this->blockcommentcolour	= "green";
$this->linecommentcolour 	= "green";

// Indent Strings

$this->indent            	= array("{", "[");
$this->unindent          	= array("}", "]");

// String characters and delimiters

$this->stringchars       	= array("%");
$this->delimiters        	= array("{", "}", " ", "	", "[", "]", "(", ")", "/", "\\");
$this->escchar           	= "";

// Comment settings

$this->linecommenton     	= array("%%");
$this->blockcommenton    	= array("");
$this->blockcommentoff   	= array("");

// Keywords (keyword mapping to colour number)

$this->keywords          	= array(
			"/Escape" => "", 
			"Char" => "", 
			"=" => "4", 
			"\\" => "", 
			"(" => "1", 
			")" => "1", 
			"begin" => "1", 
			"bind" => "1", 
			"def" => "1", 
			"defineresource" => "1", 
			"defineuserobject" => "1", 
			"echo" => "1", 
			"end" => "1", 
			"exec" => "1", 
			"execuserobject" => "1", 
			"executive" => "1", 
			"executeonly" => "1", 
			"exit" => "1", 
			"filenameforall" => "1", 
			"for" => "1", 
			"forall" => "1", 
			"if" => "1", 
			"ifelse" => "1", 
			"loop" => "1", 
			"noaccess" => "1", 
			"pathforall" => "1", 
			"pdfmark" => "1", 
			"prompt" => "1", 
			"quit" => "1", 
			"readonly" => "1", 
			"repeat" => "1", 
			"resourceforall" => "1", 
			"restore" => "1", 
			"run" => "1", 
			"save" => "1", 
			"setglobal" => "1", 
			"start" => "1", 
			"startjob" => "1", 
			"stop" => "1", 
			"stopped" => "1", 
			"undef" => "1", 
			"undefineresource" => "1", 
			"undefineuserobject" => "1", 
			"arc" => "2", 
			"arcn" => "2", 
			"arct" => "2", 
			"arcto" => "2", 
			"ashow" => "2", 
			"awidthshow" => "2", 
			"charpath" => "2", 
			"clip" => "2", 
			"clippath" => "2", 
			"cliprestore" => "2", 
			"clipsave" => "2", 
			"closepath" => "2", 
			"colorimage" => "2", 
			"concat" => "2", 
			"concatmatrix" => "2", 
			"copypage" => "2", 
			"currentblackgeneration" => "2", 
			"currentcmykcolor" => "2", 
			"currentcolor" => "2", 
			"currentcolorrendering" => "2", 
			"currentcolorscreen" => "2", 
			"currentcolorspace" => "2", 
			"currentcolortransfer" => "2", 
			"currentdash" => "2", 
			"currentflat" => "2", 
			"currentgray" => "2", 
			"currentgstate" => "2", 
			"currenthalftone" => "2", 
			"currenthsbcolor" => "2", 
			"currentlinecap" => "2", 
			"currentlinejoin" => "2", 
			"currentlinewidth" => "2", 
			"currentmiterlimit" => "2", 
			"currentoverprint" => "2", 
			"currentpagedevice" => "2", 
			"currentpoint" => "2", 
			"currentrgbcolor" => "2", 
			"currentscreen" => "2", 
			"currentsmoothness" => "2", 
			"currentstrokeadjust" => "2", 
			"currenttransfer" => "2", 
			"currentundercolorremoval" => "2", 
			"curveto" => "2", 
			"composefont" => "2", 
			"cshow" => "2", 
			"currentfont" => "2", 
			"defaultmatrix" => "2", 
			"dtransform" => "2", 
			"definefont" => "2", 
			"eoclip" => "2", 
			"eofill" => "2", 
			"erasepage" => "2", 
			"execform" => "2", 
			"fill" => "2", 
			"flattenpath" => "2", 
			"findencoding" => "2", 
			"findfont" => "2", 
			"FontDirectory" => "2", 
			"grestore" => "2", 
			"grestoreall" => "2", 
			"gsave" => "2", 
			"glyphshow" => "2", 
			"GlobalFontDirectory" => "2", 
			"idtransform" => "2", 
			"ineofill" => "2", 
			"infill" => "2", 
			"initclip" => "2", 
			"initgraphics" => "2", 
			"identmatrix" => "2", 
			"initmatrix" => "2", 
			"instroke" => "2", 
			"inueofill" => "2", 
			"inufill" => "2", 
			"inustroke" => "2", 
			"invertmatrix" => "2", 
			"image" => "2", 
			"imagemask" => "2", 
			"ISOLatin1Encoding" => "2", 
			"kshow" => "2", 
			"lineto" => "2", 
			"makepattern" => "2", 
			"moveto" => "2", 
			"makefont" => "2", 
			"newpath" => "2", 
			"nulldevice" => "2", 
			"pathbox" => "2", 
			"rcurveto" => "2", 
			"rectclip" => "2", 
			"rectfill" => "2", 
			"rectstroke" => "2", 
			"reversepath" => "2", 
			"rlineto" => "2", 
			"rmoveto" => "2", 
			"rotate" => "2", 
			"rootfont" => "2", 
			"scale" => "2", 
			"setblackgeneration" => "2", 
			"setbox" => "2", 
			"setcmykcolor" => "2", 
			"setcolor" => "2", 
			"setcolorrendering" => "2", 
			"setcolorscreen" => "2", 
			"setcolorspace" => "2", 
			"setcolortransfer" => "2", 
			"setdash" => "2", 
			"setflat" => "2", 
			"setgray" => "2", 
			"setgstate" => "2", 
			"sethalftone" => "2", 
			"sethsbcolor" => "2", 
			"setlinecap" => "2", 
			"setlinejoin" => "2", 
			"setlinewidth" => "2", 
			"setmatrix" => "2", 
			"setmiterlimit" => "2", 
			"setoverprint" => "2", 
			"setpagedevice" => "2", 
			"setpattern" => "2", 
			"setrgbcolor" => "2", 
			"setscreen" => "2", 
			"setsmoothness" => "2", 
			"setstrokeadjust" => "2", 
			"settransfer" => "2", 
			"shfill" => "2", 
			"showpage" => "2", 
			"stroke" => "2", 
			"strokepath" => "2", 
			"scalefont" => "2", 
			"selectfont" => "2", 
			"setcachedevice" => "2", 
			"setcachedevice2" => "2", 
			"setcharwidth" => "2", 
			"setfont" => "2", 
			"show" => "2", 
			"StandardEncoding" => "2", 
			"stringwidth" => "2", 
			"transform" => "2", 
			"translate" => "2", 
			"uappend" => "2", 
			"ucache" => "2", 
			"ueofill" => "2", 
			"ufill" => "2", 
			"upath" => "2", 
			"ustroke" => "2", 
			"ustrokepath" => "2", 
			"widthshow" => "2", 
			"xshow" => "2", 
			"xyshow" => "2", 
			"yshow" => "2", 
			"[" => "3", 
			"]" => "3", 
			"<<" => "3", 
			">>" => "3", 
			"$error" => "3", 
			"aload" => "3", 
			"anchorsearch" => "3", 
			"astore" => "3", 
			"array" => "3", 
			"abs" => "3", 
			"add" => "3", 
			"and" => "3", 
			"atan" => "3", 
			"bitshift" => "3", 
			"copy" => "3", 
			"currentglobal" => "3", 
			"currentobjectformat" => "3", 
			"currentpacking" => "3", 
			"cvi" => "3", 
			"cvlit" => "3", 
			"cvn" => "3", 
			"cvr" => "3", 
			"cvrs" => "3", 
			"cvs" => "3", 
			"cvx" => "3", 
			"currentdict" => "3", 
			"currentfile" => "3", 
			"currentmatrix" => "3", 
			"clear" => "3", 
			"cleardictstack" => "3", 
			"cleartomark" => "3", 
			"count" => "3", 
			"countdictstack" => "3", 
			"countexecstack" => "3", 
			"counttomark" => "3", 
			"ceiling" => "3", 
			"cos" => "3", 
			"dict" => "3", 
			"dictstack" => "3", 
			"dup" => "3", 
			"div" => "3", 
			"errordict" => "3", 
			"execstack" => "3", 
			"exch" => "3", 
			"eq" => "3", 
			"exp" => "3", 
			"findcolorrendering" => "3", 
			"false" => "3", 
			"file" => "3", 
			"filter" => "3", 
			"findresource" => "3", 
			"floor" => "3", 
			"gcheck" => "3", 
			"get" => "3", 
			"getinterval" => "3", 
			"globaldict" => "3", 
			"gstate" => "3", 
			"ge" => "3", 
			"gt" => "3", 
			"index" => "3", 
			"idiv" => "3", 
			"known" => "3", 
			"languagelevel" => "3", 
			"length" => "3", 
			"load" => "3", 
			"le" => "3", 
			"ln" => "3", 
			"log" => "3", 
			"lt" => "3", 
			"maxlength" => "3", 
			"matrix" => "3", 
			"mark" => "3", 
			"mod" => "3", 
			"mul" => "3", 
			"null" => "3", 
			"ne" => "3", 
			"neg" => "3", 
			"not" => "3", 
			"product" => "3", 
			"put" => "3", 
			"putinterval" => "3", 
			"packedarray" => "3", 
			"pop" => "3", 
			"pstack" => "3", 
			"rcheck" => "3", 
			"realtime" => "3", 
			"resourcestatus" => "3", 
			"revision" => "3", 
			"roll" => "3", 
			"rand" => "3", 
			"rrand" => "3", 
			"round" => "3", 
			"search" => "3", 
			"serialnumber" => "3", 
			"setobjectformat" => "3", 
			"setpacking" => "3", 
			"store" => "3", 
			"statusdict" => "3", 
			"string" => "3", 
			"systemdict" => "3", 
			"stack" => "3", 
			"sin" => "3", 
			"sqrt" => "3", 
			"srand" => "3", 
			"sub" => "3", 
			"token" => "3", 
			"type" => "3", 
			"true" => "3", 
			"truncate" => "3", 
			"usertime" => "3", 
			"userdict" => "3", 
			"UserObjects" => "3", 
			"version" => "3", 
			"wcheck" => "3", 
			"where" => "3", 
			"xcheck" => "3", 
			"xor" => "3", 
			"==" => "4", 
			"bytesavailable" => "4", 
			"closefile" => "4", 
			"deletefile" => "4", 
			"fileposition" => "4", 
			"flush" => "4", 
			"flushfile" => "4", 
			"print" => "4", 
			"printobject" => "4", 
			"read" => "4", 
			"readhexstring" => "4", 
			"readline" => "4", 
			"readstring" => "4", 
			"renamefile" => "4", 
			"resetfile" => "4", 
			"status" => "4", 
			"write" => "4", 
			"writehexstring" => "4", 
			"writeobject" => "4", 
			"writestring" => "4");

// Special extensions

// Each category can specify a PHP function that returns an altered
// version of the keyword.
        
        

$this->linkscripts    	= array(
			"" => "donothing", 
			"4" => "donothing", 
			"1" => "donothing", 
			"2" => "donothing", 
			"3" => "donothing");
}


function donothing($keywordin)
{
	return $keywordin;
}

}?>
