<?php



/**
 * AdmSettingsTemplate
 */
class AdmSettingsTemplate
{
    /**
     * @var int
     */
    private $id = '0';

    /**
     * @var string
     */
    private $type = '';

    /**
     * @var string
     */
    private $title = '';

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var bool|null
     */
    private $autoGenerated = '0';


    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set type.
     *
     * @param string $type
     *
     * @return AdmSettingsTemplate
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type.
     *
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set title.
     *
     * @param string $title
     *
     * @return AdmSettingsTemplate
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title.
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set description.
     *
     * @param string|null $description
     *
     * @return AdmSettingsTemplate
     */
    public function setDescription($description = null)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description.
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set autoGenerated.
     *
     * @param bool|null $autoGenerated
     *
     * @return AdmSettingsTemplate
     */
    public function setAutoGenerated($autoGenerated = null)
    {
        $this->autoGenerated = $autoGenerated;

        return $this;
    }

    /**
     * Get autoGenerated.
     *
     * @return bool|null
     */
    public function getAutoGenerated()
    {
        return $this->autoGenerated;
    }
}
