<?php



/**
 * CalEntries
 */
class CalEntries
{
    /**
     * @var int
     */
    private $calId = '0';

    /**
     * @var \DateTime|null
     */
    private $lastUpdate;

    /**
     * @var string|null
     */
    private $title;

    /**
     * @var string|null
     */
    private $subtitle;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var string|null
     */
    private $location;

    /**
     * @var bool
     */
    private $fullday = '0';

    /**
     * @var \DateTime|null
     */
    private $starta;

    /**
     * @var \DateTime|null
     */
    private $enda;

    /**
     * @var string|null
     */
    private $informations;

    /**
     * @var bool
     */
    private $autoGenerated = '0';

    /**
     * @var int
     */
    private $contextId = '0';

    /**
     * @var bool
     */
    private $translationType = '0';

    /**
     * @var bool
     */
    private $isMilestone = '0';

    /**
     * @var int
     */
    private $completion = '0';

    /**
     * @var bool
     */
    private $notification = '0';

    /**
     * @var string|null
     */
    private $contextInfo;


    /**
     * Get calId.
     *
     * @return int
     */
    public function getCalId()
    {
        return $this->calId;
    }

    /**
     * Set lastUpdate.
     *
     * @param \DateTime|null $lastUpdate
     *
     * @return CalEntries
     */
    public function setLastUpdate($lastUpdate = null)
    {
        $this->lastUpdate = $lastUpdate;

        return $this;
    }

    /**
     * Get lastUpdate.
     *
     * @return \DateTime|null
     */
    public function getLastUpdate()
    {
        return $this->lastUpdate;
    }

    /**
     * Set title.
     *
     * @param string|null $title
     *
     * @return CalEntries
     */
    public function setTitle($title = null)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title.
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set subtitle.
     *
     * @param string|null $subtitle
     *
     * @return CalEntries
     */
    public function setSubtitle($subtitle = null)
    {
        $this->subtitle = $subtitle;

        return $this;
    }

    /**
     * Get subtitle.
     *
     * @return string|null
     */
    public function getSubtitle()
    {
        return $this->subtitle;
    }

    /**
     * Set description.
     *
     * @param string|null $description
     *
     * @return CalEntries
     */
    public function setDescription($description = null)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description.
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set location.
     *
     * @param string|null $location
     *
     * @return CalEntries
     */
    public function setLocation($location = null)
    {
        $this->location = $location;

        return $this;
    }

    /**
     * Get location.
     *
     * @return string|null
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Set fullday.
     *
     * @param bool $fullday
     *
     * @return CalEntries
     */
    public function setFullday($fullday)
    {
        $this->fullday = $fullday;

        return $this;
    }

    /**
     * Get fullday.
     *
     * @return bool
     */
    public function getFullday()
    {
        return $this->fullday;
    }

    /**
     * Set starta.
     *
     * @param \DateTime|null $starta
     *
     * @return CalEntries
     */
    public function setStarta($starta = null)
    {
        $this->starta = $starta;

        return $this;
    }

    /**
     * Get starta.
     *
     * @return \DateTime|null
     */
    public function getStarta()
    {
        return $this->starta;
    }

    /**
     * Set enda.
     *
     * @param \DateTime|null $enda
     *
     * @return CalEntries
     */
    public function setEnda($enda = null)
    {
        $this->enda = $enda;

        return $this;
    }

    /**
     * Get enda.
     *
     * @return \DateTime|null
     */
    public function getEnda()
    {
        return $this->enda;
    }

    /**
     * Set informations.
     *
     * @param string|null $informations
     *
     * @return CalEntries
     */
    public function setInformations($informations = null)
    {
        $this->informations = $informations;

        return $this;
    }

    /**
     * Get informations.
     *
     * @return string|null
     */
    public function getInformations()
    {
        return $this->informations;
    }

    /**
     * Set autoGenerated.
     *
     * @param bool $autoGenerated
     *
     * @return CalEntries
     */
    public function setAutoGenerated($autoGenerated)
    {
        $this->autoGenerated = $autoGenerated;

        return $this;
    }

    /**
     * Get autoGenerated.
     *
     * @return bool
     */
    public function getAutoGenerated()
    {
        return $this->autoGenerated;
    }

    /**
     * Set contextId.
     *
     * @param int $contextId
     *
     * @return CalEntries
     */
    public function setContextId($contextId)
    {
        $this->contextId = $contextId;

        return $this;
    }

    /**
     * Get contextId.
     *
     * @return int
     */
    public function getContextId()
    {
        return $this->contextId;
    }

    /**
     * Set translationType.
     *
     * @param bool $translationType
     *
     * @return CalEntries
     */
    public function setTranslationType($translationType)
    {
        $this->translationType = $translationType;

        return $this;
    }

    /**
     * Get translationType.
     *
     * @return bool
     */
    public function getTranslationType()
    {
        return $this->translationType;
    }

    /**
     * Set isMilestone.
     *
     * @param bool $isMilestone
     *
     * @return CalEntries
     */
    public function setIsMilestone($isMilestone)
    {
        $this->isMilestone = $isMilestone;

        return $this;
    }

    /**
     * Get isMilestone.
     *
     * @return bool
     */
    public function getIsMilestone()
    {
        return $this->isMilestone;
    }

    /**
     * Set completion.
     *
     * @param int $completion
     *
     * @return CalEntries
     */
    public function setCompletion($completion)
    {
        $this->completion = $completion;

        return $this;
    }

    /**
     * Get completion.
     *
     * @return int
     */
    public function getCompletion()
    {
        return $this->completion;
    }

    /**
     * Set notification.
     *
     * @param bool $notification
     *
     * @return CalEntries
     */
    public function setNotification($notification)
    {
        $this->notification = $notification;

        return $this;
    }

    /**
     * Get notification.
     *
     * @return bool
     */
    public function getNotification()
    {
        return $this->notification;
    }

    /**
     * Set contextInfo.
     *
     * @param string|null $contextInfo
     *
     * @return CalEntries
     */
    public function setContextInfo($contextInfo = null)
    {
        $this->contextInfo = $contextInfo;

        return $this;
    }

    /**
     * Get contextInfo.
     *
     * @return string|null
     */
    public function getContextInfo()
    {
        return $this->contextInfo;
    }
}
