<?php

$WBD_USER_RECORD = array(
	'title' => '', //Herr:Frau
	'degree' => '',
	'first_name' => '',
	'last_name' => '',
	'name_affix' => '',
	'birthday' => '',
	'auth_email' => '',
	'auth_phone_nr' => '',
	'country_code' => '',
	'zipcode' => '',
	'city' => '',
	'street' => '',
	'house_number' => '',
	'pob' => '',
	'address_code' => '',
	'free_text' => '',
	'email' => '',
	'phone_nr' => '',
	'mobile_phone_nr' => '',
	'url' => '',
	'data_transfer_code'  => '',
	'data_protection_code'  => '',
	'training_pass' => '',
	'agent_registration_nr' => '',
	'agency_work' => '',
	'agent_state' => '',
	'email_confirmation' => '',
	'tp_service'  => '',
	'internal_agent_id' => '',
);


$WBD_EDU_RECORD = array(
	"user_bwv_id" => '',
	"wbd_case_id" => '',
	"crs_template_title" => '',
	"crs_credit_points" => '',
	"crs_type_title" => '',
	"crs_start_date" => '',
	"crs_end_date" => '',
	"part_okz" => '',

	"user_firstname" => '',
	"user_lastname" => '',
	"user_gender" => '',
	"user_adp_no" => '',

	"crs_obj_id" => "",
	"crs_cost_per_part" => 0,
	"wbd_transfer_ts" => -1,
	"crs_description" => "-empty-",
	"crs_mandatory" => 0,
	"part_function_title" => "Teilnehmer",
	"part_booking_state_title" => "Gebucht",
	"part_participation_state_title" => "Teilgenommen",
	"user_productivity" => "produktiv"
);



$CSV_LABELS = array(
	"address_code" => "Adresskennzeichen",
	"administration_id" => "VerwaltungsID",
	"agency_work" => "Vermittlungstätigkeit",
	"agent_id" => "VermittlerID",
	"agent_id_import" => "Vermittler Id",
	"agent_registration_nr" => "Vermittlerregisternummer",
	"agent_state" => "Vermittlerstatus",
	"auth_email" => "Authentifizierungs Email",
	"auth_phone_nr" => "Authentifizierungs Telefonnummer",
	"birthday" => "Geburtsdatum",
	"birthday_or_internal_agent_id" => "Geburtsdatum (oder interne VermittlerID)",
	"booking_nr" => "Buchungsnummer",
	"cancelled" => "Storniert",
	"city" => "Ort",
	"contact_degree" => "Ansprechpartner Titel",
	"contact_email" => "Ansprechpartner E-Mail",
	"contact_first_name" => "Ansprechpartner Vorname",
	"contact_last_name" => "Ansprechpartner Nachname",
	"contact_phone" => "Ansprechpartner Telefon",
	"country_code" => "Länderkennzeichen",
	"current_okz" => "Aktuelles OKZ",
	"data_protection_code" => "Datenschutzkennzeichen",
	"data_transfer_code" => "Datenübermittlungskennzeichen",
	"degree" => "Titel",
	"email" => "Emailadresse",
	"email_confirmation" => "Benachrichtigung Per Email",
	"first_name" => "Vorname",
	"free_text" => "Freitext",
	"from" => "von",
	"house_number" => "Hausnummer",
	"internal_agent_id" => "Interne Vermittler Id",
	//"internal_agent_id_import" => "interne Vermittler Id",
	"internal_booking_id" => "InterneBuchungsID",
	"internal_booking_id_import" => "interneBuchungsId",
	"last_name" => "Nachname",
	"mobile_phone_nr" => "Mobilfunknummer",
	"name" => "Name",
	"name_affix" => "Namenszusatz",
	"phone_nr" => "Telefonnummer",
	"pob" => "Postfach",
	"score" => "Punkte",
	"score_code" => "KennzeichenPunkte",
	"seminar_end_date" => "SeminarDatumbis",
	"seminar_start_date" => "SeminarDatumab",
	"seminar_title" => "Name der Maßnahme",
	"service_end" => "ServiceBis",
	"service_since" => "ServiceSeit",
	"end_date" => "Enddatum",
	"start_date" => "Startdatum",
	"street" => "Straße",
	"study_content" => "Lerninhalt",
	"study_type" => "Lernart",
	"study_type_selection" => "Lernart (Auswahl)",
	"till" => "bis",
	"title" => "Anrede",
	"tp_service" => "TP Service",
	"training" => "Weiterbildung",
	"training_pass" => "Weiterbildungausweis beantragt",
	"training_score_booking_id" => "WeiterbildungsPunkteBuchungsID",
	"training_score_booking_id_import" => "WeiterbildungspunktebuchungsID",
	"url" => "URL",
	"zipcode" => "Postleitzahl"
);

?>
