tinyMCE.addI18n('hu.ilimgupload', {
	title                          :'Kép beszúrása',
	upload_image                   :'Kép feltöltése',
	cancel                         :'Mégsem',
	upload                         :'Feltölt',
	src                            :'Forrás',
	image_select                   :'Válasszon képet',
	image_alt                      :'Képinformáció',
	upload_image_from_local_fs     :'Helyi rendszer',
	upload_image_from_local_fs_desc:'Kép feltöltése helyi számítógépről',
	upload_image_from_url          :'URL',
	upload_image_from_url_desc     :'Kép beszúrása másik weboldalról',
	border                         :"Keret",
	dimensions                     :"Méretek",
	vspace                         :"Függőleges távolság",
	hspace                         :"Vízszintes távolság",
	align                          :"Igazítás",
	align_baseline                 :"Alapvonalhoz",
	align_top                      :"Felülre",
	align_middle                   :"Középre",
	align_bottom                   :"Alulra",
	align_texttop                  :"Szöveg tetejéhez",
	align_textbottom               :"Szöveg aljához",
	align_left                     :"Balra",
	align_right                    :"Jobbra",
	insert                         :"Beilleszt",
	width                          :"Szélesség",
	height                         :"Magasság",
	edit_image                     :"Kép szerkesztése",
	edit_image_desc                :"Feltöltött kép szerkesztése",
	constrain_proportions          :"Méretarányok megtartása"
});