<?php declare(strict_types=1);

/* Copyright (c) 2022 Thibeau Fuhrer <thibeau@sr.solutions> Extended GPL, see docs/LICENSE */

namespace ILIAS\UI\Implementation\Component\Input\Field;

use ILIAS\UI\Implementation\Component\Input\DynamicInputsNameSource;
use ILIAS\UI\Implementation\Component\Input\InputData;
use Iterator;

/**
 * @author Thibeau Fuhrer <thibeau@sr.solutions>
 */
class DynamicInputDataIterator implements Iterator
{
    protected string $parent_input_name;
    protected array $post_data;
    protected int $index = 0;

    public function __construct(InputData $data, string $parent_input_name)
    {
        $this->post_data = $data->getOr($parent_input_name, []);
        $this->parent_input_name = $parent_input_name;
    }

    public function current() : ?InputData
    {
        if ($this->valid()) {
            $entry = [];
            $name_source = new DynamicInputsNameSource($this->parent_input_name);
            foreach ($this->post_data as $input_data) {
                // the input data must be mapped to the name generated by the
                // dynamic inputs name source, otherwise the InputData will not
                // be valid when delegating it by Input::withInput().
                $entry[$name_source->getNewName()] = $input_data[$this->index];
            }

            return new ArrayInputData($entry);
        }

        return null;
    }

    public function next() : void
    {
        $this->index++;
    }

    public function key() : ?int
    {
        if ($this->valid()) {
            return $this->index;
        }

        return null;
    }

    public function valid() : bool
    {
        if (empty($this->post_data)) {
            return false;
        }

        foreach ($this->post_data as $input_data) {
            if (!isset($input_data[$this->index])) {
                return false;
            }
        }

        return true;
    }

    public function rewind() : void
    {
        $this->index = 0;
    }
}
