<?php

declare(strict_types=1);

/**
 * This file is part of ILIAS, a powerful learning management system
 * published by ILIAS open source e-Learning e.V.
 *
 * ILIAS is licensed with the GPL-3.0,
 * see https://www.gnu.org/licenses/gpl-3.0.en.html
 * You should have received a copy of said license along with the
 * source code, too.
 *
 * If this is not the case or you just want to try ILIAS, you'll find
 * us at:
 * https://www.ilias.de
 * https://github.com/ILIAS-eLearning
 *
 *********************************************************************/

namespace ILIAS\News\Data;

use DateTimeImmutable;

/**
 * News Criteria DTO for querying news items supports caching, JSON serialization, and validation
 */
final class NewsCriteria implements \JsonSerializable
{
    private ?DateTimeImmutable $start_date = null;
    private ?DateTimeImmutable $end_date = null;
    private bool $only_public = false;
    private array $context_obj_ids = [];
    private array $context_obj_types = [];
    private ?int $min_priority = null;
    private ?int $max_priority = null;
    private ?int $limit = null;
    private ?int $offset = null;
    private bool $prevent_aggregation = false;
    private bool $no_auto_generated = false;
    private array $excluded_news_ids = [];
    private ?int $user_id = null;
    private bool $include_read_status = false;
    private ?string $search_term = null;
    private array $content_types = [];
    private ?int $root_ref_id = null;

    /*
        Getters and Setters
     */

    public function getStartDate(): ?DateTimeImmutable
    {
        return $this->start_date;
    }

    public function getEndDate(): ?DateTimeImmutable
    {
        return $this->end_date;
    }

    public function isOnlyPublic(): bool
    {
        return $this->only_public;
    }

    public function getContextObjIds(): array
    {
        return $this->context_obj_ids;
    }

    public function getContextObjTypes(): array
    {
        return $this->context_obj_types;
    }

    public function getMinPriority(): ?int
    {
        return $this->min_priority;
    }

    public function getMaxPriority(): ?int
    {
        return $this->max_priority;
    }

    public function getLimit(): ?int
    {
        return $this->limit;
    }

    public function getOffset(): ?int
    {
        return $this->offset;
    }

    public function isPreventAggregation(): bool
    {
        return $this->prevent_aggregation;
    }

    public function isNoAutoGenerated(): bool
    {
        return $this->no_auto_generated;
    }

    public function getExcludedNewsIds(): array
    {
        return $this->excluded_news_ids;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function isIncludeReadStatus(): bool
    {
        return $this->include_read_status;
    }

    public function getSearchTerm(): ?string
    {
        return $this->search_term;
    }

    public function getContentTypes(): array
    {
        return $this->content_types;
    }

    public function getRootRefId(): ?int
    {
        return $this->root_ref_id;
    }

    public function withStartDate(?DateTimeImmutable $start_date): self
    {
        $new = clone $this;
        $new->start_date = $start_date;
        return $new;
    }

    public function withEndDate(?DateTimeImmutable $end_date): self
    {
        $new = clone $this;
        $new->end_date = $end_date;
        return $new;
    }

    public function withOnlyPublic(bool $only_public): self
    {
        $new = clone $this;
        $new->only_public = $only_public;
        return $new;
    }

    public function withContextObjIds(array $context_obj_ids): self
    {
        $new = clone $this;
        $new->context_obj_ids = array_map('intval', $context_obj_ids);
        return $new;
    }

    public function withContextObjTypes(array $context_obj_types): self
    {
        $new = clone $this;
        $new->context_obj_types = array_map('strval', $context_obj_types);
        return $new;
    }

    public function withMinPriority(?int $min_priority): self
    {
        $new = clone $this;
        $new->min_priority = $min_priority;
        return $new;
    }

    public function withMaxPriority(?int $max_priority): self
    {
        $new = clone $this;
        $new->max_priority = $max_priority;
        return $new;
    }

    public function withLimit(?int $limit): self
    {
        $new = clone $this;
        $new->limit = $limit;
        return $new;
    }

    public function withOffset(?int $offset): self
    {
        $new = clone $this;
        $new->offset = $offset;
        return $new;
    }

    public function withPreventAggregation(bool $prevent_aggregation): self
    {
        $new = clone $this;
        $new->prevent_aggregation = $prevent_aggregation;
        return $new;
    }

    public function withNoAutoGenerated(bool $no_auto_generated): self
    {
        $new = clone $this;
        $new->no_auto_generated = $no_auto_generated;
        return $new;
    }

    public function withExcludedNewsIds(array $excluded_news_ids): self
    {
        $new = clone $this;
        $new->excluded_news_ids = array_map('intval', $excluded_news_ids);
        return $new;
    }

    public function withUserId(?int $user_id): self
    {
        $new = clone $this;
        $new->user_id = $user_id;
        return $new;
    }

    public function withIncludeReadStatus(bool $include_read_status): self
    {
        $new = clone $this;
        $new->include_read_status = $include_read_status;
        return $new;
    }

    public function withSearchTerm(?string $search_term): self
    {
        $new = clone $this;
        $new->search_term = $search_term;
        return $new;
    }

    public function withContentTypes(array $content_types): self
    {
        $new = clone $this;
        $new->content_types = array_map('strval', $content_types);
        return $new;
    }

    public function withRootRefId(?int $root_ref_id): self
    {
        $new = clone $this;
        $new->root_ref_id = $root_ref_id;
        return $new;
    }

    /*
        Public Methods
     */

    public function jsonSerialize(): array
    {
        return array_merge(
            $this->getPublicCriteria(),
            $this->getUserSpecificCriteria()
        );
    }

    /**
     * Get public criteria (for cache key generation)
     */
    public function getPublicCriteria(): array
    {
        return [
            'start_date' => $this->start_date?->format('Y-m-d H:i:s'),
            'end_date' => $this->end_date?->format('Y-m-d H:i:s'),
            'only_public' => $this->only_public,
            'context_obj_ids' => $this->context_obj_ids,
            'context_obj_types' => $this->context_obj_types,
            'min_priority' => $this->min_priority,
            'max_priority' => $this->max_priority,
            'limit' => $this->limit,
            'offset' => $this->offset,
            'prevent_aggregation' => $this->prevent_aggregation,
            'no_auto_generated' => $this->no_auto_generated,
            'excluded_news_ids' => $this->excluded_news_ids,
            'search_term' => $this->search_term,
            'content_types' => $this->content_types,
            'root_ref_id' => $this->root_ref_id
        ];
    }

    /**
     * Get user-specific criteria (excludes public criteria)
     */
    public function getUserSpecificCriteria(): array
    {
        return [
            'user_id' => $this->user_id,
            'include_read_status' => $this->include_read_status
        ];
    }

    /**
     * Check if criteria has a date range
     */
    public function hasDateRange(): bool
    {
        return $this->start_date !== null || $this->end_date !== null;
    }

    /**
     * Check if criteria has context filters
     */
    public function hasContextFilters(): bool
    {
        return !empty($this->context_obj_ids) || !empty($this->context_obj_types);
    }

    /**
     * Check if criteria has priority filters
     */
    public function hasPriorityFilters(): bool
    {
        return $this->min_priority !== null || $this->max_priority !== null;
    }

    /**
     * Check if criteria has pagination
     */
    public function hasPagination(): bool
    {
        return $this->limit !== null || $this->offset !== null;
    }

    /**
     * Validate criteria parameters
     */
    public function validate(): void
    {
        if ($this->start_date && $this->end_date && $this->start_date > $this->end_date) {
            throw new \InvalidArgumentException('Start date cannot be after end date');
        }

        if ($this->min_priority !== null && $this->max_priority !== null && $this->min_priority > $this->max_priority) {
            throw new \InvalidArgumentException('Min priority cannot be greater than max priority');
        }

        if ($this->limit !== null && $this->limit < 0) {
            throw new \InvalidArgumentException('Limit cannot be negative');
        }

        if ($this->offset !== null && $this->offset < 0) {
            throw new \InvalidArgumentException('Offset cannot be negative');
        }
    }
}
