<?php

/**
 * Interface ilCtrlSecurityInterface provides ilCtrl security
 * information.
 *
 * @author Thibeau Fuhrer <thf@studer-raimann.ch>
 *
 * Up till now, only post request or link-targets were provided
 * with a CSRF-token. As of now, CSRF-tokens or ilCtrl tokens
 * will be appended to every link-target generated for post AND
 * get requests.
 *
 * In order to determine which commands are considered "safe" to
 * execute, this interface can be implemented to provide ilCtrl
 * with a list of commands that don't need to check-pass a CSRF
 * validation. In this scenario the tokens will NOT be appended
 * to a link-target generated by ilCtrl as well.
 *
 * In the future this interface might as well prescribe some other
 * functions that can be used for other security information, e.g.
 * permissions.
 */
interface ilCtrlSecurityInterface
{
    /**
     * This method should return a list of commands (strings)
     * which are considered "safe" commands.
     *
     * Safe in this scenario means, that no CSRF validation is
     * needed for the command to be executed.
     *
     * Any other commands calling the GUI class implementing this
     * interface are considered unsafe and need to check-pass a
     * CSRF validation.
     *
     * @return string[]
     */
    public function getSafeCommands() : array;
}