<?php
include_once './Services/Calendar/classes/class.ilCalendarSettings.php';

/**
 * Class ilCalendarAppointmentPresentationGUI
 *
 * @author	Jesús López <lopez@leifos.com>
 * @version  $Id$
 * @ilCtrl_Calls ilCalendarAppointmentPresentationGUI: ilInfoScreenGUI, ilCalendarAppointmentGUI
*/
class ilCalendarAppointmentPresentationGUI
{
	protected $seed = null;
	protected static $instance = null;
	protected $settings = null;
	protected $appointment;


	/**
	 * Singleton
	 *
	 * @access public
	 * @param
	 * @param
	 * @return
	 */
	protected function __construct(ilDate $seed = null, $a_app)
	{
		global $DIC;
		$this->lng = $DIC->language();
		$this->ctrl = $DIC->ctrl();

		$this->settings = ilCalendarSettings::_getInstance();

		$this->seed = $seed;
		$this->appointment = $a_app;
	}

	/**
	 * get singleton instance
	 *
	 * @access public
	 * @param ilDate $seed
	 * @param  $a_app
	 * @return ilCalendarAppointmentPresentationGUI
	 * @static
	 */
	public static function _getInstance(ilDate $seed, $a_app)
	{
		return new static($seed, $a_app);
		/*
		if(isset(self::$instance) and self::$instance)
		{
			return self::$instance;
		}
		return self::$instance = new ilCalendarAppointmentPresentationGUI($seed, $a_app);
		*/
	}

	function executeCommand()
	{
		global $ilCtrl;

		$next_class = $ilCtrl->getNextClass($this);
		$cmd = $ilCtrl->getCmd("getHTML");

		if($next_class != '')
		{
			// get the path and include
			$class_path = $this->ctrl->lookupClassPath($next_class);
			include_once($class_path);

			// check if the class implements our interface
			$class_name = $this->ctrl->getClassForClasspath($class_path);
			if (in_array("ilCalendarAppointmentPresentation", class_implements($class_name)))
			{
				// forward command to class
				$gui_class = new $class_name();
				$this->ctrl->forwardCommand($gui_class);
			}
		}
	}

	/**
	 * Get seed date
	 */
	public function getSeed()
	{
		return $this->seed;
	}

	public function getHTML()
	{
		include_once "./Services/Calendar/classes/AppointmentPresentation/class.ilAppointmentPresentationFactory.php";

		$tpl = new ilTemplate('tpl.appointment_presentation.html',true,true,'Services/Calendar');

		$info_screen = $this->setInfoScreen($this->appointment);
		$toolbar = $this->fillToolbar($this->appointment);
		$f = ilAppointmentPresentationFactory::getInstance($this->appointment, $info_screen, $toolbar);


		$cat_info = $this->getCatInfo($this->appointment);

		//we can move this to the factory.
		if($cat_info['editable'] and !$this->appointment['event']->isAutoGenerated())
		{
			ilLoggerFactory::getRootLogger()->debug("event get entry".$this->appointment['event']->getEntryId());
			//$tpl->setCurrentBlock('panel_edit_link');
			//$tpl->setVariable('TXT_PANEL_EDIT',$this->lng->txt('edit'));

			$this->ctrl->clearParametersByClass('ilcalendarappointmentgui');
			$this->ctrl->setParameterByClass('ilcalendarappointmentgui','seed',$this->getSeed()->get(IL_CAL_DATE));
			$this->ctrl->setParameterByClass('ilcalendarappointmentgui','app_id',$this->appointment['event']->getEntryId());
			$this->ctrl->setParameterByClass('ilcalendarappointmentgui','dt',$this->appointment['dstart']);
			$toolbar->addButton($this->lng->txt("edit"),
				$this->ctrl->getLinkTargetByClass(array('ilPersonalDesktopGUI', 'ilCalendarPresentationGUI', 'ilCalendarCategoryGUI', 'ilcalendarappointmentgui'), 'askEdit'));
			//$tpl->setVariable('PANEL_EDIT_HREF',
			//	$this->ctrl->getLinkTargetByClass(array('ilPersonalDesktopGUI', 'ilCalendarPresentationGUI', 'ilCalendarCategoryGUI', 'ilcalendarappointmentgui'), 'askEdit'));

			//$tpl->setCurrentBlock('panel_delete_link');
			//$tpl->setVariable('TXT_PANEL_DELETE',$this->lng->txt('delete'));

			$this->ctrl->clearParametersByClass('ilcalendarappointmentgui');
			$this->ctrl->setParameterByClass('ilcalendarappointmentgui','seed',$this->getSeed()->get(IL_CAL_DATE));
			$this->ctrl->setParameterByClass('ilcalendarappointmentgui','app_id',$this->appointment['event']->getEntryId());
			$this->ctrl->setParameterByClass('ilcalendarappointmentgui','dt',$this->appointment['dstart']);
			$toolbar->addButton($this->lng->txt("delete"),
				$this->ctrl->getLinkTargetByClass(array('ilPersonalDesktopGUI', 'ilCalendarPresentationGUI', 'ilCalendarCategoryGUI', 'ilcalendarappointmentgui'), 'askDelete'));
			//$tpl->setVariable('PANEL_DELETE_HREF',
			//	$this->ctrl->getLinkTargetByClass(array('ilPersonalDesktopGUI', 'ilCalendarPresentationGUI', 'ilCalendarCategoryGUI', 'ilcalendarappointmentgui'), 'askDelete'));
			//$tpl->parseCurrentBlock();
		}

		$this->ctrl->getHTML($f);

		// show toolbar
		$tpl->setCurrentBlock("toolbar");
		$tpl->setVariable("TOOLBAR",$toolbar->getHTML());
		$tpl->parseCurrentBlock();


		// show infoscreen
		$tpl->setVariable("CONTENT", $info_screen->getHTML());

		return $tpl->get();
	}

	public function fillToolbar()
	{
		include_once("./Services/UIComponent/Toolbar/classes/class.ilToolbarGUI.php");
		$toolbar = new ilToolbarGUI();

		return $toolbar;
	}

	//TODO remove this stuff from here.
	protected function getCatInfo($a_app)
	{
		include_once('./Services/Calendar/classes/class.ilCalendarCategoryAssignments.php');

		$cat_id = ilCalendarCategoryAssignments::_lookupCategory($a_app['event']->getEntryId());
		$cat_info = ilCalendarCategories::_getInstance()->getCategoryInfo($cat_id);
		$entry_obj_id = isset($cat_info['subitem_obj_ids'][$cat_id]) ?
			$cat_info['subitem_obj_ids'][$cat_id] :
			$cat_info['obj_id'];

		return $cat_info;

	}


	/**
	 * @param $a_app
	 * @return ilInfoScreenGUI
	 */
	public function setInfoScreen($a_app)
	{
		include_once("./Services/InfoScreen/classes/class.ilInfoScreenGUI.php");

		$infoscreen = new ilInfoScreenGUI($this);
		$infoscreen->setFormAction($this->ctrl->getFormAction($this));

		return $infoscreen;

	}
}