<?php
/*
        +-----------------------------------------------------------------------------+
        | ILIAS open source                                                           |
        +-----------------------------------------------------------------------------+
        | Copyright (c) 1998-2006 ILIAS open source, University of Cologne            |
        |                                                                             |
        | This program is free software; you can redistribute it and/or               |
        | modify it under the terms of the GNU General Public License                 |
        | as published by the Free Software Foundation; either version 2              |
        | of the License, or (at your option) any later version.                      |
        |                                                                             |
        | This program is distributed in the hope that it will be useful,             |
        | but WITHOUT ANY WARRANTY; without even the implied warranty of              |
        | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               |
        | GNU General Public License for more details.                                |
        |                                                                             |
        | You should have received a copy of the GNU General Public License           |
        | along with this program; if not, write to the Free Software                 |
        | Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. |
        +-----------------------------------------------------------------------------+
*/

include_once('./Services/EventHandling/interfaces/interface.ilAppEventListener.php');

/**
* Handles events (create,update,delete) for autmatic generated calendar 
* events from course, groups, ...  
*
* @author Stefan Meyer <smeyer.ilias@gmx.de>
* @version $Id$
*
* @ingroup ServicesCalendar
*/
class ilCalendarAppEventListener implements ilAppEventListener
{
	/**
	 * Handle events like create, update, delete
	 *
	 * @access public
	 * @param	string	$a_component	component, e.g. "Modules/Forum" or "Services/User"
	 * @param	string	$a_event		event e.g. "createUser", "updateUser", "deleteUser", ...
	 * @param	array	$a_parameter	parameter array (assoc), array("name" => ..., "phone_office" => ...)	 * 
	 * @static
	 */
	public static function handleEvent($a_component, $a_event, $a_parameter)
	{
		global $ilLog;
		
		switch($a_component)
		{
			case 'Modules/Group':
				switch($a_event)
				{
					case 'create':
						#$cat_id = self::createCategory($a_parameter['object']);
						#self::createAppointments($cat_id,$a_parameter['appointments']);
						$ilLog->write(__METHOD__.': Handling create event');
						break;
					case 'update':
						// TODO: Update relevant events
						$ilLog->write(__METHOD__.': Handling update event');
						break;
					case 'delete':
						// TODO: Delete category
						$ilLog->write(__METHOD__.': Handling delete event');
						break;
				}
				break;
				
		}
	}
	
	/**
	 * Create a category for a new object (crs,grp, ...)
	 * 
	 *
	 * @access public
	 * @return
	 * @static
	 */
	public static function createCategory($a_obj)
	{
		include_once('./Services/Calendar/classes/class.ilCalendarCategory.php');
		
		$cat = new ilCalendarCategory();
		$cat->setTitle($a_obj->getTitle());
		$cat->setType(ilCalendarCategory::TYPE_OBJ);
		$cat->setColor('2F2F2F');
		$cat->setObjId($a_obj->getId());
		return $cat->add();
	}
	
	/**
	 * Create appointments
	 *
	 * @access public
	 * @param
	 * @return
	 * @static
	 */
	public static function createAppointments($a_cat_id,$a_appointments)
	{
		include_once('./Services/Calendar/classes/class.ilCalendarEntry.php');
		include_once('./Services/Calendar/classes/class.ilCalendarCategoryAssignments.php');
		
		foreach($a_appointments as $app_templ)
		{
			$app = new ilCalendarEntry();
			$app->setTitle($app_templ->getTitle());
			$app->setDescription($app_templ->getDescription());
			$app->setFurtherInformations($app_templ->getInformation());
			$app->setStart($app_templ->getStart());
			$app->setEnd($app_templ->getEnd());
			$app->setFullday($app_templ->isFullday());
			$app->setAutoGenerated(true);
			$app->save();
			
			$ass = new ilCalendarCategoryAssignments($app->getEntryId());
			$ass->addAssignment($a_cat_id);
		}
	}
}
?>