<?php

/**
 * Class FakeLanguage
 *
 * @author Fabian Schmid <fs@studer-raimann.ch>
 *         For development and Mockups only
 */
class FakeLanguage extends ilLanguage {

	/**
	 * @inheritDoc
	 */
	public function txt($a_topic, $a_default_lang_fallback_mod = "") {

		$map = array(
			'main'         => "MainMenu",
			'main_slates'  => "Main Menu Items",
			'main_entries' => "Main Menu Sub-items",
			"tab_back"     => "Back",

			'add_slate'       => "Add Main Menu Item",
			'edit_slate'      => "Edit",
			'delete_slate'    => "Delete",
			'translate_slate' => "Translate",

			'slate_position'   => 'Position',
			'slate_title'      => 'Title',
			'slate_icon'       => 'Icon',
			'slate_active'     => 'Active',
			'slate_sticky'     => 'Sticky',
			'slate_mobile'     => 'Mobile',
			'slate_subentries' => 'Sub-Entries',
			'slate_provider'   => 'Provider',
			'slate_actions'    => 'Actions',

			'add_subentry'       => 'Add Sub-Item',
			'edit_subentry'      => 'Edit',
			'delete_subentry'    => 'Delete',
			'translate_subentry' => 'Translate',

			'sub_parent' => "Main Menu Item",

			'sub_position' => 'Position',
			'sub_title'    => 'Title',
			'sub_type'     => 'Type',
			'sub_active'   => 'Active',
			'sub_status'   => 'Status',
			'sub_provider' => 'Provider',
			'sub_actions'  => 'Actions',

			'button_save' => 'Save',

			'slate_title_default'        => 'Title (Default Language)',
			'slate_title_default_byline' => 'Other Translations can be added with the Translation Action after.',
			'slate_active_byline'        => 'Activate this Main Menu Item for all users',
			'slate_sticky_byline'        => 'This Main Menu Item will always be displayed, even if place is scarce (e.g. on Mobile Phones)',
			'slate_type'                 => "Type",
			'slate_type_byline'          => "Main menu Entries can be links directly or can contain Main Menu Subitems",

			'sub_title_default'        => 'Title (Default Language)',
			'sub_title_default_byline' => 'Other Translations can be added with the Translation Action after.',
			'sub_type_byline'          => "Specific type for the Subitem, additional configuration may be needed.",
			"sub_active_byline"        => "Activate this Main Menu Subitem for all users",
		);

		if (isset($map[$a_topic])) {
			return $map[$a_topic];
		}

		return parent::txt($a_topic, $a_default_lang_fallback_mod); // TODO: Change the autogenerated stub
	}
}
