@startuml
Title Authoring


package DomainModel {
package "Question Aggregate" {
	Class "**Question (Aggregate Root)**" {
		**Attributes**
		title =  "The Ultimate Question"
		description = "Towel Day"
		question = "The answer to life, the universe, and everything"
		id = //UUID Universal Unique Identifier//
		revision = //UUID Universal Unique Identifier//
		revision_key = //cryptographic key proving integrity of question//
		type = single_choice, multiple_choice...
	}

	Class "**PossibleAnswer (Entity Object)**" {
	    **Attributes**
		id = //UUID Universal Unique Identifier//
        revision = //UUID Universal Unique Identifier//
	}

	Class "**PossibleSingleChoiceAnswer (Entity Object)**" {
			**Attributes**
            answer_text = "42"
            answer_image_store_location =
            answer_points = 4
            answer_specific_feedback =
    }

	Class "**PossibleMultipleChoiceAnswer (Entity Object)**" {
    		**Attributes**
			answer_text = "42"
	        answer_image_store_location =
	        answer_points_checked = 4
	        answer_points_unchecked = -1
	        answer_specific_feedback =
    }

	Class "**Answer (Value Object)**" {
    		**Attributes**
			answer_text = "42"
	        answer_image_store_location =
	        answer_points_checked = 4
	        answer_points_unchecked = -1
	        answer_specific_feedback =
    }

    "**Question (Aggregate Root)**" "1" o-- "n" "**PossibleAnswer (Entity Object)**"
     "**PossibleAnswer (Entity Object)**" "1"*-- "0" "**PossibleSingleChoiceAnswer (Entity Object)**"
     "**PossibleAnswer (Entity Object)**" "1"*-- "0" "**PossibleMultipleChoiceAnswer (Entity Object)**"

	Class "**CommonFeedback (Value Object)**" {
		**Attributes**
    	Correct solution
    	At least one answer is not correct
    }

     "**Question (Aggregate Root)**" "n"*-- "**CommonFeedback (Value Object)**"



}

}
@enduml
