tinyMCE.addI18n('en.ilimgupload', {
	title                          :'Insert Image',
	upload_image                   :'Upload Image',
	cancel                         :'Cancel',
	upload                         :'Upload',
	src                            :'Source',
	image_select                   :'Choose Image',
	image_alt                      :'Image Information',
	upload_image_from_local_fs     :'From Local Fileystem',
	upload_image_from_local_fs_desc:'Upload an image from local file system',
	upload_image_from_url          :'From URL',
	upload_image_from_url_desc     :'Insert an image from another website',
	border                         :"Border",
	dimensions                     :"Dimensions",
	vspace                         :"Vertical Margin",
	hspace                         :"Horizontal Margin",
	align                          :"Alignment",
	align_baseline                 :"Baseline",
	align_top                      :"Top",
	align_middle                   :"Middle",
	align_bottom                   :"Bottom",
	align_texttop                  :"Text Bottom",
	align_textbottom               :"Text Top",
	align_left                     :"Left",
	align_right                    :"Right",
	insert                         :"Insert",
	width                          :"Width",
	height                         :"Height",
	edit_image                     :"Edit Image",
	edit_image_desc                :"Edit an existing image",
	constrain_proportions          :"Constrain Proportions"
});