// UK lang variables

tinyMCE.addI18n('en.ibrowser',{
	title : 'Image manager',
	desc : 'Image manager',
	library : 'Library',
	preview : 'Preview',
	img_sel : 'Image selection',
	img_info : 'Image information',
	img_upload : 'Image upload',
	images : 'Images',
	src : 'Source',
	alt : 'Description',
	size : 'Size',
	align : 'Text flow',
	height : 'Height',
	width : 'Width',
	reset : 'Reset Dimensions',
	border : 'Border',
	hspace : 'HSpace',
	vspace : 'VSpace',
	select : 'Save',
	cancel : 'Cancel',
	uploadtxt : 'File',
	uploadbt : 'Upload',
	align_default : 'Default',
	align_baseline : 'Baseline',
	align_top : 'Top',
	align_middle : 'Middle',
	align_bottom : 'Bottom',
	align_texttop : 'Text top',
	align_absmiddle : 'Text middle',
	align_absbottom : 'Text bottom',
	align_left : 'Left',
	align_right : 'Right',
	error : 'Error',
	errornoimg : 'Please select an image',
	errornodir : 'Library doesn\'t physically exist',
	errorupload : 'An error occured while handling the file upload.\nPlease try again later',
	errortype : 'Wrong image file type',
	errordelete : 'Delete failed',
	confirmdelete : 'Click OK to delete image!',
	error_width_nan : 'Width is not a number!',
	error_height_nan : 'Height is not a number!',
	error_border_nan : 'Border is not a number!',
	error_hspace_nan : 'Horizontal space is not a number!',
	error_vspace_nan : 'Vertical space is not a number!',
	error_no_obj_id : 'Please save your ILIAS object to get a valid object id. Without an object id the image manager could not be started!'
});