<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'settings.responseChunkSize' => 'get5d005befa369e103283544',
  'settings.outputBuffering' => 'get5d005befa36b1540577059',
  'settings.determineRouteBeforeAppMiddleware' => 'get5d005befa36ba544159092',
  'settings.displayErrorDetails' => 'get5d005befa36c1863176171',
  'settings.httpVersion' => 'get5d005befa36c8119286012',
  'settings.addContentLengthHeader' => 'get5d005befa36cf551274807',
  'settings.routerCacheFile' => 'get5d005befa36d7474779442',
  'settings' => 'get5d005befa36dd395302542',
  'SubEntry5d005befa36e7' => 'get5d005befa36e8669589688',
  'SubEntry5d005befa36f4' => 'get5d005befa36f5635831445',
  'SubEntry5d005befa36fd' => 'get5d005befa36fe938847757',
  'SubEntry5d005befa3705' => 'get5d005befa3706151953127',
  'SubEntry5d005befa370d' => 'get5d005befa370e766337320',
  'SubEntry5d005befa3715' => 'get5d005befa3716398757713',
  'SubEntry5d005befa371d' => 'get5d005befa371e562073798',
  'router' => 'get5d005befa3728661040826',
  'SubEntry5d005befa4373' => 'get5d005befa4377655781545',
  'SubEntry5d005befa43a1' => 'get5d005befa43a3708898716',
  'Slim\\Router' => 'get5d005befa43ba775303382',
  'errorHandler' => 'get5d005befa43c5733351034',
  'SubEntry5d005befa43df' => 'get5d005befa43e0427634558',
  'phpErrorHandler' => 'get5d005befa43f7965838276',
  'SubEntry5d005befa440c' => 'get5d005befa440d005669241',
  'notFoundHandler' => 'get5d005befa4423722504726',
  'notAllowedHandler' => 'get5d005befa443a742228930',
  'environment' => 'get5d005befa4451123022516',
  'request' => 'get5d005befd761a446041263',
  'response' => 'get5d005befda6a7567419450',
  'foundHandler' => 'get5d005befdd64b311518746',
  'SubEntry5d005befdd682' => 'get5d005befdd684052413613',
  'foundHandler.invoker' => 'get5d005befdd69d238438332',
  'callableResolver' => 'get5d005befdfdf7155036999',
  'SubEntry5d005befdfe16' => 'get5d005befdfe17265538359',
  'DI\\Container' => 'get5d005befe2a66147619330',
  'Invoker\\CallableResolver' => 'get5d005befe2ac8610955566',
  'SubEntry5d005befe2ad9' => 'get5d005befe2ada963121341',
);

    protected function get5d005befa369e103283544()
    {
        return 4096;
    }

    protected function get5d005befa36b1540577059()
    {
        return 'append';
    }

    protected function get5d005befa36ba544159092()
    {
        return false;
    }

    protected function get5d005befa36c1863176171()
    {
        return false;
    }

    protected function get5d005befa36c8119286012()
    {
        return '1.1';
    }

    protected function get5d005befa36cf551274807()
    {
        return true;
    }

    protected function get5d005befa36d7474779442()
    {
        return false;
    }

    protected function get5d005befa36e8669589688()
    {
        return $this->delegateContainer->get('settings.httpVersion');
    }

    protected function get5d005befa36f5635831445()
    {
        return $this->delegateContainer->get('settings.responseChunkSize');
    }

    protected function get5d005befa36fe938847757()
    {
        return $this->delegateContainer->get('settings.outputBuffering');
    }

    protected function get5d005befa3706151953127()
    {
        return $this->delegateContainer->get('settings.determineRouteBeforeAppMiddleware');
    }

    protected function get5d005befa370e766337320()
    {
        return $this->delegateContainer->get('settings.displayErrorDetails');
    }

    protected function get5d005befa3716398757713()
    {
        return $this->delegateContainer->get('settings.addContentLengthHeader');
    }

    protected function get5d005befa371e562073798()
    {
        return $this->delegateContainer->get('settings.routerCacheFile');
    }

    protected function get5d005befa36dd395302542()
    {
        return [
            'httpVersion' => $this->get5d005befa36e8669589688(),
            'responseChunkSize' => $this->get5d005befa36f5635831445(),
            'outputBuffering' => $this->get5d005befa36fe938847757(),
            'determineRouteBeforeAppMiddleware' => $this->get5d005befa3706151953127(),
            'displayErrorDetails' => $this->get5d005befa370e766337320(),
            'addContentLengthHeader' => $this->get5d005befa3716398757713(),
            'routerCacheFile' => $this->get5d005befa371e562073798(),
        ];
    }

    protected function get5d005befa4377655781545()
    {
        return $this->delegateContainer->get('DI\\Container');
    }

    protected function get5d005befa43a3708898716()
    {
        return $this->delegateContainer->get('settings.routerCacheFile');
    }

    protected function get5d005befa3728661040826()
    {
        $object = new Slim\Router(NULL);
        $object->setContainer($this->get5d005befa4377655781545());
        $object->setCacheFile($this->get5d005befa43a3708898716());
        return $object;
    }

    protected function get5d005befa43ba775303382()
    {
        return $this->delegateContainer->get('router');
    }

    protected function get5d005befa43e0427634558()
    {
        return $this->delegateContainer->get('settings.displayErrorDetails');
    }

    protected function get5d005befa43c5733351034()
    {
        $object = new Slim\Handlers\Error($this->get5d005befa43e0427634558());
        return $object;
    }

    protected function get5d005befa440d005669241()
    {
        return $this->delegateContainer->get('settings.displayErrorDetails');
    }

    protected function get5d005befa43f7965838276()
    {
        $object = new Slim\Handlers\PhpError($this->get5d005befa440d005669241());
        return $object;
    }

    protected function get5d005befa4423722504726()
    {
        $object = new Slim\Handlers\NotFound();
        return $object;
    }

    protected function get5d005befa443a742228930()
    {
        $object = new Slim\Handlers\NotAllowed();
        return $object;
    }

    protected function get5d005befa4451123022516()
    {
        return $this->resolveFactory(static function () {
    return new \Slim\Http\Environment($_SERVER);
}, 'environment');
    }

    protected function get5d005befd761a446041263()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
    return \Slim\Http\Request::createFromEnvironment($c->get('environment'));
}, 'request');
    }

    protected function get5d005befda6a7567419450()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
    $headers = new \Slim\Http\Headers(['Content-Type' => 'text/html; charset=UTF-8']);
    $response = new \Slim\Http\Response(200, $headers);
    return $response->withProtocolVersion($c->get('settings')['httpVersion']);
}, 'response');
    }

    protected function get5d005befdd684052413613()
    {
        return $this->delegateContainer->get('foundHandler.invoker');
    }

    protected function get5d005befdd64b311518746()
    {
        $object = new DI\Bridge\Slim\ControllerInvoker($this->get5d005befdd684052413613());
        return $object;
    }

    protected function get5d005befdd69d238438332()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
    $resolvers = [
        // Inject parameters by name first
        new \Invoker\ParameterResolver\AssociativeArrayResolver(),
        // Then inject services by type-hints for those that weren't resolved
        new \Invoker\ParameterResolver\Container\TypeHintContainerResolver($c),
        // Then fall back on parameters default values for optional route parameters
        new \Invoker\ParameterResolver\DefaultValueResolver(),
    ];
    return new \Invoker\Invoker(new \Invoker\ParameterResolver\ResolverChain($resolvers), $c);
}, 'foundHandler.invoker');
    }

    protected function get5d005befdfe17265538359()
    {
        return $this->delegateContainer->get('Invoker\\CallableResolver');
    }

    protected function get5d005befdfdf7155036999()
    {
        $object = new DI\Bridge\Slim\CallableResolver($this->get5d005befdfe17265538359());
        return $object;
    }

    protected function get5d005befe2a66147619330()
    {
        $object = new DI\Container(NULL, NULL, NULL);
        return $object;
    }

    protected function get5d005befe2ada963121341()
    {
        return $this->delegateContainer->get('Psr\\Container\\ContainerInterface');
    }

    protected function get5d005befe2ac8610955566()
    {
        $object = new Invoker\CallableResolver($this->get5d005befe2ada963121341());
        return $object;
    }

}
