CREATE TABLE news_item
(
	id			INT			NOT NULL PRIMARY KEY AUTO_INCREMENT,
	obj_id		INT			NOT NULL DEFAULT 0,
	obj_type	CHAR(10)	NOT NULL DEFAULT '',
	sub_obj_id	INT			NOT NULL DEFAULT 0,
	sub_obj_type	CHAR(10)	NOT NULL DEFAULT '',
	cdate		DATETIME	NOT NULL DEFAULT '0000-00-00 00:00:00',
	content_type	VARCHAR(20)	NOT NULL DEFAULT '',
	priority	TINYINT	NOT NULL DEFAULT 0,
	title		VARCHAR(200)	NOT NULL DEFAULT '',
	content			TEXT	NOT NULL DEFAULT ''
)
