name: legacy-ui-checks
on:
  schedule:
     # Run every 12 hours
    - cron: '0 3,15 * * *'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run report'
        required: true
        default: 'trunk'
        type: choice
        options:
          - trunk
          - release_9
permissions:
  contents: read
  pull-requests: read
jobs:
  tests:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.changes.outputs.all }}
    strategy:
      fail-fast: false
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: trunk

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, gd, json, readline, xsl, xml, mysql
          tools: composer:v2
          coverage: none

      - name: Install Node dependencies
        run: npm clean-install --omit-dev --ignore-scripts

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --ignore-platform-reqs

      - name: 'PHStan Custom Rules'
        run: scripts/PHPStan/run_legacy_ui_report.sh

      - name: 'Store Report'
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: Reports
          retention-days: 30
