name: Pull Request Stats
on:
  pull_request_target:
jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts: true
          sort-by: 'COMMENTS'